### ISSUE TITLE
Toaster.

### ISSUE THREAD

**Issue by blay09** [blay09/CookingForBlockheads#101]
Free cooking of toast (2 at once), taking about a minute? Just...for fun.

**Comment by blay09** [comment]
Yo @Zero9o1o - I know you've always wanted to model a toaster.

**Comment by Zero9o1o** [comment]
Here is your toaster?
https://drive.google.com/file/d/0Bxivg_rr7WtsalVBUU81LWRwdW8/view?usp=sharing

**Comment by blay09** [comment]
Closed in favor of #117
