### ISSUE TITLE
Add Support for "Still Hungry" Mod & "Useful Food" Mod

### ISSUE THREAD

**Issue by SugarDaddii** [blay09/CookingForBlockheads#102]
Hey when i try to craft Things from 
these two mods it says so :

http://abload.de/image.php?img=beefburger3wjsw.jpg

and they are normal shaped/unshaped recipes!

**Comment by BlayTheNinth** [comment]
Likely fixed in #121. If the mods need further special support feel free to re-open once they reach Minecraft 1.9.4.
