### ISSUE TITLE
Background switches after scroll down in menu!

### ISSUE THREAD

**Issue by SugarDaddii** [blay09/CookingForBlockheads#103]
When i click on one recipe and than scroll down the  background is changing!

See :

http://abload.de/image.php?img=backa4kqi.jpg

**Comment by blay09** [comment]
Will be fixed on 1.8.9+

**Comment by SugarDaddii** [comment]
Mmh Thats not useful for me because i have a 1.7.10 world and my girlfriend will kill me if i delete it 😊
