### ISSUE TITLE
Support dynamic food hunger/saturation values via AppleCore

### ISSUE THREAD

**Issue by mctynp** [blay09/CookingForBlockheads#105]
The AppleCore API supports dynamic value for how much hunger/saturation is restored by a given food. To improve integration with other mods such as Spice of Life, consider using AppleCore's API (applecore/api/food/FoodValues.get()) in the Cooking For Blockheads Container/Comparator* classes to fetch hunger and saturation levels instead of calling the Vanilla Minecraft functions. This change could help ensure that sorting by hunger/saturation shows the currently-best foods for a given player.

**Comment by blay09** [comment]
Thanks, I was wondering why the sorting would get messed up on some modpacks.
