### ISSUE TITLE
Alternate Storage blocks

### ISSUE THREAD

**Issue by pip69** [blay09/CookingForBlockheads#109]
Rather than have multiple Fridges, other block for items.  
Spice Rack.  Hangs over head
Dining Table.  Connects if you add more than 1.  Best for showing off completed recipes.

**Comment by Omegapsychosis** [comment]
Other additions could be...

Freezer  - Snowballs/Ice/etc.
Cupboards - Alternative storage block to the fridge for decorative purposes. Dried Goods storage

**Comment by bookerthegeek** [comment]
Intigtation that would also would be nice....

1) Logistics pipes.
2) Storage drawers.
3) Applied Energistics

**Comment by blay09** [comment]
Closed in favor of #117 

and no, there will never be AE support (and it's also completely unrelated to this particular issue).
