### ISSUE TITLE
Cooking Table is kicking me out of server.

### ISSUE THREAD

**Issue by john8red** [blay09/CookingForBlockheads#111]
I was using this mod on Magic Farm 3 and the cooking table won't allow me to open it anymore when it's by the other blocks. When I try to it just kicks me out of the server. Do you know the problem?

**Comment by blay09** [comment]
What version are you running on? Do you have a log of the server error that happens?

If you're on an old version, there used to be a problem with recipes involving mushrooms, so you could try removing all mushrooms from your fridge & inventory and see if it'll work then.

**Comment by john8red** [comment]
I am running version 1.0.128 and nothing shows up in the server console but I get the message "A fatal error has occured, this connection is terminated".

**Comment by john8red** [comment]
I figured it out. I took the stock out and now it works fine.

**Comment by blay09** [comment]
Pretty sure this was fixed in version 1.0.134 (Fixed disconnect when opening the table while too many recipes are available)
