### ISSUE TITLE
Crash in Sky Factory 2, when clicking the recipe in NEI

### ISSUE THREAD

**Issue by WDevil3221** [blay09/CookingForBlockheads#113]
[crash-2016-03-22_10.18.07-client.txt](https://github.com/blay09/CookingForBlockheads/files/183421/crash-2016-03-22_10.18.07-client.txt)
Got a crash whenever I click any of the recipes on NEI, any fixes for this?

**Comment by blay09** [comment]
This crash log has nothing to do with Cooking for Blockheads, it looks like Pam's Harvestcraft updated and the NEI integration provided bei Tonius' NEI Integration mod broke as a result. You'll have to let NEIIntegration know.
