### ISSUE TITLE
Bean Stew for Random Things is not working due to not being a shaped recipe

### ISSUE THREAD

**Issue by shortybsd** [blay09/CookingForBlockheads#114]
Random Things Version: RandomThings-MC1.9-3.6.9
Forge Version: 1.9-12.16.0.1862-1.9
Cannot craft Bean Stew from Random Things mod due to it being a shaped recipe. Is there any way to specify the shape of the recipe?

**Comment by bookerthegeek** [comment]
You can add one with Mod tweaker. I'll post one for you tonight if you like.

**Comment by blay09** [comment]
Cooking for Blockheads should be picking up both shaped and unshaped recipes, so if it doesn't it's a bug.

**Comment by bookerthegeek** [comment]
True,  but until it does...

**Comment by shortybsd** [comment]
Thank you, could you send an example with ModTweaker? I might have to implement that before this mod gets updated.

**Comment by blay09** [comment]
Likely fixed by https://github.com/blay09/CookingForBlockheads/commit/9ed9e04c4ea1b32b76ff5ecb960ca2938964e432
