### ISSUE TITLE
Additional Kitchen Blocks

### ISSUE THREAD

**Issue by blay09** [blay09/CookingForBlockheads#117]
- [x] Toaster (will turn bread into toast at no cost other than time)
- [x] Spice Rack (storage)
- [ ] Kitchen Counter / Cupboard (storage)
- [ ] Freezer (will provide snowballs and ice to recipes)
- [x] Milk Canister (will store milk as a liquid to provide to recipes)

**Comment by RogueWarrior76** [comment]
I was thinking a great item for storage would be a pantry. You could make it like the fridge and able to stack 1 on the other.
