### ISSUE TITLE
[1.8.9][suggestion] sink to auto make fresh water

### ISSUE THREAD

**Issue by elkillo** [blay09/CookingForBlockheads#125]
i am currently using the 1.8.9 version of CFB and its helps save alot of time. my suggestion is why not let the sink make fresh water when a bucket is available in the fridge/tool rack? will save a ton of crafting time. Awesome mod btw =D

**Comment by blay09** [comment]
I don't see how this would save a ton of crafting time, you can literally craft a stack of fresh water using two clicks if you have a sink. There might also be people who don't want this happening and your suggestion does not offer a way of control over it (and any possible way of control is likely out of this mod's design scope).

**Comment by elkillo** [comment]
how can i click a stack with 2 clicks? i have to go back and forth with a bucket and the fridge to craft fresh water.... or am i not doing something right?

**Comment by blay09** [comment]
Cooking Table connected to sink.

**Comment by elkillo** [comment]
then i guess i have a bug report for the 1.8.9 version. i have the sink next to the cooking table and i have no option to make fresh water.
