### ISSUE TITLE
Crash when respawning

### ISSUE THREAD

**Issue by founderio** [blay09/CookingForBlockheads#126]
Not 100% reproducable, but it IS reproducable.

Version: 3.0.3 (On the BTM pack)
Crashlog: [crash-2016-05-27_20.55.51-client.txt](https://github.com/blay09/CookingForBlockheads/files/287192/crash-2016-05-27_20.55.51-client.txt)

**Comment by darkhax** [comment]
I can confirm this crash as well. Happened to me using same version of the mod and same mod pack. Also the same world :p
