### ISSUE TITLE
[1.8.9]Sink is next to cooking table and it does not have the option to make fresh water

### ISSUE THREAD

**Issue by elkillo** [blay09/CookingForBlockheads#127]
same as the title only with pictures!

version 1.8.9-2.0.2
forge 11.15.1.1902
Pams 1.8.9d

![2016-05-30_19 50 12](https://cloud.githubusercontent.com/assets/19398102/15659856/2ca7602c-26a0-11e6-8097-6cdfe00705c7.png)

 
![2016-05-30_19 53 09](https://cloud.githubusercontent.com/assets/19398102/15659868/50241dce-26a0-11e6-84b8-e202d254e5bb.png)

**Comment by bookerthegeek** [comment]
Is their water in the sink?

**Comment by BlayTheNinth** [comment]
The current 1.8.9 and 1.9.4 versions always require water to be piped into the sink for it to work as the sinkRequiresWater option is ignored. This will be fixed for 1.9.4 and higher.
