### ISSUE TITLE
Fridge cause glitched movement

### ISSUE THREAD

**Issue by darkhax** [blay09/CookingForBlockheads#128]
When sprinting onto the fridge, player movement gets completely glitched. Teleporting off of the fridge seems to cause the entire screen to freak out. 
![glitch](https://cloud.githubusercontent.com/assets/2250798/15665721/e00a20c2-26c9-11e6-9c17-0424605f8f7d.gif)

Edit: I totally know the diference between a fridge and a stove...

**Comment by BlayTheNinth** [comment]
Not happening to me, are you sure it's the fridge and not the cake / animal heads on top?
