### ISSUE TITLE
[1.9.4] Can't make Fresh Water or any following recipes like Salt or Dough

### ISSUE THREAD

**Issue by JamesGrimm** [blay09/CookingForBlockheads#132]
I have a sink built and placed right next to the crafting block. I even have tried putting a bucket in the fridge or on a tool rack. Unless I manually make fresh water, none of the crafting recipes related to water items work.

**Comment by BlayTheNinth** [comment]
Probably same as #127

**Comment by BlayTheNinth** [comment]
The current 1.8.9 and 1.9.4 versions always require water to be piped into the sink for it to work as the sinkRequiresWater option is ignored. This will be fixed for 1.9.4 and higher.
