### ISSUE TITLE
Automatically detect food ingredients and make them show up

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/CookingForBlockheads#133]
Right now I have to add all those manually, which was fine for Harvestcraft's salt and water, but More Foods has a whole lot more of these.

**Comment by Timeslice42** [comment]
Alternatively (or additionally) it would be great to have a config setting for adding our own list of items which should show up. Something like the config that Forestry uses for it's backpacks would be great.

This would allow us to add some of the custom mod items from our modpack to your crafting.

On an unrelated note, are you still supporting 1.7.10? Our pack is a 1.7.10 pack.

**Comment by Syndaryl** [comment]
I think the most thorough way to do this would be to scan the item database for everything edible, and then recursively scan the recipes for the components. That gets weird when the components are oreDict components, though, which is the case for a lot of food mods with good compatibility.
A config list would be a lot less complicated.

**Comment by Timeslice42** [comment]
Even scanning wouldn't get everything. For example vanilla minecraft cakes (and PHC equivalents) would get left out.

**Comment by BlayTheNinth** [comment]
Closing in favor of the new JSON compat files. Maintaining them is probably less work than a robust detection system.
