### ISSUE TITLE
Backport minecraft:air render crash fix to 1.8.9

### ISSUE THREAD

**Issue by AngelKairi** [blay09/CookingForBlockheads#134]
So whilst streaming my progress on my newer version of my Modpack, I've come across this strange render error when I respawn near my set of Kitchen blocks. (all of them btw)

While respawning two times, it'll crash the game with this render error. (Has happened 3 times so far)

http://paste.ubuntu.com/17284555/

-Optifine IS installed. Latest Version

**Comment by BlayTheNinth** [comment]
Are you on version 3.0.7 or higher?

**Comment by AngelKairi** [comment]
This is for 1.8.9 though. I prob should of mentioned it in the title. :c Sorry.

**Comment by BlayTheNinth** [comment]
I'll see about backporting the [fix](https://github.com/blay09/CookingForBlockheads/commit/072b3e4c2ab5bac0a5b6d99fbc4f4303b91ed15c) when I find some extra time.

**Comment by BlayTheNinth** [comment]
I doubt I'll go back to fix this, 1.8.9 is pretty much dead.
