### ISSUE TITLE
Container sorting

### ISSUE THREAD

**Issue by Thiana** [blay09/CookingForBlockheads#140]
Could you please add support for the various sorting/deposit mods? ie, Vazkii's Quark deposit buttons and cpw11's Inventory Sorter. For some reason they don't see the fridge as a normal container.

Thanks.

**Comment by BlayTheNinth** [comment]
Fridge and Counter will be compatible with Quark's dropoff button in the next version. cpw's InventorySorter [does not support IItemHandlers yet](https://github.com/cpw/inventorysorter/blob/master/src/main/java/cpw/mods/inventorysorter/Action.java#L136-L137).
