### ISSUE TITLE
 crashes my client to minecraft main menue when i open the manuel for cooking for blockheads

### ISSUE THREAD

**Issue by Phizzhead** [blay09/CookingForBlockheads#141]
hears the logs of my client 
https://gist.github.com/Phizzhead/1e1e3256c15c4b91653c5bb9678d8a15

**Comment by BlayTheNinth** [comment]
There's no actual crash log in those logs, it just ends abruptly at line 6992.

**Comment by BlayTheNinth** [comment]
#154
