### ISSUE TITLE
Infinite Heavy Cream

### ISSUE THREAD

**Issue by doctorkreger** [blay09/CookingForBlockheads#142]
Whenever I have a mixing bowl attached to my kitchen, I can pull infinite heavy cream via the soy milk recipe. This seems to be in error, as I have no soy beans on my farm yet, and have no other milk source.

**Comment by doctorkreger** [comment]
After more testing, it appears simply having a sink and cooking table together enables infinite heavy cream assuming the mixing bowl is present.

**Comment by elkillo** [comment]
i can also confirm that if you have salt you can also get infinite cheese! everyone loves cheese.

**Comment by CJL48** [comment]
Also, note that disabling the harvestcraft soy replacement in recipes will not stop this from happening- you can still get infinite cheese/heavy cream/etc, as if you had an infinite supply of milk.

**Comment by everseeking** [comment]
Confirmed have this issue as well
