### ISSUE TITLE
Wool in the Sink

### ISSUE THREAD

**Issue by digitalgadget** [blay09/CookingForBlockheads#143]
Running modpack Expedition.  When right-clicking colored wool to the Sink it returns invalid number of white wool.  Specifically it takes one block from the colored stack and returns the quantity of the colored stack as white wool blocks.  For example if you have 3 brown wool, right click on the sink, you now have 2 brown wool and receive 2 white wool.

**Comment by everseeking** [comment]
Also noticed receiving an extra white wool after it is "cleaned" as mentioned above.
