### ISSUE TITLE
Update checker fails because SQL database user does not have access.

### ISSUE THREAD

**Issue by Claycorp** [blay09/CookingForBlockheads#145]
http://pastebin.com/rQvpwB7v

**Comment by BlayTheNinth** [comment]
Was this actually causing a crash or just spamming the log? I've moved the script for now so hopefully Forge's update checker can handle a 404 better than it handles garbage, **if** it's crashing.

**Comment by Claycorp** [comment]
It doesn't crash just letting you know it wasn't working as intended. I was going through a log for someone and noticed it. Thought I'd report it.

**Comment by BlayTheNinth** [comment]
Alright, thanks. Was worried I caused a disaster by my webserver being broken again. :D
