### ISSUE TITLE
Infinite water buckets with sink

### ISSUE THREAD

**Issue by vocin** [blay09/CookingForBlockheads#149]
If you right click a Sink with a empty bucket, it gives you 1000 water buckets

![screenshot_101](https://cloud.githubusercontent.com/assets/461279/17161138/e711cd12-5378-11e6-8cce-5e016fc81169.png)

Playing FTB Unstable 1.10 v4.2.4 (with Cooking for Blockheads v3.1.26), so i'm not sure it's a FTB bug or a Cooking for Blockeads bug

**Comment by BlayTheNinth** [comment]
See https://github.com/SleepyTrousers/EnderIO/issues/3507#issuecomment-233017995 - it's apparently an issue in IC2.

**Comment by vocin** [comment]
Yeah, so the problem it's not here xD. Thank you for your time (and of course for your mode - it makes my life easier with food ^-^)
