### ISSUE TITLE
Cooking table "eats" empty buckets from inventory

### ISSUE THREAD

**Issue by Syndaryl** [blay09/CookingForBlockheads#157]
Version 3.1.26, forge 12.18.1.2018

To replicate:
- build a cooking table, a sink, and a fridge, and place them together in a multiblock kitchen.
- put some Fresh Water, salt, and flour in the fridge.
- put multiple empty buckets in your inventory (you must have 2 or more buckets - bug does not manifest with one bucket)
- craft dough (bug can also be replicated with other water-using recipes, I suspect also milk but have not confirmed).

**Expected:** Number of empty buckets in inventory would not change, Fresh Water in fridge would be consumed. 

**Actual:** Fresh water does not change, empty buckets are consumed. If this leaves you with one bucket, that bucket is not consumed

(This can also be replicated if the ingredients are in your inventory - not sure if it can be replicated w/out the multiblock kitchen)

**Second, probably related issue:**
If the buckets are instead full, for instance with water, they are untouched, but you can still craft recipes that need water (even if there is no Fresh water in your inventory or the fridge)

**Comment by LaVidaYokel** [comment]
v4.1.12
forge 12.18.1.2066

I'm experiencing the same issue except it will also manifest if there is only one empty bucket in my inventory.  This happens with both water and milk recipes.
