### ISSUE TITLE
easy recipe for cooking table intentional?

### ISSUE THREAD

**Issue by Terpo** [blay09/CookingForBlockheads#159]
CookingForBlockheads-mc1.9.4-3.1.26
I'm playing on MC 1.10.2 with Forge build 2011

There is a recipe with one hardened black stained clay and a chest to craft the cooking table. I don't think that is intentional ?!

Recipe:
null null null
null stained_hardened_clay:15 null
null chest null

**Comment by BlayTheNinth** [comment]
#139 It's the Kitchen Counter recipe giving the wrong item.
