### ISSUE TITLE
Salt....

### ISSUE THREAD

**Issue by DnTheMn** [blay09/CookingForBlockheads#163]
With the Cooking For Blockheads multi-block kitchen and a Pam's Harvestcraft pot you can basically get unlimited amounts of Pam's Harvestcraft salt for free (can sit there and spam shift + click on the recipe in the cooking table). The salt can then be used to make Brine from Mekanism, which means you can achieve 4x ore processing without having to build the thermal evaporation towers as the intended progression through Mekanism. A simple solution would be to disable Pam's Harvestcraft salt from being used to create brine and only allow the Mekanism salt (which has to be mined in word) to be used to create the brine or the towers. i will post on the mekanism github too incase you think the issue lies with them (https://github.com/aidancbrady/Mekanism/issues/3684)

**Comment by BlayTheNinth** [comment]
You can get salt for free with vanilla Pam's too, it literally just takes water. Cooking for Blockheads just lets you craft it without setting up an auto-crafting (which would be trivial to do as well). This is an issue between Pam's and Mekanism, nothing to do with this mod.
