### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by DnTheMn** [blay09/CookingForBlockheads#164]
Repro steps:
Craft a book
Cook the book
Craft CookingForBlockheads #NoFilter edition by putting the book you just crafted into your crafting window and pulling it out

Right click on CookingForBlockheads #NoFilter edition

Observe error "Fatal error. This connection has been terminated"

**Comment by BlayTheNinth** [comment]
#NoFilter Edition has already been disabled in the latest version because of this issue, it will be re-enabled once it's fixed. #154

**Comment by DnTheMn** [comment]
ok thanks
