### ISSUE TITLE
crafting table not reading oven tools?

### ISSUE THREAD

**Issue by Bigmanvegas** [blay09/CookingForBlockheads#165]
ver. 1.8.9 2.0.2 The crafting table isn't reading that the oven has any tools in it. I tried both sides of the table and nothing. I can store tools in the oven. It does detect when they are in the fridge and racks.

**Comment by BlayTheNinth** [comment]
Pretty sure that's fixed in 1.9.4+, 1.8.9 is no longer supported.

**Comment by Bigmanvegas** [comment]
Ah ok then I'll just have to use racks while I wait for mods to update...
