### ISSUE TITLE
[Suggestion] Improve Kitchen Blocks' cohesion

### ISSUE THREAD

**Issue by Xiaminou** [blay09/CookingForBlockheads#166]
Let me start by saying I like this mod, it goes very well with Pam's Harvestcraft and Spice of Life, and makes managing your food resources much easier.
I like the looks of all the different blocks, especially the double block fridge. However, I think they don't fit together very well. Would it be possible to have full block height (built in) alternatives to those blocks that would connect without leaving gaps? Like those in Decocraft2 ([example](http://i.imgur.com/xM3qkYB.png)).
Now that there are Toasters and Milk Jars to place on top of the blocks with the blocks not being full height they're basically floating above.

**Comment by BlayTheNinth** [comment]
I plan to add some kind of item that will turn the model into a larger, full-block model, just need to make the actual models for that first.

**Comment by Nezraddin** [comment]
I'm not sure if that's in the planning already as well, but in addition to this idea:
- It would be wonderful if there were some kind of "filler" blocks. 
  So blocks which you can hide in the wall or actually some sort of "kitchen floor block" (texture wise) with which you can add the sink, oven etc. a bit away from each other. Like having your oven at the one wall and your sink and cooking table at the other wall like 4 blocks away.

I don't know if that is difficult code-wise, but I just thought I throw it in here. _hides_
Love the mod! :)

**Comment by BlayTheNinth** [comment]
The latest release for 1.11.2 adds new models as well as a kitchen floor block which can connect kitchen blocks over longer distances.

![Screenshot](https://media-elerium.cursecdn.com/attachments/198/317/2017-03-16_15.png)

**Comment by Xiaminou** [comment]
Cool! Will you release them for 1.10.2 as well or this is only 1.11.2?

**Comment by BlayTheNinth** [comment]
For the time being 1.11.2 only. If by the time I'm done going over updating my other mods and 1.10.2 is still the prominent modded version I'll probably backport it.
