### ISSUE TITLE
Gregtech knife doesn't take damage in tool rack

### ISSUE THREAD

**Issue by bear989** [blay09/CookingForBlockheads#168]
Greg added his knife meta tool to the ore dic. of the cutting board from pam's. but when it is in a  drying rack it doesn't take damage on use.

**Comment by BlayTheNinth** [comment]
Does it take damage when used in normal crafting (via crafting table) of Pam's recipes?

**Comment by bear989** [comment]
yes it does

**Comment by BlayTheNinth** [comment]
There doesn't seem to be a GregTech for 1.10.2 and the 1.7.10 version of Cooking for Blockheads is no longer supported, sorry. Feel free to re-open should GregTech update.
