### ISSUE TITLE
Agricultural Revolution compat

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/CookingForBlockheads#173]
adds a cow too apparently that should work for the Cow in a Jar

**Comment by b0bst3r** [comment]
On this, by default AR disables all food smelting so it has to be done in the AR brick oven.  Is there anyway you can add something to also allow your oven to function?

**Comment by BlayTheNinth** [comment]
Yeah, there's a system in place for Pam's already which can be used. Thanks for the info.

**Comment by b0bst3r** [comment]
So I can do it now or do you mean you can make the addition easily because you did the same for Pams?

**Comment by BlayTheNinth** [comment]
It'll likely be possible once Agricultural Revolution support is actually implemented.

**Comment by BlayTheNinth** [comment]
Closing for now since Agricultural seems to be stuck on 1.10 and old versions are only getting bug fixes at this point.
