### ISSUE TITLE
whack-a-mole'ish behavior in cooking table

### ISSUE THREAD

**Issue by DoomSquirter** [blay09/CookingForBlockheads#178]
running CookingForBlockheads_1.10.2-4.2.26.jar (and prev version had same behavior)

playing pack futures edge on curse (https://forum.feed-the-beast.com/threads/1-10-2-curse-futures-edge-hardcore-quests.185526/)

have a couple fridges full of pam's harvestcraft, a couple cows in a jar, sink, etc.  

when I go to make fresh milk, the icon for the fresh milk changes from fresh milk to a random other food item and back again.  Flour seems to do same thing.  I think this is visual only since if I shift-craft a bunch, I get fresh milk/flour not the erroneous item.  I have a few biomes o plenty items (fruit or something) in the fridges as well, but it's 99% vanilla/pam's.  

forgot to mention one thing.  the revolving picture issue happens only after you craft the first batch it seems.  so if you open the gui straight out, no flickering of images occurs, but as soon as you craft one item (fresh milk, flour in this case) then it starts replacing the icon.

**Comment by BlayTheNinth** [comment]
This sounds like intended behaviour - for recipes with ore-dictionary ingredients it scrolls through the available ingredients (in this case it was probably fresh milk and soy milk). The ingredient item can be locked to whatever it is currently showing by clicking on it.

**Comment by CovertJaguar** [comment]
The list of food outputs does like to rearrange itself all the time. Doesn't matter what the sorting setting setting is, I think the client just sorts it different from the server. Clicking the same place gets you the food you started on still, but like you want to make jam and after clicking on jam once, it now looks like you would be making scrambled eggs or something but still makes jam if you keep clicking.
