### ISSUE TITLE
Cross-mod crash w/ Translocators and ActuallyAdditions

### ISSUE THREAD

**Issue by MrPipperz** [blay09/CookingForBlockheads#179]
Using latest AA release (r88), Translocators 1-8 latest release (2.1.3.34) and latest CCC libraries, and latest Cooking for Blockheads release (4.2.26). Using latest forge #2171 (same crash results with #2099)

Attaching a Translocator to an Item Phantomface which is already bound to a CfBH kitchen multiblock (any of them seemingly, have tested several, same result) results in a crash a few ticks later.

Have tested in a new custom instance with only the required mods and libraries loaded (well, plus Blood Magic by mistake, but I doubt it matters), same result.

It is worth noting that Translocators seems to check whether it can properly interact with a container before allowing the block to place; they cannot normally be placed on the CfBH blocks.

Within the same instance and session I checked that the Phantomfaces were able to route items to the CfBH blocks with vanilla hoppers prior to attempting to place a Translocator on the Phantomface, this was successful each time.

Attempting to reload the world results in the same crash, effectively resulting in a "bugged" save.

I realize this is an odd corner case and that Translocators is most likely responsible, but I thought you'd appreciate a report.

Happy holidays!
[crash-2016-12-04_08.39.07-server.txt](https://github.com/blay09/CookingForBlockheads/files/629652/crash-2016-12-04_08.39.07-server.txt)
[crash-2016-12-04_09.53.18-server.txt](https://github.com/blay09/CookingForBlockheads/files/629653/crash-2016-12-04_09.53.18-server.txt)

**Comment by BlayTheNinth** [comment]
Sounds like this is an issue on Actually Additions' side. https://github.com/Ellpeck/ActuallyAdditions/issues/446#issuecomment-264715727
