### ISSUE TITLE
[suggestion] Recursive recipe

### ISSUE THREAD

**Issue by Piratdu52** [blay09/CookingForBlockheads#180]
Currently CookingForBlockheads shown only recipy **directly** craftable, so if i have some wheat it will only show me flour and not bread and toast.
Why not adding recipe result to the list of ingredients an rerun the "avaibleRecipe" function ? If the result of the last batch == the result of the current batch show the list of recipe.

**Comment by BlayTheNinth** [comment]
duplicate of #112
