### ISSUE TITLE
Spice of Life compatibility?

### ISSUE THREAD

**Issue by Wingyl123** [blay09/CookingForBlockheads#186]
I installed Hunger Overhaul and Spice of Life and now everything that can actually be eaten is called 'unnamed' in the cooking table and trying to sort by anything except for name causes the error "a fatal error has occured, this connection is terminated" and kicks me to the multiplayer world selection screen.

And yes, the 'occured' is _actually spelt like that_ despite the word being spelt _occurred._

**Comment by Wingyl123** [comment]
Looking at the mod list, it seems that, if it's sorted by load order (seems likely), then just getting Cooking for Blockheads to load last might work-that's done by renaming it with a Z in front, right?

ETA: I held shift over a food item (can't remember which one) in the Cooking Table GUI and got an actual crash. 
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 9/02/17 7:54 PM
Description: Unexpected error

java.lang.ArithmeticException: Division undefined
	at java.math.BigDecimal.divide(BigDecimal.java:1741)
	at com.udojava.evalex.Expression$5.eval(Expression.java:768)
	at com.udojava.evalex.Expression$41.eval(Expression.java:1232)
	at com.udojava.evalex.Expression$41.eval(Expression.java:1232)
	at com.udojava.evalex.Expression$41.eval(Expression.java:1232)
	at com.udojava.evalex.Expression$41.eval(Expression.java:1232)
	at com.udojava.evalex.Expression$41.eval(Expression.java:1232)
	at com.udojava.evalex.Expression$Function.lazyEval(Expression.java:519)
	at com.udojava.evalex.Expression.eval(Expression.java:1254)
	at squeek.spiceoflife.foodtracker.FoodModifier.getFoodGroupModifier(FoodModifier.java:109)
	at squeek.spiceoflife.foodtracker.FoodModifier.getFoodModifier(FoodModifier.java:140)
	at squeek.spiceoflife.foodtracker.FoodModifier.getFoodModifier(FoodModifier.java:116)
	at squeek.spiceoflife.foodtracker.FoodModifier.getFoodValues(FoodModifier.java:34)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_448_FoodModifier_getFoodValues_GetPlayerFoodValues.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.getFoodValuesForPlayer(AppleCoreAccessorMutatorImpl.java:95)
	at squeek.applecore.api.food.FoodValues.get(FoodValues.java:64)
	at squeek.applecore.client.TooltipOverlayHandler.onRenderTick(TooltipOverlayHandler.java:141)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_309_TooltipOverlayHandler_onRenderTick_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1003)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.math.BigDecimal.divide(BigDecimal.java:1741)
	at com.udojava.evalex.Expression$5.eval(Expression.java:768)
	at com.udojava.evalex.Expression$41.eval(Expression.java:1232)
	at com.udojava.evalex.Expression$41.eval(Expression.java:1232)
	at com.udojava.evalex.Expression$41.eval(Expression.java:1232)
	at com.udojava.evalex.Expression$41.eval(Expression.java:1232)
	at com.udojava.evalex.Expression$41.eval(Expression.java:1232)
	at com.udojava.evalex.Expression$Function.lazyEval(Expression.java:519)
	at com.udojava.evalex.Expression.eval(Expression.java:1254)
	at squeek.spiceoflife.foodtracker.FoodModifier.getFoodGroupModifier(FoodModifier.java:109)
	at squeek.spiceoflife.foodtracker.FoodModifier.getFoodModifier(FoodModifier.java:140)
	at squeek.spiceoflife.foodtracker.FoodModifier.getFoodModifier(FoodModifier.java:116)
	at squeek.spiceoflife.foodtracker.FoodModifier.getFoodValues(FoodModifier.java:34)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_448_FoodModifier_getFoodValues_GetPlayerFoodValues.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.getFoodValuesForPlayer(AppleCoreAccessorMutatorImpl.java:95)
	at squeek.applecore.api.food.FoodValues.get(FoodValues.java:64)
	at squeek.applecore.client.TooltipOverlayHandler.onRenderTick(TooltipOverlayHandler.java:141)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_309_TooltipOverlayHandler_onRenderTick_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Wingyl'/6491, l='MpServer', x=-182.34, y=46.62, z=355.35]]
	Chunk stats: MultiplayerChunkCache: 462, 471
	Level seed: 0
	Level generator: ID 04 - biosphere, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-234,64,356), Chunk: (at 6,4,4 in -15,22; contains blocks -240,0,352 to -225,255,367), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 520009 game time, 520009 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 29 total; [EntityClientPlayerMP['Wingyl'/6491, l='MpServer', x=-182.34, y=46.62, z=355.35], EntityBat['Bat'/6531, l='MpServer', x=-149.25, y=62.10, z=400.75], EntityBat['Bat'/6469, l='MpServer', x=-148.63, y=51.00, z=369.09], EntityBat['Bat'/6470, l='MpServer', x=-174.56, y=53.87, z=373.69], EntityChicken['Chicken'/6471, l='MpServer', x=-182.53, y=50.00, z=405.63], EntityBat['Bat'/6472, l='MpServer', x=-178.47, y=54.14, z=414.88], EntityBat['Bat'/6473, l='MpServer', x=-140.25, y=50.58, z=300.09], EntityBat['Bat'/8714, l='MpServer', x=-188.59, y=52.27, z=399.66], EntityBat['Bat'/6475, l='MpServer', x=-128.63, y=52.77, z=353.59], EntityBat['Bat'/6482, l='MpServer', x=-121.47, y=55.10, z=366.75], EntityBat['Bat'/6483, l='MpServer', x=-123.00, y=46.05, z=310.91], EntityBat['Bat'/6484, l='MpServer', x=-109.63, y=55.55, z=370.78], EntityBat['Bat'/6485, l='MpServer', x=-113.91, y=50.20, z=392.66], EntityBat['Bat'/6441, l='MpServer', x=-174.78, y=56.87, z=346.53], EntityChicken['Chicken'/6443, l='MpServer', x=-192.59, y=46.00, z=359.47], EntityItem['item.item.feather'/6444, l='MpServer', x=-196.13, y=46.13, z=361.72], EntityChicken['Chicken'/6445, l='MpServer', x=-194.38, y=46.00, z=361.47], EntityBat['Bat'/6446, l='MpServer', x=-150.28, y=52.56, z=360.50], EntityItem['item.item.egg'/6448, l='MpServer', x=-191.22, y=46.13, z=361.75], EntityBat['Bat'/6576, l='MpServer', x=-155.75, y=49.57, z=365.59], EntityItem['item.item.egg'/6449, l='MpServer', x=-188.13, y=46.13, z=359.78], EntityBat['Bat'/6577, l='MpServer', x=-199.41, y=48.02, z=350.97], EntityChicken['Chicken'/6450, l='MpServer', x=-188.53, y=46.00, z=359.88], EntityChicken['Chicken'/6451, l='MpServer', x=-189.16, y=46.00, z=359.41], EntityChicken['Chicken'/6452, l='MpServer', x=-189.09, y=46.00, z=361.81], EntityItem['item.item.feather'/6453, l='MpServer', x=-189.66, y=46.13, z=361.88], EntityChicken['Chicken'/6454, l='MpServer', x=-188.16, y=46.00, z=359.16], EntityBat['Bat'/6455, l='MpServer', x=-135.13, y=59.21, z=377.41], EntityManaBurst['Mana Burst'/9278, l='MpServer', x=-167.03, y=47.55, z=358.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 227747104 bytes (217 MB) / 781463552 bytes (745 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_D1 65 mods loaded, 65 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAA	CodeChickenCore{1.0.7.45} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal.jar) 
	UCHIJAAAAAAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAAAAAAA	BinniePatcher{1.8.2} [Binnie Patcher] (minecraft.jar) 
	UCHIJAAAAAAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAAAAAAA	AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-1.7.10-1.5.0.jar) 
	UCHIJAAAAAAAAA	AppleCore{1.3.2} [AppleCore] (AppleCore-mc1.7.10-1.3.2.jar) 
	UCHIJAAAAAAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAAAAAAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAAAAAAA	ThermalFoundation{1.7.10R1.2.4} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.4-114.jar) 
	UCHIJAAAAAAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAAAAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAAAAAAA	ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.2-240.jar) 
	UCHIJAAAAAAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAAAAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAAAAAAA	Armory{1.1.0.1-256} [Armory] (Armory-1.1.0.1-256.jar) 
	UCHIJAAAAAAAAA	Armory-Weaponry{@VERSION@} [Armory-Weaponry] (Armory-Weaponry-1.0.0-20.jar) 
	UCHIJAAAAAAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJAAAAAAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1521-universal.jar) 
	UCHIJAAAAAAAAA	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCHIJAAAAAAAAA	Forestry{4.2.12.60} [Forestry for Minecraft] (forestry_1.7.10-4.2.12.60.jar) 
	UCHIJAAAAAAAAA	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UCHIJAAAAAAAAA	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) 
	UCHIJAAAAAAAAA	B0bGrowsOre{2.5.4} [B0bGary's Growable Ores] (B0bGary's Growable Ores-2.5.4 for 1.7.10.jar) 
	UCHIJAAAAAAAAA	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCHIJAAAAAAAAA	BinnieCore{2.0-pre13} [Binnie Core] (binnie-mods-2.0-pre13.jar) 
	UCHIJAAAAAAAAA	Botany{2.0-pre13} [Botany] (binnie-mods-2.0-pre13.jar) 
	UCHIJAAAAAAAAA	ExtraBees{2.0-pre13} [Extra Bees] (binnie-mods-2.0-pre13.jar) 
	UCHIJAAAAAAAAA	ExtraTrees{2.0-pre13} [Extra Trees] (binnie-mods-2.0-pre13.jar) 
	UCHIJAAAAAAAAA	Genetics{2.0-pre13} [Genetics] (binnie-mods-2.0-pre13.jar) 
	UCHIJAAAAAAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJAAAAAAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAAAAAAA	cookingbook{1.0.140} [Cooking for Blockheads] (cookingbook-mc1.7.10-1.0.140.jar) 
	UCHIJAAAAAAAAA	exnihilo{1.38-51} [Ex Nihilo] (Ex-Nihilo-1.38-51.jar) 
	UCHIJAAAAAAAAA	exastrisrebirth{MC1.7.10-1.01-45} [Ex Astris Rebirth] (Ex-Astris-Rebirth-MC1.7.10-1.01-45.jar) 
	UCHIJAAAAAAAAA	golems{1.20} [Extra Golems] (Extra-Golems[1.7.10]-1.20.jar) 
	UCHIJAAAAAAAAA	golems_addon_tconstruct{1.08} [Tinkers' Golems Addon] (ExtraGolemsTinkersAddon[1.7.10]-1.08.jar) 
	UCHIJAAAAAAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHIJAAAAAAAAA	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UCHIJAAAAAAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAAAAAAA	gendustry{1.6.2.127} [GenDustry] (gendustry-1.6.2.127-mc1.7.10.jar) 
	UCHIJAAAAAAAAA	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
	UCHIJAAAAAAAAA	journeymap{5.1.1} [JourneyMap] (journeymap-1.7.10-5.1.1-unlimited.jar) 
	UCHIJAAAAAAAAA	movillages{1.2.1} [Mo' Villages] (MoVillages-1.3.1.jar) 
	UCHIJAAAAAAAAA	Mystcraft{0.11.6.02} [Mystcraft] (mystcraft-1.7.10-0.11.6.02.jar) 
	UCHIJAAAAAAAAA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJAAAAAAAAA	New Biospheres Mod{0.85} [New Biospheres Mod] (NewBiospheresMod-Experimental-2015-04-16.jar) 
	UCHIJAAAAAAAAA	qCraft{1.2} [qCraft] (qCraft-1.2-1.7.10.jar) 
	UCHIJAAAAAAAAA	SpiceOfLife{1.3.7} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.3.7.jar) 
	UCHIJAAAAAAAAA	squidless{0.6.1} [Squidless] (squidless-1.7.10-0.6.1.jar) 
	UCHIJAAAAAAAAA	alfheimwings{30} [The Wings of Alfheim] (The Wings of Alfheim-1.7.10-30.jar) 
	UCHIJAAAAAAAAA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCHIJAAAAAAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAAAAAAA	wawla{1.3.3} [What Are We Looking At] (Wawla-1.3.3-1.7.10.jar) 
	UCHIJAAAAAAAAA	NEIAddons{1.12.13.38} [NEI Addons] (neiaddons-1.12.13.38-mc1.7.10.zip) 
	UCHIJAAAAAAAAA	NEIAddons|Developer{1.12.13.38} [NEI Addons: Developer Tools] (neiaddons-1.12.13.38-mc1.7.10.zip) 
	UCHIJAAAAAAAAA	NEIAddons|AppEng{1.12.13.38} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.13.38-mc1.7.10.zip) 
	UCHIJAAAAAAAAA	NEIAddons|Botany{1.12.13.38} [NEI Addons: Botany] (neiaddons-1.12.13.38-mc1.7.10.zip) 
	UCHIJAAAAAAAAA	NEIAddons|Forestry{1.12.13.38} [NEI Addons: Forestry] (neiaddons-1.12.13.38-mc1.7.10.zip) 
	UCHIJAAAAAAAAA	NEIAddons|CraftingTables{1.12.13.38} [NEI Addons: Crafting Tables] (neiaddons-1.12.13.38-mc1.7.10.zip) 
	UCHIJAAAAAAAAA	NEIAddons|ExNihilo{1.12.13.38} [NEI Addons: Ex Nihilo] (neiaddons-1.12.13.38-mc1.7.10.zip) 
	UCHIJAAAAAAAAA	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.14008 Compatibility Profile Context 21.19.137.1' Renderer: 'AMD Radeon(TM) R5 Graphics'
	CoFHCore: -[1.7.10]3.1.2-325
	ThermalFoundation: -[1.7.10]1.2.4-114
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	ThermalExpansion: -[1.7.10]4.1.2-240
	TConstruct Environment: Environment healthy.
	List of loaded APIs: 
		* AgriCraftAPI (1.0) from AgriCraft-1.7.10-1.5.0.jar
		* AppleCoreAPI (1.2.0) from AppleCore-mc1.7.10-1.3.2.jar
		* Armory-API|Armor (1.0.0.0-256) from Armory-1.1.0.1-256.jar
		* Armory-API|core (1.0.0.0-256) from Armory-1.1.0.1-256.jar
		* Armory-API|Crafting (1.0.0.0-256) from Armory-1.1.0.1-256.jar
		* Armory-API|Crafting|SmithingsAnvil (1.0.0.0-256) from Armory-1.1.0.1-256.jar
		* Armory-API|Crafting|SmithingsAnvil|Components (1.0.0.0-256) from Armory-1.1.0.1-256.jar
		* Armory-API|Crafting|SmithingsAnvil|Recipe (1.0.0.0-256) from Armory-1.1.0.1-256.jar
		* Armory-API|Events (1.0.0.0-256) from Armory-1.1.0.1-256.jar
		* Armory-API|Events|Client (1.0.0.0-256) from Armory-1.1.0.1-256.jar
		* Armory-API|Events|Common (1.0.0.0-256) from Armory-1.1.0.1-256.jar
		* Armory-API|Item (1.0.0.0-256) from Armory-1.1.0.1-256.jar
		* Armory-API|Materials (1.0.0.0-256) from Armory-1.1.0.1-256.jar
		* Armory-API|Registries (1.0.0.0-256) from Armory-1.1.0.1-256.jar
		* Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
		* BiomesOPlentyAPI (1.0.0) from BiomesOPlenty-1.7.10-2.1.0.1521-universal.jar
		* BloodMagicAPI (1.3.3-13) from BloodMagic-1.7.10-1.3.3-17.jar
		* BotaniaAPI (76) from Botania r1.8-249.jar
		* BuildCraftAPI|core (1.0) from extrautilities-1.2.12.jar
		* BuildCraftAPI|tools (1.0) from extrautilities-1.2.12.jar
		* ChiselAPI (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Carving (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Rendering (0.1.1) from Chisel-2.9.5.11.jar
		* CoFHAPI (1.7.10R1.0.13B1) from extrautilities-1.2.12.jar
		* CoFHAPI|block (1.7.10R1.0.13B1) from extrautilities-1.2.12.jar
		* CoFHAPI|core (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|energy (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|fluid (1.7.10R1.0.12) from Ex-Astris-Rebirth-MC1.7.10-1.01-45.jar
		* CoFHAPI|inventory (1.7.10R1.0.12) from Ex-Astris-Rebirth-MC1.7.10-1.01-45.jar
		* CoFHAPI|item (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.12) from Ex-Astris-Rebirth-MC1.7.10-1.01-45.jar
		* CoFHAPI|tileentity (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|transport (1.7.10R1.0.12) from Ex-Astris-Rebirth-MC1.7.10-1.01-45.jar
		* CoFHAPI|world (1.7.10R1.0.12) from Ex-Astris-Rebirth-MC1.7.10-1.01-45.jar
		* CoFHLib (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|audio (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|gui (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|gui|container (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|gui|element (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|gui|slot (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|inventory (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|render (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|render|particle (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|util (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|util|helpers (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|util|position (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|world (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|world|feature (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* ForestryAPI|apiculture (4.8.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|core (5.0.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|world (2.1.0) from forestry_1.7.10-4.2.12.60.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.2.127-mc1.7.10.jar
		* Guide-API|API (1.7.10-1.0.1-20) from Guide-API-1.7.10-1.0.1-20.jar
		* MetallurgyAPI (2.0.0) from Metallurgy-1.7.10-4.0.6.80.jar
		* Mystcraft|API (0.1) from mystcraft-1.7.10-0.11.6.02.jar
		* Thaumcraft|API (4.2.2.0) from Pam's HarvestCraft 1.7.10Lb.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon(TM) R5 Graphics GL version 4.5.14008 Compatibility Profile Context 21.19.137.1, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Phoneix Wings]
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_D1
	Render Distance Chunks: 12
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.5.14008 Compatibility Profile Context 21.19.137.1
	OpenGlRenderer: AMD Radeon(TM) R5 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by BlayTheNinth** [comment]
This looks like an issue on Spice of Life's side to me, please report it [over there](https://github.com/squeek502/SpiceOfLife/issues) and link to this issue.

There's nothing special about the items in the cooking book, so I'm not sure why they're suddenly having problems. It used to work just fine in the past.

**Comment by squeek502** [comment]
This can be closed, it's a TSoL issue (the formula they're using is not protecting against division by zero).
