### ISSUE TITLE
Sink doesn't follow forge specifications (Can cause crashes)

### ISSUE THREAD

**Issue by Da-Technomancer** [blay09/CookingForBlockheads#187]
The specific mistake occurs on line 37 of the TileSink class. Specifically, from the description on the Forge fill method "@return Amount of resource that was (or would have been, if simulated) filled.". In the sink, however, you are returning the amount of fluid that WASN'T filled, when you should be returning 0. This has caused a crash when combined with a few other mods (ex. https://github.com/Da-Technomancer/Crossroads/issues/55).

**Comment by BlayTheNinth** [comment]
Wait, this is intended. How does it cause crashes? The sink is supposed to simply eat up any liquid you give it, it doesn't have an "internal tank" by default as it's an infinite water source.

**Comment by Da-Technomancer** [comment]
Sorry, I thought the sink was supposed to only provide water, not be willing to accept it. This causing a crash was actually something on my end due to the edge case of something able to provide AND accept infinite amounts of a liquid (something I assumed would be a bug). I've fixed it on my end anyways.
