### ISSUE TITLE
[SF3] Doors not closing?

### ISSUE THREAD

**Issue by Lethann** [blay09/CookingForBlockheads#191]
I've frequently had the doors to the counters and fridge get 'stuck' in the open position until I broke it and replaced it. Frequently happened when I tried to 'float' some counters in the air as cabinets. (Had to take them down anyway since they were not registering their inventories).

**Comment by BlayTheNinth** [comment]
Did you shift-right click them maybe? Shift-right-clicking the doors will open/close the door without someone actually accessing the block.
