### ISSUE TITLE
[Suggestion] Option to show all recipes in cooking table

### ISSUE THREAD

**Issue by Lethann** [blay09/CookingForBlockheads#193]
Really love this mod! However I'd like the ability to see all recipes even if I don't have the materials because some recipes simply take other craftable items like mayo, oil, the tofu meats, etc. Or maybe just all 'uncraftable' recipes. Some recipes take raw meats, others require cooked, some are tiered like the burgers.

**Comment by BlayTheNinth** [comment]
Try right-clicking a cooking table with a #NoFilter Edition, the table will then act as a #NoFilter edition and should still be able to craft items.

**Comment by Lethann** [comment]
Ah! Another one I didn't know. Thanks!!
