### ISSUE TITLE
Request: allow Inventory Sorter to work?

### ISSUE THREAD

**Issue by Lethann** [blay09/CookingForBlockheads#195]
Not sure which mod to post this to so I'm posting to both.

The mod [Simple Inventory Sorter](https://github.com/cpw/inventorysorter) sorts the items in an inventory like chests and the player. However it doesn't work on the CFB stuff. Would be really nice because I mass farm and am trying to only keep one stack of food in the kitchen at a time to save space.

**Comment by BoboSims** [comment]
Similarly, I would also like compatibility with [InvTweaks,](https://minecraft.curseforge.com/projects/inventory-tweaks) which offers several improvements like - for example - CTRL-SHIFT-clicking to transport all stacks of a certain ingredient into or out of the fridge/counter, as well as scrolling the wheel on any stack to move one item between inventories.

**Comment by BlayTheNinth** [comment]
Not sure why Inventory Sorter doesn't like my stuff, there doesn't appear to be an API for it either. It seems to be stuck on 1.10 at the moment, so I'm closing this for now and can take another look once it updates to modern versions.

Inventory Tweaks should already be supported - if it's not working as expected, please open a separate issue detailing what part is broken.
