### ISSUE TITLE
Incompatibility with CraftTweaker

### ISSUE THREAD

**Issue by Gunner76th** [blay09/CookingForBlockheads#200]
When running the most recent release of both CraftTweaker and CookingForBlockheads, CFB causes CT to crash out and shut down the server. 
[fml-server-latest.log.txt](https://github.com/blay09/CookingForBlockheads/files/823274/fml-server-latest.log.txt)

When I disabled CFB, my server starts up with no issue.

**Comment by Gunner76th** [comment]
Please see this issue ticket as well for additional information https://github.com/jaredlll08/CraftTweaker/issues/170

**Comment by BlayTheNinth** [comment]
Looks like the problem lies with a furnace recipe that results in nothing. Cooking for Blockheads doesn't error-check in that case yet.

**Comment by BlayTheNinth** [comment]
Specifically it seems to be some Refined Storage furnace recipes in your scripts (see minetweaker.log):

```
ERROR: Furnace.zs:16: Could not resolve <refinedstorage : quartz_enriched_iron>
ERROR: Furnace.zs:40: Could not resolve <refinedstorage : processor : 1>
ERROR: Furnace.zs:41: Could not resolve <refinedstorage : processor : 2>
ERROR: Furnace.zs:42: Could not resolve <refinedstorage : processor>
ERROR: Furnace.zs:43: Could not resolve <refinedstorage : processor : 6>
```
