### ISSUE TITLE
[1.11.2] Shift click remove tool from rack with another tool in hand voids held tool.

### ISSUE THREAD

**Issue by MrNinja93** [blay09/CookingForBlockheads#203]
Shift clicking to remove a tool from the tool rack whilst holding another tool will void the held tool from inventory. 

Tested with Just Cooking for blockheads and Pam's harvestcraft for the tools.

Forge:13.20.0.2252
Cooking For Blockheads: 5.2.8
Pam's: 1.11.2f

**Comment by BlayTheNinth** [comment]
Shift-clicking with a tool in hand doesn't interact with the tool rack at all. Tools are removed using simple right-click, and it's not voiding the held item for me. It puts the removed tool into the first available slot into the hotbar, maybe it's there and just wasn't put directly into your hand?

**Comment by MrNinja93** [comment]
Shift + Right click. Simple right click works as intended and swaps items. 
(Also happens in just a forge/CFB instance with vanilla tools)  

Gif for illustration:
http://imgur.com/j4YfsHH
