### ISSUE TITLE
Hatch of Oven Doesn't Shown

### ISSUE THREAD

**Issue by ghost** [blay09/CookingForBlockheads#204]
![oven](https://cloud.githubusercontent.com/assets/24831406/24070203/323bba36-0bc1-11e7-80a6-8d5df19a3040.PNG)
there was a hatch on oven and if i right click it it was opening, it was pretty. did you guys delete it?
it's minecraft 1.11.2 and forge 2259
and i tried in gamemode, placed many ovens on world but didn't work
oven is working.

**Comment by BlayTheNinth** [comment]
Do you have any mods messing with rendering installed?

**Comment by ghost** [comment]
i'm not sure but i have a few mods :D how can i know which mod causes? thanks.
but i think this happened after the latest version of cooking for blockheads 
but it works fine with vanilla, i know this.

**Comment by BlayTheNinth** [comment]
OptiFine or other FPS enhancing mods would probably be the cause, do you have any of those installed?

**Comment by ghost** [comment]
ah yes i installed optifine, but it was working fine with optifine.
and same with the betterfps mod. let me try without installing them, wait me. thanks.

**Comment by BlayTheNinth** [comment]
Actually I have another suspicion, are you playing on Fast graphics options? Didn't take that into account when making the doors render so that might be the issue...

**Comment by ghost** [comment]
no i'm playing on fancy

**Comment by ghost** [comment]
you can try my modpack to inspect the issue maybe if you want. it's [magenji](https://www.technicpack.net/modpack/magenji.968153) in technic launcher. you can try =)

**Comment by ghost** [comment]
bump: i deleted optifine and betterfps, problem happens already.

**Comment by ghost** [comment]
and i wanna ask something, there are some slots on oven (like skillet, or saucepan) but there are no any items like that. is it a bug? i really wonder. i just watched [this video ](https://www.youtube.com/watch?v=Zk0PYvolaOg) and see there are. and i already installed mrcrayfish's furniture mod.

**Comment by BlayTheNinth** [comment]
The tool items are from Pam's Harvestcraft, they're not necessary if you don't have Pam's Harvestcraft installed.

**Comment by ghost** [comment]
oh... i can't install harvestcraft because it crashes, uncompatible with my modpack... so it has no sense without harvestcraft? if yes, i should delete CFBH... thanks..

**Comment by BlayTheNinth** [comment]
Cooking for Blockheads supports other food mods as well. If you have no food mods at all installed, then there's not much purpose to it other than decorational use.

**Comment by ghost** [comment]
hmm, okay blay. thank you. and i'm waiting you to fix the waystones mods bugs :D get luck with your work! see ya
