### ISSUE TITLE
Fridge / Toaster / Oven make cave ambiance sounds when used

### ISSUE THREAD

**Issue by SableDrake** [blay09/CookingForBlockheads#208]
see title, version 1.11.2-5.3.13

**Comment by BlayTheNinth** [comment]
Works fine for me. Can you reproduce this issue without any other mods installed?

**Comment by SableDrake** [comment]
No I cannot, turns out I cannot reproduce the problem in singeplayer at all, with or without other mods. Unfortunately I cannot test it on the server without any other mods. But it seems to be a MP issue I guess.
