### ISSUE TITLE
rendering issue with oven

### ISSUE THREAD

**Issue by TheDarkPreacher** [blay09/CookingForBlockheads#209]
leaving the chunk and reloading it causes all sorts of rendering issues after placing down the oven. missing chisels and bit blocks, Platforms mod platforms either rendering wrong or not rendering, and the counters from CFB lose their coloring after dye is applied. Also, the following paste is from a crash I just had : https://pastebin.com/bE1qeXjx

**Comment by IchigoGames** [comment]
i am also having this same crash on my server https://pastebin.com/3rwakeuC

minecraft 1.11.2
forge 2260
CookingForBlockheads_1.11.2-5.3.13
