### ISSUE TITLE
[1.11.2 - 5.3.13] Manually inserting items into an open oven voids held item.

### ISSUE THREAD

**Issue by GeekBeam** [blay09/CookingForBlockheads#212]
when opening the oven's front face (via shift right click) one is able to insert ANY item into the oven. but since the oven doesn't accept any item except food items, if I attempt to insert cobble, it is immediately voided from my hand, this is valid for ANY other non smeltable.

**Comment by BlayTheNinth** [comment]
Are you sure it was voided and didn't end up in the fuel slot? That's where it went for me.

**Comment by GeekBeam** [comment]
Attempting to insert a modular storage tablet from RFTools voided the tablet, so mayhaps it has to do with NBT data attached to the item?

**Comment by BlayTheNinth** [comment]
That shouldn't make a difference. Either way, new version only allows coal to be inserted into the fuel slot so it shouldn't happen anymore.
