### ISSUE TITLE
[1.10.2-4.2.39] What Kitchen Floor?

### ISSUE THREAD

**Issue by BoboSims** [blay09/CookingForBlockheads#214]
The wiki tells us of a Kitchen Floor that can connect all kitchen blocks to each other. But the version that I have (CookingForBlockheads_1.10.2-4.2.39) does not contain any such block. Did I miss something?

The Kitchen Corner is missing as well, by the way.

**Comment by BlayTheNinth** [comment]
The wiki targets the latest version on Minecraft 1.11.2.

**Comment by BoboSims** [comment]
Thank you for your super fast response. Someone could have mentioned that certain blocks aren't present in other versions.
But the real issue now becomes: how am I supposed to work around a corner, or connect distant kitchen blocks now? Is there a chance of a back-porting of these objects? Or, if there isn't: could you possibly be persuaded to take a request for it under advisement?

I would be very much obliged! :)

**Comment by BlayTheNinth** [comment]
Backporting is unlikely since I only have a limited amount of time to spend on my mods, and I'd rather spend that time fixing bugs and adding new content rather than supporting versions that are almost a year old already. I'd rather everyone would try and look into updating to 1.11.2.

**Comment by BoboSims** [comment]
Sure, I understand that. But for THAT to happen, a lot more mods should be updated to support 1.11.2 first. Heck, a lot of mods haven't even been fully updated to 1.10.2, yet. So the majority is holding back on that. Can you blame them? Not me, cuz I'm one of them. :)

Besides, what's wrong with a game version being a year old? The last expansion for The Sims 2 is NINE years old, and millions of people are still playing that, too... :)

Anyway, you're not back porting, so I'll accept that, reluctantly...

**Comment by BlayTheNinth** [comment]
Mods that still aren't on 1.10.2 are either dead or have made a conscious decision to stay on old versions forever (cutting them off from the rest of the ecosystem). The ones that are still on 1.10.2 only just haven't made updating a priority.

I don't blame them (other than the fact that I constantly get asked by people to backport stuff and basically do my work twice), but I also don't support their decision and so I won't make any efforts to make it easier for them to stay behind. 

I follow a simple "old versions get bugfixes only" approach, which is very common and also what Minecraft Forge does. 

If it wasn't for pioneer mods venturing into newer versions, the big packs would have even more reason to stay behind and we might have still been stuck on Minecraft 1.7.10 today. Some of these pioneer mods have the time and motivation to actively support multiple versions at once - I don't. And I don't see a need as long as we're talking new features. My mod may not be entirely useful to you in that state, but it's the (only) state that was available back in Minecraft 1.10.2, and it worked well enough for people before they found out it had been improved in the future.

**Comment by BattleNachos** [comment]
Lack of multiblock functionality of the kitchen leaves a big hole in Forever Stranded imo.  Not your fault for sure, but damn it would be nice 😃 

edit
Using 1.10.2-4.2.43

edit 2
oh it does, it just doesn't have the connected visual my bad

**Comment by Scratchman** [comment]
So, you're saying thaumcraft is a dead mod? Odd.
