### ISSUE TITLE
Dupe bug involving Survivalist

### ISSUE THREAD

**Issue by purpleposeidon** [blay09/CookingForBlockheads#215]
Putting a vanilla tool on a toolrack triggers a PlayerDestroyItemEvent that causes Survivalist to do a 'recovery' of the materials that made the tool, eg diamonds from a diamond pickaxe. However, the tool does not break.

https://github.com/gigaherz/Survivalist/issues/43

**Comment by BlayTheNinth** [comment]
Issue should be fixed in the [newest Cooking for Blockheads](http://jenkins.blay09.net/job/Cooking%20for%20Blockheads%201.10/lastSuccessfulBuild/) version.
