### ISSUE TITLE
Suggestion:  Connected Blocks

### ISSUE THREAD

**Issue by AnthonyKane5528X** [blay09/CookingForBlockheads#220]
I don't know how hard this would be to implement but my suggestion would be to have the blocks connect.  I know they form a "multi block", but one of the things that I don't like (aesthetically) is that each block (The Counter, the Sink, The Cabinet) are all their own individual blocks.  Nothing connects to form one smooth, large counter top, or one large cabinet.  So rather than have a coherent "Kitchen" I have a bunch of little "station blocks".  Also the blocks do not visually fill the full blocks space, but instead leave small gaps.  They are technically full blocks, as they're bounding boxes show, but they don't look it.   

So my suggestion would be to see if you could make it so that these blocks could have "connected textures".  That way we can make long counter tops, double cabinets and have it all connect up with the Kitchen table and sink.

**Comment by BlayTheNinth** [comment]
![](https://media-elerium.cursecdn.com/attachments/198/317/2017-03-16_15.png)
It's already a thing in 1.11.2+ (and will not be backported).

**Comment by AnthonyKane5528X** [comment]
Well this is cool.  Thanks for the information.  :)
-hopefully we'll see it in 1.12 as well.

P.S.
(I never asked for it to be backported btw)
