### ISSUE TITLE
Suggestion:  Range Top and Wall Mounted Oven

### ISSUE THREAD

**Issue by AnthonyKane5528X** [blay09/CookingForBlockheads#221]
Here's an idea for future updates (1.11 and forward).

I know the game already has the oven.  Which is awesome.  Perhaps you might be able to offer a "Range Top" which would be a stove, build into the counter itself, and a stand alone oven that could be placed in the wall.  They would be separate blocks but offer the player a choice of either an "All in one unit" with the original stove, or they could opt to install them as separate pieces.

I know it would mean adding two more items to the mod, that split the function of one block, but it would provide players more choice when customizing their "Kitchen".

**Comment by bookerthegeek** [comment]
Setting up the range to require power, or fuel such as modded oils would be cool with this to.

**Comment by BlayTheNinth** [comment]
With the planned addition of the Electric Oven (https://github.com/blay09/CookingForBlockheads/issues/108) and Gas Oven (https://github.com/blay09/CookingForBlockheads/issues/275) we'd end up with five oven blocks, which I feel is too many and would start overwhelming users. Not too mention it'd be weird if the new styles don't also have gas and electric versions, resulting in a total of nine ovens... 

Sorry, I don't think this'll happen.
