### ISSUE TITLE
Suggestion: Oven & VanillaFoodPantry Bit O' Heat

### ISSUE THREAD

**Issue by nephatrine** [blay09/CookingForBlockheads#223]
It would be nice if the Oven provided a source of Bits O Heat for VanillaFoodPantry in the same way the sink provides a water source. If that's not possible, could you support the normal Bits O Heat recipes from the cooking table? I'm assuming they don't show up because it's not "food" itself, but since it's used pretty much exclusively to cook food it'd be really handy.

**Comment by BlayTheNinth** [comment]
Bits O Heat should now appear in the list on the latest 1.11.2 version.
