### ISSUE TITLE
Upgraded Cabinets and Fridges

### ISSUE THREAD

**Issue by Thiana** [blay09/CookingForBlockheads#238]
Could you please consider adding a method for denser storage? With HC alone you either end up with absurdly large kitchens full of fridges and/or cabinets or you have to keep swapping the contents of those blocks out for meal variety.

Possible options:
* Upgraded blocks. ie, iron chests mod
* Config option to set block slots (ie 27 => 54)
* External storage 'adapter'. ie, connect to RS/AE2/SD/EU/XU

Thanks :)

**Comment by Lethann** [comment]
Possibly compatibility with Storage Drawers maybe as well? That's so handy for figuring out what I'm low on. Maybe an 'upgrade' to add to the drawer to let it be registered by the multiblock as long as it's touching?

**Comment by Saklad5** [comment]
Refined Storage Interfaces expose all items on the network, so all you’d need to do is add a way to connect to other blocks. No special code needed.

That being said, it’d be great if Refined Storage could expose all the recipes as auto-crafting patterns by being connected.

**Comment by BlayTheNinth** [comment]
Storage Drawers compatibility is coming in the next version most likely: https://github.com/blay09/CookingForBlockheads/pull/272

As for an upgraded fridge, I think I will be adding a freezer block that holds a double chest worth in one block: https://github.com/blay09/CookingForBlockheads/issues/229

Refined Storage support isn't as easy as it seems - there's potential issues of huge networks slowing down the cooking table and problems like having two interfaces of the same network attached, that would need to be solved first.

I don't think I'll be adding upgraded cabinets. I want to instead add some specialized storage blocks like the Fruit Basket (https://github.com/blay09/CookingForBlockheads/issues/276) which should help.

**Comment by Saklad5** [comment]
Or to put it another way, Refined Storage support would be easy, but optimizing it to be actually usable is a whole other story.

I would think the same issues apply with Storage Drawers, though. Can’t you have multiple Drawer Controllers attached?

**Comment by BlayTheNinth** [comment]
That's why in the Storage Drawers support only the actual drawers can be connected, no controllers. Controllers had an additional problem in that they apparently cached available items for five seconds, causing inaccurate data to be shown.

**Comment by Saklad5** [comment]
A lot of people are going to open bug reports saying Storage Drawers integration doesn’t work, I imagine.

**Comment by BlayTheNinth** [comment]
Doubt it, there's nothing to indicate it's supposed to work to begin with. Only people who read changelogs or experiment will find the cooking table now detects drawer content.

**Comment by Saklad5** [comment]
Make sure to specify that Controllers don’t work in the changelog, then.

**Comment by Thiana** [comment]
Thank you :)

**Comment by BlayTheNinth** [comment]
The new version also contains an option to double the space of the kitchen counters.
