### ISSUE TITLE
Tool Rack

### ISSUE THREAD

**Issue by washinoboku** [blay09/CookingForBlockheads#239]
On SkyFactory v3.0.14 they update your mod from 4.2.43 to 4.2.45 and now the tool rack is not recognized in the multiblock or even having proper items in inventory, The sink doesn't work as water source in the multiblock and the cow in a jar either. Fridge, oven, table, and counters work perfect,

**Comment by BlayTheNinth** [comment]
Is Pam's Harvestcraft also up to date?

**Comment by washinoboku** [comment]
They not update Pam's to the last version in that modpack release. I did it manually and works perfect. My mistake for not checking basic information. Thank you for helping me.
