### ISSUE TITLE
Help needed with IMC support

### ISSUE THREAD

**Issue by Sixdd6** [blay09/CookingForBlockheads#241]
I'm trying to use the RegisterOvenRecipe imc but I've been at it for hours now and I can't seem to get the correct values in for ItemStack, how is this supposed to be formatted/could I get an example?

**Comment by BlayTheNinth** [comment]
Send an IMC message with id `RegisterOvenRecipe` to `cookingforblockheads`, the message being of type `NBTTagCompound`.

Inside the NBT, there should be another compound `Input` and one `Output`. Those are used to create ItemStacks, meaning they must be in the ItemStack format `ItemStack.writeToNBT(...)`

In JSON it would look something like
```json
{
    "Input": {
        "id": "minecraft:raw_fish",
        "Count": 1,
        "Damage": 0
    },
    "Output": {
        "id": "minecraft:cooked_fish",
        "Count": 1,
        "Damage": 0
    }
}```

**Comment by Sixdd6** [comment]
Thank you for the response, works a treat 😄
