### ISSUE TITLE
Rustic and lycan compatability?  1.12.2

### ISSUE THREAD

**Issue by Sayonarakansas** [blay09/CookingForBlockheads#242]
im unable to add olive oil to a food item using your multiblock structure. 
lycanites recipes arent supported in the multiblock

**Comment by BlayTheNinth** [comment]
Olive Oil can be added to every food item in existence, supporting it would severely bloat the recipe book as many of the ingredients used for further cooking can also be eaten by themselves (and therefore, each of them would get an olive oiled entry).

Lycanites recipes seem to work just fine, just the ones that aren't actually edible can't be made in the Cooking Table as it only focuses on edible food and its ingredients.
