### ISSUE TITLE
Request: Compatibility between Cow in a jar and EnderIO Conduits

### ISSUE THREAD

**Issue by RepoDraghon** [blay09/CookingForBlockheads#243]
They suggested to put this request over on your end rather on theirs.

I'd like you to add compatibility for the EnderIO conduits so I can use the ENDERIO Drums to store more milk from the Cow in a Jar then later use it.

Current version used 1.10.2 but I'd like it through all versions

**Comment by BlayTheNinth** [comment]
This is dealt with by #231 (for upcoming Minecraft 1.12 update)
