### ISSUE TITLE
Outside kitchen corner block

### ISSUE THREAD

**Issue by gchpaco** [blay09/CookingForBlockheads#244]
We have the new-ish kitchen corner block, which is superb for inside corners; thank you!

I occasionally have cause to build with an interior that is concave; for example, in my recent playthrough I'm in an ice biome and my main storage area is an igloo.  It would be really nice to have an outside corner block so that I could (in principle) run kitchen counters all the way around.  You can see where I've improvised using a normal cabinet block near the cow in a jar.

![2017-10-22_03 43 30](https://user-images.githubusercontent.com/17789/31860414-51a81dd2-b6df-11e7-8dbe-f25c8c075b55.png)

**Comment by BlayTheNinth** [comment]
I think instead of adding a separate block, it should reuse the Kitchen Corner block and have them render in a similar manner as stairs do.
