### ISSUE TITLE
Various key recipes dont work in 1.10.2-4.2.45

### ISSUE THREAD

**Issue by daddy77gaming** [blay09/CookingForBlockheads#246]
Hi, as related to issue  #219, which was stated as fixed in next update ( which since dropped) no salt could be crafted among other things that require water.. as the sink doesnt add water to the recipe book.
Second is flour, doesnt show up in recipe book with mortar and pestle and wheat both present..

just dropping these 2 as they are part of most advanced recipes and sort of makes the whole great multiblock kitchen useless, read on various discord groups and so on workaround automating the flour and dough in different ways, but to me that just doesnt make sense cause if you automate that you could automate every food crafting without using this cool mod.
A word on this and future 1.10 support would be apprechiated.. since most modpacks are still based on 1.10 at current date, and the whole idea behind the kitchen is too awesome to not be in ALL packs created.

**Comment by BlayTheNinth** [comment]
Both Cooking for Blockheads **and** Pam's Harvestcraft need to be on the latest version.
