### ISSUE TITLE
Crash with Master-chef Mod installed

### ISSUE THREAD

**Issue by Deing-Young** [blay09/CookingForBlockheads#250]
Version:    CookingForBlockheads_1.10.2-4.2.45             1.10.2-forge1.10.2-12.18.3.2511

Problem:    With Master_Chef_v5.0.1-1.10.X installed (which is not such a famous mod and is not on curseforge), when I open the NoFilter Edition recipe book, there appears to be nothing on the book, and when I scroll down a bit, foods start to appear in the slots, but immediately after that, the game crashes. If I filter the foods by the third filter, still I have to scroll down to see anything, and this time the game does not crash until I scroll down to the bottom.

Crash-report:  http://paste.ubuntu.com/26186570/  (may need copy-pasting the link?)

Since I know nothing about the machenics of mods, I hope desperately that someone could tell me why this is happening and what to do to make these two mods compatible on 1.10.2

**Comment by BlayTheNinth** [comment]
Some of the items (for example, bruschetta) are not being registered by the Master Chef mod. It's something that needs to be fixed on their side, as it will likely cause many other issues as well.

**Comment by Deing-Young** [comment]
Well, guess I'll have to drop that mod, thanks for explaining.
