### ISSUE TITLE
[1.12.0] java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [blay09/CookingForBlockheads#251]
mod Version: 6.3.17
Forge Build: 2443

[https://pastebin.com/dhTMQYTy](log)

**Comment by BlayTheNinth** [comment]
The file was mistakenly marked as supporting 1.12. It requires at least Minecraft 1.12.2.

**Comment by Pythonic-Rainbow** [comment]
Ok I understand.Thank you!
