### ISSUE TITLE
Kitchen Floor recipe using Concrete

### ISSUE THREAD

**Issue by BryanBoru** [blay09/CookingForBlockheads#253]
With the addition of concrete, and with the growing use of quark by many users. I feel like the Kitchen Floor could be made laborious but less 'end game' by using something other than Quartz. Obviously a modpack author can tweak in recipe changes, but I was wondering if you guys were considering using white and black concrete or possibly Quark's polished marble and polished basalt for use in the kitchen floor recipes?
I've tweaked them into a pack I am working on for myself, but felt like I could mention to yourselves to hear what you think on it.?

**Comment by BlayTheNinth** [comment]
Totally missed the addition of concrete, sounds like a fair point. Coal and quartz was just for lack of anything more fitting.

**Comment by BryanBoru** [comment]
Aye, in my pack I am using Ceramics, so as an gaff I am making the players use white and black porcelain. 😄
