### ISSUE TITLE
Fridge door is wrongly rotated [Fix: Update Forge to latest!]

### ISSUE THREAD

**Issue by loudwhitenoise** [blay09/CookingForBlockheads#254]
MC v1.12.2, Cooking for Blockheads v6.3.17, Forge v14.23.1.2582

The fridge model appears to be rotated wrongly.
https://imgur.com/a/J4LHA

**Comment by BlayTheNinth** [comment]
Please try on the latest Forge version (2585+), they recently introduced (and fixed) a bug regarding model rotations.
