### ISSUE TITLE
Merge/Deposit to Chests No Longer Works Since Quark 1.4-121

### ISSUE THREAD

**Issue by SSyl** [blay09/CookingForBlockheads#255]
Quark has the ability to merge/deposit to nearby storage containers. Prior to the latest version of Quark, the Fridge and Counters of CookingForBlockheads worked with the Merge/Deposit to chest functionality of Quark.

Now, when you use the Merge/Deposit option it completely ignores Cooking for Blockheads' storage containers.

I've tried three separate mods that add their own storage versions (Actually Additions' Storage Crates, Iron Chests, Colossal Chests) and they still work with the Merge/Deposit of Quark.

Technical Details:
MC 1.12, Forge 2589
Cooking for Blockheads 1.12-6.3.16
Quark r1.4-121

Also reported on Quark's repo: https://github.com/Vazkii/Quark/issues/744

**Comment by Vazkii** [comment]
This can be fixed by usiing the following API class: https://github.com/Vazkii/Quark/blob/master/src/main/java/vazkii/quark/api/IDropoffManager.java

**Comment by BlayTheNinth** [comment]
This has been fixed in the latest Quark update.
