### ISSUE TITLE
[Request] Support for Chisels & Bits

### ISSUE THREAD

**Issue by chimericdream** [blay09/CookingForBlockheads#257]
Specifically, I'd love to have the ability to put bits in the same block space as some of the block which aren't full 16x16x16. For example, it would be handy to put a fridge into a small alcove with 1-bit thick walls and ceiling so there could be items on top of the fridge itself. Even though it doesn't take up the full block space, the hitbox does, preventing this sort of behavior.

**Comment by BlayTheNinth** [comment]
Sorry, I don't think I'll be doing this. The effort required to make it work (+ the additional maintenance in the future and external mod dependency) doesn't balance out with the benefit of allowing those tiny spaces to be filled.

It would be interesting to have a mod that adds multiparts that can bleed into adjacent blocks (achieving your goal without having to have support in Cooking for Blockheads) ... maybe I'll look at that and release it seperately.
