### ISSUE TITLE
Add a "kitchen kit"

### ISSUE THREAD

**Issue by tivec** [blay09/CookingForBlockheads#26]
First I'd like to thank you for this awesome mod. Totally saving time for anyone using Harvestcraft and especially when combined with hunger overhaul and spice of life.

I would love to see a "kitchen kit". Either a multi slot inventory for the cook book where you can put your harvestcraft tools, or one where you can craft the tools into one item to carry with you.

This would make it easier to cook "on the run" without having to pick up the tools from storage.

**Comment by tivec** [comment]
I tried to cheese this in by using minetweaker and giving the second cookbook all the ore dict entries for the various tools, but that did not seem to work out so well..

**Comment by blay09** [comment]
The next version will add a cooking table which uses ingredients and tools from adjacent inventories. That might be an alternative to carrying all foods and tools around at all times?
