### ISSUE TITLE
Crash while using a Davinci's Vessels ship with a kitchen on-board

### ISSUE THREAD

**Issue by Lurmey** [blay09/CookingForBlockheads#270]
Hiya, was just playing on my server with my modpack, Realistic Survival ([modlist](https://minecraft.curseforge.com/projects/lurms-realistic-survival/relations/dependencies)) and I started up my ship to escape from an incoming tornado, after travelling for just 20 or so blocks, my game froze entirely and promptly crashed. Here's the crash log, it mentions the oven from Cooking For Blockheads so I thought to post it here first.
[crash-2018-03-24_20.24.09-client.txt](https://github.com/blay09/CookingForBlockheads/files/1844766/crash-2018-03-24_20.24.09-client.txt)

Now I've gotta try and get that ship back and hope the tornado didn't whisk it away...

**Comment by BlayTheNinth** [comment]
This is an issue in Davinci's Vessels, it looks like the oven was ticked with an incorrect accompanying block (bedrock, probably due to the movement).

**Comment by Lurmey** [comment]
Okay, thanks! I'll take this to the devs of Davinci's Vessels and see if they can fix it.
