### ISSUE TITLE
Oven with Pam's skillet/pot/etc. causing rendering crash

### ISSUE THREAD

**Issue by dragonshardz** [blay09/CookingForBlockheads#273]
Running the latest version of CFB on client and server (6.3.26) with Forge 2364. Intermittently getting a Rendering Block Entity crash on login when the pots and pans from Pam's Harvestcraft are in the oven's inventory. The crashlog is appended.

[crash-2018-03-30_20.49.38-client.txt](https://github.com/blay09/CookingForBlockheads/files/1865160/crash-2018-03-30_20.49.38-client.txt)

**Comment by BlayTheNinth** [comment]
Try updating your Forge, I can't reproduce this crash and it doesn't make any sense if not for a bug in an older Forge version.
