### ISSUE TITLE
Turn Milk Jar into Cooking Jar

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/CookingForBlockheads#277]
Or a similar name. Allow fluids other than just milk for food mods that use other fluids for cooking.

**Comment by Syndaryl** [comment]
But what would be the plan for the poor cow? :D

**Comment by BlayTheNinth** [comment]
It would still be used in the same way to craft the Cow in a Jar, just the cow-less version would no longer be restricted to milk only.

**Comment by BlayTheNinth** [comment]
Not sure about this any more, I think I'd prefer specialized fluid containers for whatever else comes up (if there even is anything).
