### ISSUE TITLE
Piping anything other than water into the sink voids it

### ISSUE THREAD

**Issue by Xiaminou** [blay09/CookingForBlockheads#278]
If you pipe any liquid that's not water into CFB's sink that liquid will be voided. I only tested it with "infinite water" disabled, so I have to pipe water into it.

https://youtu.be/VwNbkQyRiHc

Environment: Server
Minecraft: 1.12.2
Forge: 2641
Mods: [list.txt](https://github.com/blay09/CookingForBlockheads/files/1887729/list.txt)

**Comment by BlayTheNinth** [comment]
That's intended behaviour, the sink acts both as a water provider but also as a liquid nullifier. You can empty out any bucket (and even potions, I think) in it.

Is there any reason it shouldn't? I feel you could probably avoid unwanted voiding through pipe management.

**Comment by Xiaminou** [comment]
No reason, it's just unexpected, it took me some time before I realised it was what was voiding my fluids. Maybe a tooltip or something then, make it a config option? or an in-game option?

**Comment by BlayTheNinth** [comment]
I will probably disable it for piped in fluids in 1.13.

**Comment by Xiaminou** [comment]
Sounds good.

**Comment by WrongWeekend** [comment]
Why not allow other fluids to be piped into and drawn from the sink for easy crafting?

**Comment by BlayTheNinth** [comment]
That would be unclear and confusing and is not what a sink is. 

You're thinking of some kind of fluid tank, which is already planned for 1.13, see #277

**Comment by Xiaminou** [comment]
A bit off topic but what would be nice is to have the sink have some visual representation of the water when it's not set to be an infinite source.

**Comment by BlayTheNinth** [comment]
#282

**Comment by Lurmey** [comment]
Along a similar vein, it'd be nice to have a config option to specify which liquid the sink is expecting when the option "sink requires water to be piped in" is on. I have Tough as Nails installed, that makes regular water be treated as "dirty" and adds its own "purified water". I'd like the sink to be expecting that purified water rather than the regular dirty water.
