### ISSUE TITLE
[1.11.2] Fridge Rendering Issue (Forge Bug, downgrade Forge to fix)

### ISSUE THREAD

**Issue by Elmfeather7** [blay09/CookingForBlockheads#280]
So the cooking for block heads fridge renders strangely and the doors only face one direction.  if they are placed facing another way they render weird and don't work correctly. I've updated Forge to the latest and it still is having troubles. 

playing on 1.11.2
Forge: 2588 (latest)

**Comment by PoptartKing99** [comment]
I am having the same bug as well, it looks like it's having a problem with optifine and it's smooth lighting settings.

**Comment by BlayTheNinth** [comment]
This is a bug in the latest version(s?) of Forge for 1.11.2. The recommended version of Forge (13.20.1.2386) works fine.
