### ISSUE TITLE
Presser support in Kitchen

### ISSUE THREAD

**Issue by blipadouzi** [blay09/CookingForBlockheads#285]
Could you please either add support for Pam's Presser (that makes honey) or create one of your own that would be recognized by the multiblock kitchen?

Thank you

**Comment by HalJordan** [comment]
This sounds nice, but if you're doing tofu, it can get convoluted and take a while. It's kinda cheaty, but I just set it up with eio conduits and filters, then have the soybeans and silken tofu passed through until the soy milk and firm tofu are full, then stop the beans when the silken is done. The presser takes so long that I'd rather have that stuff on hand than wait around for each one to be made.

**Comment by BlayTheNinth** [comment]
Don't think the Presser exists anymore in Pams HC2
