### ISSUE TITLE
Connection Lost when click GUI of tier0 book

### ISSUE THREAD

**Issue by bakaxyf** [blay09/CookingForBlockheads#29]
![image](https://cloud.githubusercontent.com/assets/10368307/8909398/bc1df9ee-34b3-11e5-928d-c9fcae877804.png)

https://gist.github.com/bakaxyf/908067ba5bd3f5808fd9

**Comment by bakaxyf** [comment]
Problem solved. Suspecting the conflict between Forestry and NEI-Integration
It isn't CookingForBlockheads' issue

**Comment by bakaxyf** [comment]
Still happen when Forestry only.
https://gist.github.com/bakaxyf/6d4c6f39e6438b305362

**Comment by blay09** [comment]
I believe this was fixed in #50 as well and should no longer happen on builds 79+.

**Comment by bakaxyf** [comment]
Problem solved after update.
