### ISSUE TITLE
[Suggestion] Add Bread Basket/Box and add Multiple Items on Counters

### ISSUE THREAD

**Issue by MokahTGS** [blay09/CookingForBlockheads#296]
I love that your adding more storage options, but it creates a problem of counter space that could be solved how you handle pots on the stove.  If possible, could you add the enhancement of putting multiple containers, toasters, fruit bowls on the same counter top?

**Comment by BlayTheNinth** [comment]
I don't think the bread basket would be much different from the fruit basket, so you could just use that one to store your bread. Multiple pieces on one counter top won't become a thing, it doesn't match how Vanilla works and would look rather odd (since the models would have to shrink).
