### ISSUE TITLE
[Feature/Compatibility] Spice of Life: Carrot Edition filtering

### ISSUE THREAD

**Issue by PCSpinner** [blay09/CookingForBlockheads#297]
SoL: Carrot Edition rewards you for eating different foods at least once. It tracks whether each food has been eaten or not. I believe there is a per player list of which foods have been eaten. 

Would it be possible to add a filter to the recipe book to hide the foods you've already eaten?

**Comment by BlayTheNinth** [comment]
The next version will consider tooltips in the search, meaning you will be able to search for "Not yet eaten" or whatever it says in the tooltip to achieve this behaviour.

**Comment by PCSpinner** [comment]
That will help tremendously!
