### ISSUE TITLE
[1.12.2] Fridge doesn't render items inside it.

### ISSUE THREAD

**Issue by brisingraerowing** [blay09/CookingForBlockheads#303]
As per title. With C4B v6.4.44, items don't render inside the fridges. They do render in the cabinets, and I haven't tested the stove yet.

**Comment by BlayTheNinth** [comment]
They're rendering fine for me, do you have any mods that affect rendering installed (e.g. Optifine)? Is there some graphically fancy block nearby that may be affecting the fridge rendering by accident? What items are inside the fridge (I tested with apples)?

Also, what Forge version are you on?

**Comment by brisingraerowing** [comment]
No optifine. The only other blocks that were nearby were from an AE2 setup. It didn't matter what was in the fridge. This is probably another bug like the one I'm having with Refined Storage, where I'm the only one it affects.

EDIT: I was on Forge 2739, I've updated to 2745 and will see if that changes anything.

**Comment by brisingraerowing** [comment]
They render in the new version, although I tested in a superflat world. I'll retest in a normal world and see if that changes anything. I was in an ocean biome when they didn't render, though.

And I just thought of something, I had some C&B blocks nearby for lighting. Those may have been it.

**Comment by brisingraerowing** [comment]
Still works even with a C&B block there. I'll go ahead and close this.

**Comment by Xerxeth** [comment]
Actually have this issue as well on Forge 2760.
C4B is version 6.4.62
All other cabinets render fine, pack is Direwolf20 1.12.2 v2.3.0

**Comment by 4cello** [comment]
For me, this problem appears only for fridges where the door handle is on the left side. [Pics (Both fridges are filled)](https://imgur.com/a/NrSdcLm)

**Comment by brisingraerowing** [comment]
Had this again. Handle was on the left side (as above commenter noted). I’ll get versions when I get back to my computer.

**Comment by SYDoukou** [comment]
So has it been fixed? Ran into this problem today myself, thought it is a new bug
