### ISSUE TITLE
[Feat Req] Food processor appliance

### ISSUE THREAD

**Issue by Kremnari** [blay09/CookingForBlockheads#305]
I would like to suggest an automatic food processor that can sit on counters.  You could place upto three items in it, and it would autocraft from items in the kitchen (probably upto a configuable stacksize, 6 maybe?) and it would prevent the last from being used up.

This way some things like salt or dough could be kept in stock.

Also, perhaps adding a "fuse box" block would allow the kitchen multiblock to recieve power for all components (so the food processor can use power with the RF stove upgrade).

Loving the mod, thank you!

**Comment by Ichirou-Tomoe** [comment]
I don't see wich kitchen appliance they would pass as... 
That being said, the ability to automatically to every sub craft needed for a recipe could be added to the cooking table just like the fridge and oven add-on works.
But this is discussed in issue #112
