### ISSUE TITLE
Enabling bigger storage changes nothing

### ISSUE THREAD

**Issue by TheRealDadbeard** [blay09/CookingForBlockheads#306]
I enabled the option but still the same size. I get no error or something either.

MC 1.12.2
Forge 2750
CFB 6.4.44

I'm looking at existing blocks

**Comment by BlayTheNinth** [comment]
I believe the option only applies to newly placed kitchen counters. Fridges and others are unaffected in general. I may look into auto-upgrading existing kitchen counters to the bigger size in a future version.
