### ISSUE TITLE
Suggestion: Config-assignable loot tables

### ISSUE THREAD

**Issue by Deightine** [blay09/CookingForBlockheads#313]
I was wondering if there was any chance of adding a config option for the fridge and cabinet that allowed a user to supply a loot table (ex. fridgeloot="minecraft:chests/simple_dungeon")?

That way if either is generated into the world rather than created by a player, it will pull from a loot table. Even better would be if it could handle multiple loot tables and pick one of them at random or with percentage weighting.

Alternately, it would be great if it also just added a default loot table (including some vanilla ingredients and the cookbook) to the mod itself which modders/modpackers could change from the outside with tools.

Thanks for taking the time to read this. Kudos on CFB. It's really cool. :)

**Comment by BlayTheNinth** [comment]
This sounds a lot like something that should be handled by the mod handling the world generation, not by each other mod individually. I wouldn't be surprised if e.g. Recurrent Complex already supports custom loot tables for generated inventories.

**Comment by Deightine** [comment]
Edit: Wiped out a bunch of irrelevant information, after stumbling across a possible solution that won't require anyone add so much as a twinge of code anywhere. Feel free to kill the thread with impunity.

I appreciate you taking the time to respond. :) Keep up the awesome work. I'm really enjoying CFB.
