### ISSUE TITLE
Fruit Basket and Spice Rack Quark compatability broken

### ISSUE THREAD

**Issue by Syndaryl** [blay09/CookingForBlockheads#321]
The regular cabinets and the fridge are able to use the Quark "drop off" functionality, allowing me to quickly clear my inventory. The fruit basket and the spice racks are not currently working with this.

IIRC there's an Interface to implement for it to work?

**Comment by BlayTheNinth** [comment]
The reason for this is that there's no filtering as to which items are going to be inserted using the dropoff, which would create weirdness like dirt blocks being put into the fruit basket. This "issue" is less visible with fridges and counters that are more of a general storage, but it looks pretty bad in the case of the blocks that display the items at all times (such as the spice rack and fruit basket).

I think what I might do is have it always force the smart-dropoff, where it will only insert items if an item of the type already exists.

**Comment by Syndaryl** [comment]
I confess I never thought of the "dumb" drop-off, as I exclusively use the smart drop-off feature. This looks like a good solution, however.

**Comment by ghost** [comment]
https://github.com/blay09/CookingForBlockheads/issues/323
