### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Omnimetatron** [blay09/CookingForBlockheads#322]
Just updated to new version (6.4.61) and upon loading Minecraft I'm getting this an NPE. No issues with previous version so I'll roll back to that one for now.
https://pastebin.com/b6Kb2sBt

**Comment by Cirrus0** [comment]
Can confirm, probably linked to the fix for #321 ?

**Comment by ghost** [comment]
https://github.com/blay09/CookingForBlockheads/issues/323

**Comment by Omnimetatron** [comment]
Whatever you did fixed it for me, thanks. Nice work on the quick turnaround!
