### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by Nesroht** [blay09/CookingForBlockheads#331]
Found a dupe bug in the FTB Continuum pack in regards to an interaction between the cooking table and the oven. If you ask the cooking table to craft lots of a single cookable item untill the oven is full, itll start dropping full stacks of the uncooked item.

On a LAN server of FTB Continuum v.1.5.2 on Minecraft 1,12,2, added veinminer to the pack.

**Comment by minimuscle** [comment]
You closed this, did you find the issue?

**Comment by BlayTheNinth** [comment]
See #325 #332 #334 (=> it's been fixed in the next version already)
