### ISSUE TITLE
Recipe stack dupe

### ISSUE THREAD

**Issue by Drarthe** [blay09/CookingForBlockheads#332]
When doing a shift-click for a recipe, if I run out of the core item (chicken and bread so far, for cooked chicken and toast), then I get a full stack of the uncooked item in my inventory.  I am using the modpack Stoneblock, haven't tested with just the singular mod yet.

**Comment by fandomaniac** [comment]
What version of CookingForBlockheads is the pack using? There was a duplication bug in an older version of the mod that was fixed in the latest release.

**Comment by Drarthe** [comment]
6.4.63, which I thought was the latest version, but I now see that .65 is the latest.
