### ISSUE TITLE
Raw Calamari (Pam's Harvestcraft) dupe glitch!

### ISSUE THREAD

**Issue by merdinarchfire** [blay09/CookingForBlockheads#334]
I have a kitchen setup with 4 pieces, the crafting counter, a storage counter, a corner counter, an oven, with bakeware and pot inside, using mini coal(Actually Additions)to cook, and a tool rack above. When I click on the recipe to cook Raw Calamari it gives me a stack of 64 every time I click on it.

Here is a screenshot of my setup:
![2018-10-16_11 31 27](https://user-images.githubusercontent.com/17118955/46991102-10cbd380-d137-11e8-87c2-004cf8587d42.png)

![2018-10-16_11 35 08](https://user-images.githubusercontent.com/17118955/46991217-9059a280-d137-11e8-8064-1d9966eb6b02.png)

Here are the versions I have:
Minecraft 1.12.2
Forge 12.23.4.2759
Cooking for Blockheads 6.4.61
Pam's HarvestCraft 1.12a
Actually Additions 1.12.2-r140

**Comment by merdinarchfire** [comment]
A quick update, it seems to be happening with all Pam's fish to some degree. It is also happening with Minecraft raw fish. With no coal of any kind in the stove.

**Comment by Skydragonsz** [comment]
You need to update to the latest CfB 
See #332 and #325

**Comment by merdinarchfire** [comment]
Thanks! 👍
