### ISSUE TITLE
Ice/Snow Maker Upgrade doesn't work

### ISSUE THREAD

**Issue by Thiana** [blay09/CookingForBlockheads#335]
The fridge upgrade doesn't appear to provide snowballs for Pam's recipe (ice cream specifically). The multiblock used was fridge(both upgrades)/table/oven/sink and appropriate utensils. With snowballs in inventory the recipe appears in the table, and crafts without issue. Without the snowballs, but all other ingredients no recipe appears. Thanks.

Versions:
- MC 1.12.2
- Forge 2768
- CfB 6.4.65
- Pams 1.12.2za

**Comment by nephatrine** [comment]
This still seems to be the case. Is this being worked on?
