### ISSUE TITLE
crash with the latest version and Quarks while looking at reciptes

### ISSUE THREAD

**Issue by JasonKillsUs** [blay09/CookingForBlockheads#340]
Greeting: MC 1.12/2772

Crash with the latest Version (CookingForBlockheads_1.12.2-6.4.65) and Quark (Quark-r1.5-130) while browsing recipes in the Cooking-table, I also noticed that the inserted Food is not showing up in the Fridge when open the Door, while in the Cabinets it does.

https://paste.ee/p/TsGYe

thanks for looking into it

besides that fantastic Mod :-)

**Comment by red360** [comment]
Having the same issue. Quark 1.5-141. Cooking for Blockheads 1.12.2-6.4.65
https://paste.ee/p/sUb4U
Update: When reverting back to CFB ver 1.12.2-6.4.44 it doesn't crash.

**Comment by red360** [comment]
Update to the latest version of Quark-r1.5-142. Issue is fixed.
