### ISSUE TITLE
Server crash with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ghost** [blay09/CookingForBlockheads#342]
Hello,
currently this mod is crashing our server with the following report:

> [14:05:11] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
> java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 27
>         at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
>         at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
>         at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
> Caused by: java.lang.ArrayIndexOutOfBoundsException: 27
>         at net.blay09.mods.cookingforblockheads.api.capability.KitchenItemProvider.getSimulatedUseCount(KitchenItemProvider.java:37) ~[KitchenItemProvider.class:?]
>         at net.blay09.mods.cookingforblockheads.api.capability.DefaultKitchenItemProvider.findSource(DefaultKitchenItemProvider.java:45) ~[DefaultKitchenItemProvider.class:?]
>         at net.blay09.mods.cookingforblockheads.registry.CookingRegistry.findAnyItemStack(CookingRegistry.java:271) ~[CookingRegistry.class:?]
>         at net.blay09.mods.cookingforblockheads.registry.CookingRegistry.findSourceCandidates(CookingRegistry.java:285) ~[CookingRegistry.class:?]
>         at net.blay09.mods.cookingforblockheads.registry.CookingRegistry.getRecipeStatus(CookingRegistry.java:331) ~[CookingRegistry.class:?]
>         at net.blay09.mods.cookingforblockheads.container.ContainerRecipeBook.findAndSendItemList(ContainerRecipeBook.java:214) ~[ContainerRecipeBook.class:?]
>         at net.blay09.mods.cookingforblockheads.container.ContainerRecipeBook.func_75142_b(ContainerRecipeBook.java:146) ~[ContainerRecipeBook.class:?]
>         at net.minecraft.inventory.Container.func_75132_a(Container.java:53) ~[afr.class:?]
>         at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:101) ~[FMLNetworkHandler.class:?]
>         at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
>         at net.blay09.mods.cookingforblockheads.block.BlockCookingTable.func_180639_a(BlockCookingTable.java:91) ~[BlockCookingTable.class:?]
>         at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
>         at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
>         at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
>         at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
>         at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
>         at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
>         ... 5 more

This happens every time someone right-clicks the Cooking Table.

The server is running the FTB Revelation modpack 2.6.0-1.12.2 with CookingForBlockheads 1.12.2-6.4.65.

**Comment by Mugiwaxar** [comment]
Same for me
Server crash when I try to use the Cooking Table

**Comment by Mugiwaxar** [comment]
Ok, found why
Because of that:
`# Enabling this will make the kitchen counters have twice as much inventory space.
    B:"Large Counters"=true`

If you have charged this value middle game, cabinet can have different size, and make the game crash!
Can also appen if the config betweeen the client and the server differ

**Comment by BlayTheNinth** [comment]
This was fixed a while back, must have forgotten to close.
