### ISSUE TITLE
[Suggestion] Lunch Box?

### ISSUE THREAD

**Issue by HeavyDeception** [blay09/CookingForBlockheads#344]
Would it be possible to add a lunch box so you can store food in it but you don't have to pull the food out to eat it? I think where was a mod like that at one time but I can no longer find it.

**Comment by BlayTheNinth** [comment]
Spice of Life is the mod adding the lunch box, but it also does changes to how food works.

**Comment by HeavyDeception** [comment]
Sorry I haven't replayed and that's the one but ya I have nutrients in the mod pack so the two would kind of clash with each other. Thank you.
