### ISSUE TITLE
skyfactory 3 no kitchen floor  and blocks don't connect 

### ISSUE THREAD

**Issue by xoniogaming** [blay09/CookingForBlockheads#347]
im having trouble getting the kitchen floor because its does not exist and the kitchen items dont connect and theres no kitchen cabinet corner

**Comment by BlayTheNinth** [comment]
Sky Factory 3 runs on Minecraft 1.10, the blocks you are mentioning have been added in a later version of the mod (starting Minecraft 1.11). Even if the kitchen is not connecting visually, the multiblock functionality is available.
