### ISSUE TITLE
2x2 Recipes from CraftTweaker do not work correctly

### ISSUE THREAD

**Issue by Sunekaer** [blay09/CookingForBlockheads#348]
Hey

So i changed the recipe for AA Dough via crafttweaker, but the Cooking Table is showing the old recipe and doesnt work, hasnt been able to find a way to change it in the Cooking Table, please assist 

https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/114

**Comment by BlayTheNinth** [comment]
I tried to reproduce with the following script:
```
recipes.removeShaped(<minecraft:bread>, [[null, null, null],[<minecraft:wheat>, <minecraft:wheat>, <minecraft:wheat>], [null, null, null]]);
recipes.addShaped(<minecraft:bread>, [[<minecraft:wheat>, null, null],[null, <minecraft:dirt>, null], [null, null, null]]);
```

and it's working fine for me.

**Comment by Sunekaer** [comment]
```
recipes.remove(<actuallyadditions:item_misc:4>);
recipes.addShaped(<actuallyadditions:item_misc:4>*2, [
  [<minecraft:wheat>, null],
  [null, <minecraft:wheat>]
]);
```
Is the code i use in Stoneblock there causes the issue
2x2 recipe
