### ISSUE TITLE
Uncraftable Potion

### ISSUE THREAD

**Issue by StoneLegion** [blay09/CookingForBlockheads#354]
I hope this is this mod but I bet it's going be a conflict and annoying to find lol.

So when I right click the Sink with a empty bottle I end up getting an uncraftable potion.

Happens both MP and SP using the Pack "The Next Leap"

**Comment by StoneLegion** [comment]
I sadly just tried the mod on its own so it does seem to be another mod conflicting with it. Will attempt to find out what mod.

**Comment by srwaggon** [comment]
I'm getting this as well.

I didn't always.
Some notable mods I've added recently include
* Thaumcraft
* Railcraft
* Forestry
* Tinker's Construct
* sadly many others.

My pack is loosely based on RLCraft. Vanilla RLCraft + CFB doesn't appear to yield this bug, but something I've added in my pack contributes.

**Comment by srwaggon** [comment]
@blay09 I see that this was closed. What was the fix?

**Comment by BlayTheNinth** [comment]
It was closed due to inactivity. No idea if it's fixed itself or what mod is causing the problem.
