### ISSUE TITLE
Client Crash, Forestry Ambrosia

### ISSUE THREAD

**Issue by NielsPilgaard** [blay09/CookingForBlockheads#355]
Hello! A user of mine reported a soft-crash to main menu when clicking Forestry Ambrosia in both the no filter book and Cooking for Blockheads crafting table, here's the original report:

**Issue Description**

As per my previous description, when using the Cooking for Blockheads #no filter book and clicking the recipe for Forestry Ambrosia the game crashes ("Connection Lost...") out to a searching for server screen in the Minecraft app (I assume this might be because the world is treated as a server in the internal workings of Minecraft, but to be sure, I am not running this on a server).  Re-logging into the world using normal single player mode and everything is ok. The crash is repeatable and consistent.

**Mod versions**
- CookingForBlockheads_1.12.2-6.4.69
- Forge 1.12.2-14.23.5.2781

**Logs**

[Snippet of the latest.log, what I think is helpful](https://gist.github.com/NillerMedDild/bc66eb4db14154b4dfc267869581920e)
[entire latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2800389/latest.log)

**Comment by BlayTheNinth** [comment]
I can't reproduce it (at least not with just Forestry and Cooking for Blockheads) and I'm not sure what could be causing it. Is there anything special with the Ambrosia recipe in your pack?

This is the recipe I'm getting:
![image](https://user-images.githubusercontent.com/1933180/55671020-90875f00-588b-11e9-9f07-25f8b53cf7b8.png)

**Comment by NielsPilgaard** [comment]
Nope, it's the normal recipe. However if you can't reproduce, I'll just close the issue, thanks for checking :)
