### ISSUE TITLE
Crash when click arrow button in book

### ISSUE THREAD

**Issue by bakaxyf** [blay09/CookingForBlockheads#36]
https://gist.github.com/bakaxyf/006b267821dcf019a8de

**Comment by blay09** [comment]
Looks like an issue with Botania or whatever adds the recipe with that mushroom item; the same recipe would most likely crash in NEI too. Nothing I can really do about it.

**Comment by bakaxyf** [comment]
![image](https://cloud.githubusercontent.com/assets/10368307/9254126/5e5d37ca-4214-11e5-871b-f6cd329678a9.png)
Don't crash in NEI.

**Comment by bakaxyf** [comment]
Still crash.
