### ISSUE TITLE
Client crashes when ticking block entity: TileOven

### ISSUE THREAD

**Issue by RyanJM93** [blay09/CookingForBlockheads#360]
Time: 2/21/19 4:44 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at net.blay09.mods.cookingforblockheads.tile.TileOven.func_73660_a(TileOven.java:121)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1846)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at net.blay09.mods.cookingforblockheads.tile.TileOven.func_73660_a(TileOven.java:121)

-- Block entity being ticked --
Details:
	Name: cookingforblockheads:oven // net.blay09.mods.cookingforblockheads.tile.TileOven
	Block type: ID #0 (tile.air // net.minecraft.block.BlockAir // minecraft:air)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (511,84,1647), Chunk: (at 15,5,15 in 31,102; contains blocks 496,0,1632 to 511,255,1647), Region: (0,3; contains chunks 0,96 to 31,127, blocks 0,0,1536 to 511,255,2047)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir // minecraft:air)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['LavaGriffin'/5545308, l='MpServer', x=394.50, y=69.00, z=1481.50]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-143,64,337), Chunk: (at 1,4,1 in -9,21; contains blocks -144,0,336 to -129,255,351), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 37198475 game time, 51124349 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 121 total; [EntityZombie['Zombie'/5545548, l='MpServer', x=366.50, y=15.00, z=1472.50], MoCEntityButterfly['ButterFly'/5545584, l='MpServer', x=415.41, y=69.00, z=1533.03], EntityWolf['Wolf'/5545585, l='MpServer', x=420.15, y=69.00, z=1481.91], EntityWolf['Wolf'/5545586, l='MpServer', x=420.32, y=69.00, z=1485.46], EntityCreeper['Creeper'/5545340, l='MpServer', x=316.50, y=40.00, z=1547.50], EntityCreeper['Creeper'/5545341, l='MpServer', x=316.50, y=40.00, z=1545.50], EntityChicken['Chicken'/5545597, l='MpServer', x=463.85, y=72.00, z=1504.49], EntityChicken['Chicken'/5545598, l='MpServer', x=468.49, y=72.00, z=1504.99], EntityChicken['Chicken'/5545599, l='MpServer', x=468.03, y=72.00, z=1504.79], EntityItem['item.tile.obsidian'/5545580, l='MpServer', x=433.48, y=46.00, z=1510.79], EntityDonkey['Donkey'/5545581, l='MpServer', x=446.84, y=72.00, z=1508.74], MoCEntityHorse['WildHorse'/5545582, l='MpServer', x=444.11, y=72.00, z=1510.89], MoCEntityThrowableRock['entity.mocreatures:trock.name'/5545583, l='MpServer', x=416.50, y=70.00, z=1526.22], EntityItem['item.item.string'/5545576, l='MpServer', x=422.00, y=57.00, z=1429.88], EntityCreeper['Creeper'/5545577, l='MpServer', x=436.74, y=35.00, z=1402.87], MoCEntityAnt['Ant'/5545500, l='MpServer', x=409.50, y=69.00, z=1473.50], MoCEntityButterfly['ButterFly'/5545501, l='MpServer', x=412.50, y=69.00, z=1487.50], MoCEntityFly['Fly'/5545502, l='MpServer', x=412.50, y=69.00, z=1487.50], EntityWolf['Wolf'/5545503, l='MpServer', x=415.63, y=69.00, z=1486.22], MoCEntityFly['Fly'/5545498, l='MpServer', x=410.50, y=69.00, z=1475.50], MoCEntityFly['Fly'/5545499, l='MpServer', x=406.50, y=69.00, z=1478.50], EntitySheep['Sheep'/5545520, l='MpServer', x=395.30, y=69.00, z=1419.56], MoCEntitySnail['Snail'/5545521, l='MpServer', x=398.42, y=70.00, z=1408.05], EntityItem['item.item.string'/5545508, l='MpServer', x=410.50, y=40.00, z=1525.88], EntityItem['item.item.string'/5545509, l='MpServer', x=385.92, y=36.00, z=1535.61], EntitySkeleton['Skeleton'/5545510, l='MpServer', x=415.50, y=44.00, z=1496.50], EntitySkeleton['Skeleton'/5545511, l='MpServer', x=411.30, y=41.67, z=1495.58], MoCEntityMaggot['Maggot'/5545504, l='MpServer', x=388.85, y=70.00, z=1466.15], EntityCow['Cow'/5545505, l='MpServer', x=384.18, y=70.00, z=1465.68], MoCEntityDragonfly['DragonFly'/5545506, l='MpServer', x=390.50, y=70.00, z=1450.50], EntitySheep['Sheep'/5545516, l='MpServer', x=393.21, y=69.00, z=1424.70], EntityCow['Cow'/5545515, l='MpServer', x=412.15, y=69.00, z=1416.34], MoCEntitySnail['Snail'/5545428, l='MpServer', x=380.64, y=71.00, z=1456.92], EntitySkeleton['Skeleton'/5545424, l='MpServer', x=376.50, y=17.00, z=1465.50], MoCEntityMaggot['Maggot'/5545425, l='MpServer', x=377.96, y=71.00, z=1459.88], MoCEntityMaggot['Maggot'/5545426, l='MpServer', x=376.25, y=71.00, z=1458.51], MoCEntitySnail['Snail'/5545427, l='MpServer', x=376.74, y=71.00, z=1458.28], EntitySpider['Spider'/5545436, l='MpServer', x=362.06, y=15.00, z=1555.47], EntitySkeleton['Skeleton'/5545437, l='MpServer', x=362.50, y=15.00, z=1557.50], EntitySkeleton['Skeleton'/5545438, l='MpServer', x=363.50, y=15.00, z=1556.50], EntityZombie['Zombie'/5545439, l='MpServer', x=366.50, y=15.00, z=1553.50], MoCEntitySilverSkeleton['SilverSkeleton'/5545435, l='MpServer', x=382.49, y=24.00, z=1541.24], EntityZombie['Zombie'/5545414, l='MpServer', x=377.50, y=35.00, z=1516.50], EntitySkeleton['Skeleton'/5545415, l='MpServer', x=371.50, y=35.00, z=1517.50], EntityItem['item.item.string'/5545420, l='MpServer', x=366.31, y=68.00, z=1502.19], MoCEntityWraith['Wraith'/5545421, l='MpServer', x=376.85, y=18.41, z=1465.92], EntitySkeleton['Skeleton'/5545422, l='MpServer', x=377.50, y=17.00, z=1465.50], EntitySkeleton['Skeleton'/5545423, l='MpServer', x=377.50, y=17.00, z=1465.50], EntitySkeleton['Skeleton'/5545416, l='MpServer', x=376.30, y=35.00, z=1516.51], EntityCreeper['Creeper'/5545417, l='MpServer', x=352.84, y=33.00, z=1503.41], EntitySpider['Spider'/5545418, l='MpServer', x=358.27, y=64.03, z=1497.62], EntityCreeper['Creeper'/5545419, l='MpServer', x=359.46, y=63.00, z=1498.06], MoCEntityAnt['Ant'/5545456, l='MpServer', x=355.73, y=70.67, z=1442.99], MoCEntitySnail['Snail'/5545457, l='MpServer', x=363.07, y=69.00, z=1423.85], MoCEntityMaggot['Maggot'/5545458, l='MpServer', x=362.27, y=69.00, z=1423.36], EntityItem['item.item.string'/5545440, l='MpServer', x=380.21, y=35.00, z=1525.88], EntitySheep['Sheep'/5545452, l='MpServer', x=369.80, y=70.00, z=1454.50], MoCEntitySnail['Snail'/5545453, l='MpServer', x=357.76, y=71.00, z=1463.37], MoCEntityRoach['Roach'/5545454, l='MpServer', x=373.50, y=69.00, z=1413.50], MoCEntityAnt['Ant'/5545455, l='MpServer', x=384.08, y=69.67, z=1423.56], MoCEntitySilverSkeleton['SilverSkeleton'/5545449, l='MpServer', x=369.50, y=26.00, z=1446.50], MoCEntitySnail['Snail'/5545450, l='MpServer', x=378.94, y=70.00, z=1449.29], MoCEntitySnail['Snail'/5545451, l='MpServer', x=377.54, y=72.00, z=1446.13], EntityItem['item.item.string'/5545364, l='MpServer', x=335.41, y=28.00, z=1482.13], EntityChicken['Chicken'/5545620, l='MpServer', x=468.34, y=72.00, z=1500.88], EntitySkeleton['Skeleton'/5545365, l='MpServer', x=330.17, y=27.33, z=1476.41], EntityChicken['Chicken'/5545621, l='MpServer', x=467.63, y=72.00, z=1500.88], EntityCow['Cow'/5545623, l='MpServer', x=468.46, y=72.00, z=1490.57], EntityChicken['Chicken'/5545616, l='MpServer', x=468.88, y=72.00, z=1500.82], EntityCow['Cow'/5545617, l='MpServer', x=467.74, y=72.00, z=1494.31], EntityCow['Cow'/5545618, l='MpServer', x=469.92, y=72.00, z=1490.45], EntityChicken['Chicken'/5545628, l='MpServer', x=467.66, y=72.00, z=1501.36], EntityChicken['Chicken'/5545629, l='MpServer', x=465.16, y=72.00, z=1503.47], MoCEntityHorse['WildHorse'/5545630, l='MpServer', x=454.17, y=73.00, z=1512.46], EntityChicken['Chicken'/5545631, l='MpServer', x=463.00, y=72.00, z=1504.49], EntityPlayerSP['LavaGriffin'/5545308, l='MpServer', x=394.50, y=69.00, z=1481.50], EntityCow['Cow'/5545624, l='MpServer', x=468.29, y=72.00, z=1493.76], EntityCow['Cow'/5545625, l='MpServer', x=469.24, y=72.00, z=1490.92], EntityChicken['Chicken'/5545626, l='MpServer', x=467.51, y=72.00, z=1503.63], EntityChicken['Chicken'/5545604, l='MpServer', x=466.78, y=72.00, z=1501.56], MoCEntityMaggot['Maggot'/5545349, l='MpServer', x=317.65, y=67.00, z=1433.90], EntityCow['Cow'/5545605, l='MpServer', x=467.11, y=72.00, z=1490.85], EntityCow['Cow'/5545350, l='MpServer', x=317.82, y=69.00, z=1437.46], EntityChicken['Chicken'/5545606, l='MpServer', x=467.05, y=72.00, z=1501.26], EntityCow['Cow'/5545607, l='MpServer', x=469.19, y=72.00, z=1493.85], EntityChicken['Chicken'/5545600, l='MpServer', x=466.96, y=72.00, z=1504.86], EntitySkeleton['Skeleton'/5545602, l='MpServer', x=456.50, y=70.00, z=1525.50], MoCEntityAnt['Ant'/5545347, l='MpServer', x=328.60, y=70.00, z=1411.60], EntityCow['Cow'/5545603, l='MpServer', x=469.92, y=72.00, z=1495.92], EntityChicken['Chicken'/5545356, l='MpServer', x=318.80, y=70.00, z=1409.45], EntityCow['Cow'/5545613, l='MpServer', x=467.92, y=72.00, z=1495.92], EntityChicken['Chicken'/5545614, l='MpServer', x=464.24, y=72.00, z=1501.35], EntityCow['Cow'/5545615, l='MpServer', x=468.70, y=72.00, z=1492.19], EntityChicken['Chicken'/5545608, l='MpServer', x=469.17, y=72.00, z=1502.42], EntityCow['Cow'/5545609, l='MpServer', x=469.92, y=72.00, z=1494.61], MoCEntityMaggot['Maggot'/5545354, l='MpServer', x=332.37, y=72.00, z=1405.05], EntityChicken['Chicken'/5545355, l='MpServer', x=314.51, y=70.00, z=1415.53], EntityChicken['Chicken'/5545611, l='MpServer', x=469.17, y=72.00, z=1501.29], EntityCreeper['Creeper'/5545396, l='MpServer', x=336.50, y=27.00, z=1468.50], EntityItem['item.item.string'/5545397, l='MpServer', x=344.23, y=36.00, z=1454.15], MoCEntitySnake['Snake'/5545398, l='MpServer', x=339.70, y=69.00, z=1428.02], MoCEntityMaggot['Maggot'/5545399, l='MpServer', x=341.90, y=71.00, z=1409.61], EntityChicken['Chicken'/5545648, l='MpServer', x=461.24, y=72.00, z=1502.63], EntityChicken['Chicken'/5545649, l='MpServer', x=462.44, y=72.00, z=1501.36], EntityChicken['Chicken'/5545650, l='MpServer', x=462.91, y=72.00, z=1501.74], EntityChicken['Chicken'/5545651, l='MpServer', x=461.42, y=72.00, z=1503.88], EntitySkeleton['Skeleton'/5545380, l='MpServer', x=328.50, y=37.00, z=1543.50], EntitySkeleton['Skeleton'/5545381, l='MpServer', x=326.50, y=37.00, z=1545.50], EntityPig['Pig'/5545637, l='MpServer', x=462.50, y=69.00, z=1431.67], EntitySkeleton['Skeleton'/5545382, l='MpServer', x=324.50, y=37.00, z=1545.50], MoCEntityHorse['WildHorse'/5545632, l='MpServer', x=452.98, y=72.00, z=1507.01], EntityItem['item.item.string'/5545377, l='MpServer', x=336.91, y=20.00, z=1521.08], EntityChicken['Chicken'/5545633, l='MpServer', x=463.37, y=72.00, z=1504.05], EntitySpider['Spider'/5545378, l='MpServer', x=345.43, y=21.67, z=1529.99], EntitySkeleton['Skeleton'/5545379, l='MpServer', x=326.50, y=37.00, z=1543.50], EntityCow['Cow'/5545644, l='MpServer', x=462.48, y=72.00, z=1492.14], EntityCow['Cow'/5545645, l='MpServer', x=462.07, y=72.00, z=1495.92], EntityZombie['Zombie'/5545384, l='MpServer', x=337.55, y=15.00, z=1502.77], EntitySpider['Spider'/5545385, l='MpServer', x=350.70, y=65.00, z=1488.70], EntityZombie['Zombie'/5545386, l='MpServer', x=323.50, y=14.00, z=1514.50], EntityZombie['Zombie'/5545387, l='MpServer', x=321.48, y=16.00, z=1516.17]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6142234480 bytes (5857 MB) / 11140071424 bytes (10624 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                      | Source                                                         | Signature                                |
	|:------ |:-------------------- |:---------------------------- |:-------------------------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft            | 1.12.2                       | minecraft.jar                                                  | None                                     |
	| UCHIJA | mcp                  | 9.42                         | minecraft.jar                                                  | None                                     |
	| UCHIJA | FML                  | 8.0.99.99                    | forge-1.12.2-14.23.5.2768.jar                                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                | 14.23.5.2768                 | forge-1.12.2-14.23.5.2768.jar                                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | applecore            | 3.1.4                        | AppleCore-mc1.12.2-3.1.4.jar                                   | None                                     |
	| UCHIJA | jei                  | 4.13.1.225                   | jei_1.12.2-4.13.1.225.jar                                      | None                                     |
	| UCHIJA | appleskin            | 1.0.9                        | AppleSkin-mc1.12-1.0.9.jar                                     | None                                     |
	| UCHIJA | baubles              | 1.5.2                        | Baubles-1.12-1.5.2.jar                                         | None                                     |
	| UCHIJA | bibliocraft          | 2.4.5                        | BiblioCraft[v2.4.5][MC1.12.2].jar                              | None                                     |
	| UCHIJA | biomesoplenty        | 7.0.1.2419                   | BiomesOPlenty-1.12.2-7.0.1.2419-universal.jar                  | None                                     |
	| UCHIJA | bonsaitrees          | 1.1.2                        | bonsaitrees-1.1.2-b144.jar                                     | None                                     |
	| UCHIJA | ctm                  | MC1.12.2-0.3.3.22            | CTM-MC1.12.2-0.3.3.22.jar                                      | None                                     |
	| UCHIJA | chisel               | MC1.12.2-0.2.1.35            | Chisel-MC1.12.2-0.2.1.35.jar                                   | None                                     |
	| UCHIJA | chiselsandbits       | 14.30                        | chiselsandbits-14.30.jar                                       | None                                     |
	| UCHIJA | redstoneflux         | 2.1.0                        | RedstoneFlux-1.12-2.1.0.6-universal.jar                        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | cofhcore             | 4.6.2                        | CoFHCore-1.12.2-4.6.2.25-universal.jar                         | None                                     |
	| UCHIJA | cofhworld            | 1.3.0                        | CoFHWorld-1.12.2-1.3.0.6-universal.jar                         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | mantle               | 1.12-1.3.3.39                | Mantle-1.12-1.3.3.39.jar                                       | None                                     |
	| UCHIJA | tconstruct           | 1.12.2-2.12.0.115            | TConstruct-1.12.2-2.12.0.115.jar                               | None                                     |
	| UCHIJA | conarm               | 1.2.3                        | conarm-1.12.2-1.2.3.jar                                        | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJA | conquest             | 3.0.2                        | ConquestReforged-3.0.2-mc1.12.2.jar                            | None                                     |
	| UCHIJA | blockpalette         | 1.5.0                        | ConquestReforged-3.0.2-mc1.12.2.jar                            | None                                     |
	| UCHIJA | connect              | 1.0.3-mc1.12.2-SNAPSHOT      | ConquestReforged-3.0.2-mc1.12.2.jar                            | None                                     |
	| UCHIJA | cookingforblockheads | 6.4.69                       | CookingForBlockheads_1.12.2-6.4.69.jar                         | None                                     |
	| UCHIJA | customspawner        | 3.11.4                       | CustomMobSpawner-3.11.4.jar.zip                                | None                                     |
	| UCHIJA | disenchanter         | 1.6                          | disenchanter-1.121.6.jar                                       | None                                     |
	| UCHIJA | mocreatures          | 12.0.5                       | DrZharks_MoCreatures_Mod-12.0.5.jar.zip                        | None                                     |
	| UCHIJA | extrabitmanipulation | 1.12.2-3.4.1                 | ExtraBitManipulation-1.12.2-3.4.1.jar                          | None                                     |
	| UCHIJA | fastleafdecay        | v14                          | FastLeafDecay-v14.jar                                          | None                                     |
	| UCHIJA | giacomos_fishing_net | 1.6.1                        | GiacomosFishingNet-1.12.2-1.6.1.jar                            | None                                     |
	| UCHIJA | astikoor             | 1.1.1                        | Horse-Carts-Mod-1.12.2.jar                                     | None                                     |
	| UCHIJA | improvedbackpacks    | 1.12.2-1.4.0.0               | ImprovedBackpacks-1.12.2-1.4.0.0.jar                           | None                                     |
	| UCHIJA | jjraces              | 1.0.7                        | JJ+Races+1.12-1.12.2-v1.0.7.jar                                | None                                     |
	| UCHIJA | mcmultipart          | 2.5.3                        | MCMultiPart-2.5.3.jar                                          | None                                     |
	| UCHIJA | millenaire           | Millénaire 7.1.1             | millenaire-7.1.1.jar                                           | None                                     |
	| UCHIJA | movinglightsource    | 1.0.15                       | movinglightsource-1.12.2-1.0.15.jar                            | None                                     |
	| UCHIJA | netherportalfix      | 5.3.17                       | NetherPortalFix_1.12.1-5.3.17.jar                              | None                                     |
	| UCHIJA | notenoughscaffold    | 1.8                          | NotEnoughScaffold-1.12.2-1.8.jar                               | None                                     |
	| UCHIJA | harvestcraft         | 1.12.2zb                     | Pam_s+HarvestCraft+1.12.2zb.jar                                | None                                     |
	| UCHIJA | roguelike            | 1.8.0                        | RoguelikeDungeons-1.12.2-1.8.0.jar                             | None                                     |
	| UCHIJA | solcarrot            | 1.3.1                        | solcarrot-1.12.2-1.3.3.jar                                     | None                                     |
	| UCHIJA | soulshardsrespawn    | 1.12.2-1.1.0-12              | SoulShardsRespawn-1.12.2-1.1.0-12.jar                          | None                                     |
	| UCHIJA | spartanshields       | 1.4.1                        | SpartanShields-1.12.2-1.4.1.jar                                | None                                     |
	| UCHIJA | spiceoflife          | 1.3.12                       | SpiceOfLife-mc1.12-1.3.12.jar                                  | None                                     |
	| UCHIJA | thermalfoundation    | 2.6.2                        | ThermalFoundation-1.12.2-2.6.2.26-universal.jar                | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | tinkertoolleveling   | 1.12.2-1.1.0.DEV.b23e769     | TinkerToolLeveling-1.12.2-1.1.0.jar                            | None                                     |
	| UCHIJA | treechopper          | 1.2.4                        | TreeChopper-1.12.2-1.2.4.jar                                   | None                                     |
	| UCHIJA | waystones            | 4.0.67                       | Waystones_1.12.2-4.0.67.jar                                    | None                                     |
	| UCHIJA | worldedit            | 6.1.8                        | WorldEdit-1.12.jar                                             | None                                     |
	| UCHIJA | worldeditcuife2      | 2.2.0-mf-1.12.2-14.23.5.2768 | WorldEdit+CUI+Forge+Edition+2-2.2.0-mf-1.12.2-14.23.5.2768.jar | None                                     |

	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  squeek.applecore.asm.TransformerModuleHandler
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.82' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.82, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: millenaire-hd-1.0.3.zip, 1-12-dokucraft-chisel-1522964655.zip, LGs_JohnSmith_Remix.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 16
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.17 Extreme-Volumetric Lighting.zip
	OpenGlVersion: 4.6.0 NVIDIA 398.82
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by RyanJM93** [comment]
This is on a minecraft server. Happens randomly to different players when a chunk containing the oven gets ticked. Temporary solution has been to have someone else currently unaffected break the oven in question, then the affected player can rejoin server. Else, game crashes on server join. Has affected multiple people at same time, with same oven entity being the problem.

**Comment by BlayTheNinth** [comment]
How frequently does this happen and what other blocks are nearby? Do you use Sponge?

**Comment by RyanJM93** [comment]
Just saw your comment. It happens when the chunk hasn't been visited for a while and has to reload. Not that often, but game breaking, when it does happen. I don't use Sponge.
