### ISSUE TITLE
Ice Unit doesn't appear to be working

### ISSUE THREAD

**Issue by scotty9090** [blay09/CookingForBlockheads#365]
If I understand the upgrade correctly, and remember from past experience, the upgrade should be providing the frozen ingredients (snowballs) for Pam's Smoothies.  However, I'm not seeing the recipe show up in the cooking table when I have all the required ingredients except the snowballs.  I have to physically add snowballs to the fridge - which shouldn't be necessary with the upgrade?

Running version: 1.12.2-6.4.69

**Comment by BlayTheNinth** [comment]
Duplicate #335
