### ISSUE TITLE
Support custom fluid to item mappings, e.g. goat milk to goat cheese

### ISSUE THREAD

**Issue by Graywaren** [blay09/CookingForBlockheads#367]
I'm really loving CFB and especially it's ability to work with storage drawers and mod ingredients. However, it seems that mod milks won't be accepted into the milk jar. I can't find a config for this and while there is a compatibility config folder, I can't find any documentation on how to write something for it. (I did find someone who'd written compatibility for mod ingredients that now just work automatically, but I can't find info on how to use it in general... maybe I missed it.) I'd really like to attach the milk jar via pipes etc. to my dairy farm that provides different milks for different items (animania for example). Is there any way to do this? If not, would love to see this compatibility added.

**Comment by BlayTheNinth** [comment]
What mod is adding the milk fluid?

**Comment by Graywaren** [comment]
Animania and better animals plus are the two I have. There’s about 7 types between them: 4 cow, one sheep, 2 goat, I think.

**Comment by BlayTheNinth** [comment]
Currently, only non-specialized milk (as in that which would be equivalent to Vanilla's milk bucket) is supported. I may be opening this up for better compatibility in the port to Minecraft 1.13, right now it'd require too many changes to existing compat files.

**Comment by Graywaren** [comment]
Understandable. Would it be possible/easier to make the multiblock structure compatible with fluid tanks? Such as the tank from Open Blocks.. the way that storage drawers work. That way I could put milk tanks into the structure itself rather than going through the milk jar. CFB already recognizes when I have a bucket of those mod's milk in my inventory, so maybe there would be a way it could pull the milk from a tank inventory? Not sure if that's easier to implement than the milk jar though, but it would be super convenient for large quantities of milk from an automated farm.

**Comment by BlayTheNinth** [comment]
That would not help in this case since the part that's needed isn't the fluid storage, but rather the mapping of fluids to their item counterparts. Additionally merging other fluid tanks into the multiblock is a different story, and while I may create a compat entrypoint for it, I don't think I'll add any official integrations, since people have already been running into performance problems with just the Storage Drawers integration.

**Comment by BlayTheNinth** [comment]
What are these other milks used for? I saw Goat Cheese. Is there anything else? Thinking it might be easier after all to just allow a simple connect-tank-to-bucket compat than mess with the milk jar, especially if there's only such limited use for them.

**Comment by Graywaren** [comment]
Hi! They're basically just used for various cheeses and equivalents to the vanilla milk. There's not much else they do that I know of.

**Comment by BlayTheNinth** [comment]
Closing this since more extensible fluid support is planned for the new API via #673
