### ISSUE TITLE
Client booted from server when clicking recipe from #nofilter Book

### ISSUE THREAD

**Issue by katubug** [blay09/CookingForBlockheads#368]
We're playing CookingForBlockheads_1.12.2-6.4.70 on MC 1.12.2, forge version 12.23.5.2825 and experiencing a very specific crash.

When using the No Filter Cooking Book, and clicking on the recipe for Cheese, it kicks the client off of our server. It happened to a player and I can replicate it.

Let me know if you need any other information!

**Comment by BlayTheNinth** [comment]
I need the log sections from client and server at the time the disconnect happens. Which mod is the cheese recipe from?

Possibly related to #355

**Comment by katubug** [comment]
The cheese is from Pam's Harvestcraft. Here are the logs:

Server: https://hastebin.com/finavaloho.md

Client: https://hastebin.com/epeyuyuhox.md

**Comment by BlayTheNinth** [comment]
The pastes have expired now, but I assume I looked at them back then and couldn't immediately figure out what was causing it. Is this issue still happening, and what other mods are installed?

**Comment by katubug** [comment]
I just went to test it, and it seems that it's no longer occurring, although perhaps I'm unable to test it correctly due to cheese being uncraftable? But that bug is already address here: https://github.com/blay09/CookingForBlockheads/issues/382

Also, my apologies for not including important diagnostic information. I had only just started this modpack business and didn't know what I was doing yet!
