### ISSUE TITLE
Can't Load My World :( (Crash)

### ISSUE THREAD

**Issue by KenyMylankca** [blay09/CookingForBlockheads#371]
[crash-2019-05-03_22.56.49-server.txt](https://github.com/blay09/CookingForBlockheads/files/3143390/crash-2019-05-03_22.56.49-server.txt)
i just doesn't let me load my world :(

**Comment by BlayTheNinth** [comment]
It looks like some mod is adding or removing furnace recipes from a different thread. Do you know of any mods you have installed that are doing changes to the furnace recipes?

**Comment by KenyMylankca** [comment]
it's cooking for blockheads i think. **if not**, it's IGCM from CreativeMD i'm %100 sure.

**Comment by BlayTheNinth** [comment]
Cooking for Blockheads does not change any recipes, it's only trying to read them at the same time as some other mod is trying to change them, which caused the crash.

**Comment by KenyMylankca** [comment]
yeah @CreativeMD should take a look, i think...

**Comment by CreativeMD** [comment]
Yeah IGCM changes the recipe list every time somebody changes the configuration. @KenyMylankca if you don't this feature anyway you can disable it in the config file (make sure to disable it on client and server).

**Comment by KenyMylankca** [comment]
uhm, i'm using it actually, i tweak recipies with IGCM... :/

**Comment by CreativeMD** [comment]
Also furnace recipes (you can disable that separately).

**Comment by KenyMylankca** [comment]
oh i will do that so.
B:enableFurnace=false
by this way, right?

**Comment by CreativeMD** [comment]
Yes and make sure to disable it on the server as well (if you are using a server).

**Comment by KenyMylankca** [comment]
thanks a lot. i disabled it.

**Comment by BlayTheNinth** [comment]
If it's confirmed to be IGCM changing the smelting recipes outside the main thread I think it's worth investigating why (though looking at the code I couldn't find any immediate problems that could be causing this).

**Comment by CreativeMD** [comment]
Actually, not outside the main thread (if I'm not mistaken).
