### ISSUE TITLE
MrCrayfish's Furniture Mod integration and support

### ISSUE THREAD

**Issue by DWX12** [blay09/CookingForBlockheads#373]
Saw an old closed issue regarding this topic and figured I'd bring it up again. There's alot that his furniture mod adds in and would like to see some integration and support for it. As it stands, there's a fridge, oven, blender, microwave along with several blocks with inventories.

Always kind of sucks when I have to choose among different mods when making a kitchen and end up having to choose CfB because of the whole multi-block thing. Although the mixed styles of mods don't always look all that great, lol.

Hope to see more mod integration in the future with others.

Thanks so much for this awesome mod.

**Comment by BlayTheNinth** [comment]
Previous issue for my own reference: #115 was closed because the furniture mod hadn't been updated, but it's now available for 1.14.4. Will have to look into the mod to see what it actually adds that needs to be considered.

**Comment by djmattyg007** [comment]
Just wanted to voice my support in favour of adding compatibility with the cooler from McCrayfish's Furniture mod. It would be fantastic.

**Comment by BlayTheNinth** [comment]
Not sure when it was added but there already is support for CFM
