### ISSUE TITLE
Cooking oven doesn't display energy inside

### ISSUE THREAD

**Issue by ArtOfCombat** [blay09/CookingForBlockheads#380]
With the heating unit upgrade installed, the oven's GUI does not display how much energy it has. WAILA or TOP does display, however.

**Comment by BlayTheNinth** [comment]
I didn't add an energy bar because I didn't see an immediate need for one. The oven is not a "battery" after all. I think since pretty much everyone has either WAILA or TOP installed, that's good enough.

**Comment by ArtOfCombat** [comment]
The issue was that wth TOP it didn't display energy levels - didn't pass them to the display mod.

**Comment by BlayTheNinth** [comment]
Sorry, I don't understand. What display mod?

**Comment by ArtOfCombat** [comment]
That One Probe.

**Comment by ElvenChaos** [comment]
For me the upgraded oven does have an energy bar, but it will always show "Energy stored: 0/10000" despite it actually having energy. To verify that the information the interface was giving me was misleading, I had to go turn the energy module of waila on when I previously had it off. I cam here originally thinking that it was just not getting power.

**Comment by BlayTheNinth** [comment]
TIL I added an energy bar and forgot about it

**Comment by BlayTheNinth** [comment]
Energy showing fine for me on both single- and multiplayer.

![image](https://user-images.githubusercontent.com/1933180/72634462-f21c4400-395a-11ea-90ff-836170e542ba.png)
