### ISSUE TITLE
Opening #NoFilter edition causes client to disconnect

### ISSUE THREAD

**Issue by iamweirdie** [blay09/CookingForBlockheads#383]
Hi, when i open the #nofilter cookbook in my modpack, server OR singleplayer, i get booted
[i wouldnt know which line.txt](https://github.com/blay09/CookingForBlockheads/files/3365065/i.wouldnt.know.which.line.txt)

for reference, here's the modpack
https://kreezcraft.com/2019/07/01/wod-hell-1-2-3/

**Comment by BlayTheNinth** [comment]
There's too many food items being sent to the client. Should 1) check if there is actually that many foods, or if there's something wrong with the detection and 2) split the packets into multiple if necessary.

**Comment by iamweirdie** [comment]
sorry, i should've mentioned when i found it, the issue was cuisine mod
https://www.curseforge.com/minecraft/mc-mods/cuisine

if you understand how the mod works, it's VERY obvious where all the recipe issues stem from.
