### ISSUE TITLE
Wall Cabinets not detected by multiblock kitchen.

### ISSUE THREAD

**Issue by brisingraerowing** [blay09/CookingForBlockheads#386]
As per title. Wall cabinets are not detected by a multiblock kitchen.

Cabinet containing bread:
![2019-07-26_23 00 45](https://user-images.githubusercontent.com/250409/61989177-6d7ae980-aff9-11e9-8f3f-594b922213ee.png)

Bread shown as not available:
![2019-07-26_23 01 01](https://user-images.githubusercontent.com/250409/61989182-7b306f00-aff9-11e9-926c-432a77721c71.png)

**Comment by BlayTheNinth** [comment]
Probably same issue as #382

**Comment by BlayTheNinth** [comment]
Closing as duplicate to #382
