### ISSUE TITLE
Workbench functionality on placed cutting board

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/CookingForBlockheads#387]
From CurseForge:
> So ive got a strange question. One of my favorite parts of harvest craft was that the cutting board worked like a workbench but for foods, is there any way to make this placeable cutting board act like the old one? 

> i have no clue why they removed that feature from harvest craft. I like still having to manually put my food recipes together but i dont want a workbench sitting in my kitchen. Maybe theres a way to make the cutting board act like a crafting table so i can still access manual recipes without needing a workbench?

**Comment by HalJordan** [comment]
This sounds more like something to send Harvestcraft's way. This mod uses that cuttingboard, it doesn't add it's own, or modify any of harvestcraft in anyway. It's merely a companion that allows for easy cooking without needing a full inventory.

**Comment by BlayTheNinth** [comment]
Cooking for Blockheads does add a placeable version of the cutting board, which is what the feature request refers to. It can only be placed using the Pam's cutting board, but the actual block is implemented on CFB side.
