### ISSUE TITLE
Cooking table can detect inventory of Cooking Oven

### ISSUE THREAD

**Issue by bakaxyf** [blay09/CookingForBlockheads#39]
![image](https://cloud.githubusercontent.com/assets/10368307/9257536/a78bd29e-4228-11e5-89f5-a0088c3ea94d.png)
![image](https://cloud.githubusercontent.com/assets/10368307/9257509/7c7bf2be-4228-11e5-9aba-aa665c3b5df3.png)
![image](https://cloud.githubusercontent.com/assets/10368307/9257521/8fdadf0a-4228-11e5-8165-aec185018131.png)

**Comment by blay09** [comment]
That's kind of intended, but I guess I need to make it so it only reads the output slots.

**Comment by blay09** [comment]
Will be fixed by #43.

**Comment by blay09** [comment]
Fixed in version 1.0.92+
