### ISSUE TITLE
Add support for Thermal Foundation's Redstone Furnace

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/CookingForBlockheads#390]

**Comment by Krougal** [comment]
Yes! Or an upgrade for your oven to be competitive with the Trivection chamber at least.
I'm a huge TF fanboy but I have to admit, your oven is way cooler.

**Comment by Zero9o1o** [comment]
I don't like the idea of trying to be competitive with mods like TF. But the idea of support for the redstone furnace is weird... Cause other then trying to be better then it I can't think of what there is to add for support?

**Comment by Krougal** [comment]
> I don't like the idea of trying to be competitive with mods like TF. But the idea of support for the redstone furnace is weird... Cause other then trying to be better then it I can't think of what there is to add for support?

When I say be competetive, I mean if I've got both options available, because I'm going to go with the more efficient. Just like the RF upgrade for the oven allows it to be competetive in an environment that includes RF powered furnaces. The big thing the oven has going for it is the cool factor (that and storing Pam's tools). I use it, but I cook the meat in a Trivection chamber furnace and pipe it in.

**Comment by incomingnerd** [comment]
Wading in with my own left-field opinions here, but it always bemused me that the kitchen multiblock interacts with one or two other mods (like Storage Drawers) while ignoring other mods with similar functionality. What follows is just me spitballing ideas.

In the case of the Redstone Furnace, for example, perhaps it would be more intuitive to interact with any tile entity that claims to cook food (perhaps using a whitelist/blacklist config entry)? I'd maybe blacklist the vanilla furnace by default, to encourage building the Blockheads oven instead.

Of course, this would still not support more exotic cooking mechanisms like a Create lava fan/belt setup. An alternative, therefore, might be to introduce an "external furnace" tile entity which pushes uncooked food to an adjacent inventory and assumes it can pull the cooked result some time later. I could see this block being crafted from the floor tile block, yielding a floor tile with a furnace icon on one face. The player could place down a normal tile floor with an "external furnace" tile somewhere in it, place a furnace item from some other mod on top of the "external furnace" tile and have it seamlessly integrate with the kitchen, no config required.

Generalizing the idea of the "external furnace" floor tile, an "external storage" tile (floor tile with a chest icon on) could add inventory interaction with whatever storage system you wanted (not just Storage Drawers), while making it much more obvious that the kitchen will attempt to interact with a given block. Likewise, while Harvestcraft appears to have removed the Grinder and Presser for the time being, support for these external machines (or ones with similar functionality) could again be added with custom floor tiles.

Do what you will with these ideas - they may well be terrible.
