### ISSUE TITLE
You need multiple milk jars

### ISSUE THREAD

**Issue by Zero9o1o** [blay09/CookingForBlockheads#391]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2838
Mod Version:6.4.71

What is wrong: To make cake you need 3000mb of milk, but you need to have 2 jars in your kitchen and they both need to have at minimum 1000mb of milk

What you expected to happen:Only needing 1 jar that has 3000mb of milk in it.

Additional notes:

**Comment by katubug** [comment]
I can replicate this. Cake doesn't show up in the Cooking Table unless two Cow in a Jars are present in the multiblock. I have all the same versions as the OP.

**Comment by Krougal** [comment]
I know this isn't really the issue here, but how about an industrial milker? (maybe something more for Farming for Blockheads though)

**Comment by Rixxaw** [comment]
Same problem with XLFoods Mod, Cheese takes 6 Milk buckets... (Thats the only ingredients)  I put 8 empty buckets in the Fridge, and had a Full Cow, but it wouldn't make it.  So I added 3 more Cows in a jar, and even with 4 cows full it wont' craft.  Unless I tossed 2 full buckets of milk into the fridge.  I suppose I need to go get 2 more cow jars to make it work.
