### ISSUE TITLE
Cooking Table + Preservation Chamber Issue

### ISSUE THREAD

**Issue by imakunee** [blay09/CookingForBlockheads#392]
Cooking For Blockheads 6.4.71

### Description of Issue

When using the Cooking Table to create a recipe with multiple possible ingredients (in this instance, Stock from Pam's Harvestcraft) and the ingredients are in a Fridge upgraded with the Preservation Chamber, the Cooking Table consistently tries to use a single recipe due to the Preservation Chamber keeping the  ingredient technically available. This stops all ability to craft using a different ingredient than the first one unless you wait for the recipe preview window to reach the ingredient you want to use. However, upon crafting said recipe, the recipe preview window returns to the first ingredient which you can't craft with as it's protected by the Preservation Chamber, forcing you to wait until the recipe preview window returns to the ingredient you want to use. Naturally this eliminates the usefulness of the Cooking Table as it's intended as it's faster to create your recipe by handling the ingredients yourself in a typical crafting table.

For example, the Stock recipe can use Bamboo or Carrots. There is only one Bamboo in the Fridge upgraded with a Preservation Chamber and there are 64 Carrots. The Cooking Table first shows the recipe for Stock that uses a Pot and Bamboo. Attempting to craft that recipe provides no result. Waiting several seconds the Cooking Table shows the recipe for Stock that uses a Pot and a Carrot. Attempting to craft uses one Carrot and provides three Stock as expected and the Cooking Table recipe preview window returns to the recipe for Stock that uses a Pot and a Bamboo. Immediately attempting to craft Stock again provides no result as the Cooking Table is attempting to craft Stock using Bamboo.

### Expected Outcome

The Preservation Chamber causes the Cooking Table to act as if any item in an upgraded Fridge that is the last item of its type (Carrot, Bamboo, etc.) does not exist.

### ---
Thank you so much for your work on this mod. It's a must have whenever I'm playing modded Minecraft for both its look and functionality.

**Comment by BlayTheNinth** [comment]
You should be able to scroll through the ore-dict items using the mousewheel and you can click to lock it. Still marking it as bug though since it shouldn't show up as oredict option when it's the last of its kind.
