### ISSUE TITLE
Add a Deep Freeze set.

### ISSUE THREAD

**Issue by Neko-Jess** [blay09/CookingForBlockheads#393]
A Deep Freeze block set would be really interesting i think. It could be used for storing raw fish and meats. Google "Lay Down Deep Freeze" and check images for the basic design. I can link a proper picture to you in discord if you so desire for the design I mean, but simply turning the current two block tall fridge on its back long ways with the door opening upwards is the best and easiest solution for now. Of course, I think it should accept the preservation upgrade.

**Comment by Neko-Jess** [comment]
Addendum: Seeing as it would legit just be a big freezer block set,, I think it should hold more than the fridge by a little bit for that extra added meats and fish storage capability, but the freezer itself should not be stack-able or able to sit on counters/ hang on walls.

**Comment by BlayTheNinth** [comment]
What other functionality would this block offer other than slightly different looks and more storage space?

**Comment by Neko-Jess** [comment]
Maybe have it be a remote storage set that doesn't need to be a direct part of the kitchen? Something you can place within a certain range of other kitchen blocks and have a large storage capacity, more so than the double fridge? I'd say make it store only meats and fish to be honest cause it would work best as a meat locker type storage.

**Comment by katubug** [comment]
Personally, I'd like this just for the extra aesthetic. My kitchen looks a little weird with three and a half refrigerators, not gonna lie.
