### ISSUE TITLE
Concrete and the sink

### ISSUE THREAD

**Issue by Zero9o1o** [blay09/CookingForBlockheads#394]
Would be cool if when the sink has water and you click on it with concrete powder it turns the powder in to concrete blocks!

**Comment by katubug** [comment]
It's a cool idea, but personally I'd never think to use it, as it seems outside the scope of the mod.

**Comment by Ichirou-Tomoe** [comment]
I think this feature would be useful, but it's out of place in a kitchen, wich is the focus of your mod. I would rather see that in a machinery/automation oriented mod.
