### ISSUE TITLE
Scrolling down via mouse wheel causes clicks in gui.

### ISSUE THREAD

**Issue by grundyboy34** [blay09/CookingForBlockheads#396]
[Mod Version - 1.12.2-6.4.71]
As stated, using the mouse wheel to scroll down in the cooking table causes clicks to be made, often crafting and queuing things in the oven unintentionally.
Scrolling up doesn't have this effect.

**Comment by Neko-Jess** [comment]
Weird. You're able to do so in the crafting grid for a recipe to switch between ingredients you want to use for a recipe should it have multiple choices for a required ingredient... never had this happen though.

**Comment by grundyboy34** [comment]
Yeah it's pretty weird. I have a bit of mods, but I eouldn't think any of them would cause it. Anyway, I'll try to reproduce it without them when I have time.

**Comment by Neko-Jess** [comment]
Try checking your mouse tweak settings. Blay said "Mouse tweaks or something does that".

**Comment by BlayTheNinth** [comment]
Many years ago there was a similar issue with Mouse Tweaks that happened on scrolling down: #46 

It may have returned, or there is some other mod doing mouse-y things now. Do you have Mouse Tweaks installed and does it still happen if the wheel tweaks are disabled?

**Comment by grundyboy34** [comment]
I haven't gotten to test  yet but I can say I don't have mouse tweaks. The only mod I can think of that tweaks the gui in my pack is Quark. Here's a link to my pack on curseforge, and it has every mod listed on there if that helps anyone.   https://www.curseforge.com/minecraft/modpacks/slightly-spicy/files/2774584

**Comment by BlayTheNinth** [comment]
Closing since 1.12 is no longer supported, if this still happens in 1.15+ please open a new issue.
