### ISSUE TITLE
Any news for 1.14.4?

### ISSUE THREAD

**Issue by Bvioto** [blay09/CookingForBlockheads#398]
I want to use this mod on 1.14.4 version. I'm just wondering if there is any update on this mod?

**Comment by BlayTheNinth** [comment]
In progress but no ETA.

**Comment by Bvioto** [comment]
Ohhh :c thanks anyways. I love this mod and I really want to use it with XL Food mod, snif.

**Comment by BlayTheNinth** [comment]
Closing as progress is tracked in #395
