### ISSUE TITLE
quite slow response using the cooking table

### ISSUE THREAD

**Issue by wallasaurus** [blay09/CookingForBlockheads#400]
opening cooking table doesn't show ingredients for a few seconds, and when clicking recipes there is a similar delay between each one being created.

This is in enigmatica 2 (not expert) 1.71a version.  Is this a known issue or something I am doing wrong as a user?  I'm happy to try to fix but I do not know where to begin.

Thanks for any assistance,

**Comment by BlayTheNinth** [comment]
Enigmatica 2 is a huge pack from what I remember so I wouldn't be surprised if there's huge amounts of food recipes needing to be checked. Maybe there's some that can be safely ignored by Cooking for Blockheads too.

Moving all performance related issues to here: #346

**Comment by BlayTheNinth** [comment]
One more thing, was this on a server (and if so, with Sponge?) or singleplayer?

**Comment by wallasaurus** [comment]
This was on a server and I don’t see sponge in the mod list.  You’re right it’s a big old pack, I just didn’t experience this issue on a different modpack which was also pretty large so I figured I would log it.  😊

 

The server is running enigmatica 2  1.71 version, if it is of any help.
