### ISSUE TITLE
Dyeable Oven

### ISSUE THREAD

**Issue by JasonKillsUs** [blay09/CookingForBlockheads#401]
It would be nice if the cooking stove would be dye-able, just saying, may a for a future version

**Comment by Skydragonsz** [comment]
He is already working of that.
See #395 for more info!

**Comment by fallenhunter1** [comment]
As the fridge is already thus, why not the oven too.. heck, would love to see the cabinets dye-able.

**Comment by BlayTheNinth** [comment]
Dyed oven textures created by Mezimaru from Discord for future use

[Oven Textures.zip](https://github.com/TwelveIterationMods/CookingForBlockheads/files/13589465/Oven.Textures.zip)
