### ISSUE TITLE
Weird Bug with crafttweaker (1.14)

### ISSUE THREAD

**Issue by BedrockLegends** [blay09/CookingForBlockheads#407]
Might have find a weird bug with crafttweaker, when I go and make a custom recipe for Cooking for Blockheads Kitchen floor and use craft tweaker to removed the old recipes to just use my custom recipe, The custom recipe does not show up at all

**Comment by Zero9o1o** [comment]
I got it to work.
Minecraft version: 1.14.4
Forge Version: forge-28.1.87
CookingForBlockheads Version: 7.4.0
Crafttweaker version: 5.0.1.130

syntax in 1.14.x for crafttweaker seemed to changed a bit
Gist of working crafttweaker script.
[Gist link](https://gist.github.com/Zero9o1o/9120849398465be7555bec58c14796f4)

**Comment by BedrockLegends** [comment]
@Zero9o1o 

https://gist.github.com/BedrockLegends/b605fa7fdcf111c0421fbe73d9547bcd

https://gist.github.com/BedrockLegends/fe024a82657bdfebf54c83096e7c0d90

**Comment by Zero9o1o** [comment]
Your removal script is being ran after your custom recipe script. add "##_" before your scripts. (example: 00_removed.zs)

**Comment by jaredlll08** [comment]
Do not add `##_` to your scripts, if you truly want something to run before something else, use `#priority <number>`, different file systems read files differently in different orders.
