### ISSUE TITLE
[1.14.4] Bread to Toaster = Diamond

### ISSUE THREAD

**Issue by Crissaegrem** [blay09/CookingForBlockheads#409]
When i put the bread on the toaster and wait for few seconds, the outcome is a diamond.

**Comment by BlayTheNinth** [comment]
![image](https://user-images.githubusercontent.com/1933180/69008744-57998780-094e-11ea-8b8c-ba976f1ffd91.png)

\>_>

**Comment by Skydragonsz** [comment]
Always fun when the dev forgets to remove his test code

**Comment by Crissaegrem** [comment]
Ahahaha // You've forgotten me

Thanks for the mod 😄
