### ISSUE TITLE
French language file submit

### ISSUE THREAD

**Issue by Ichirou-Tomoe** [blay09/CookingForBlockheads#410]
I've made the french translation of the language file. This is my native language and I checked with an integrated kitchen vendor to make sure I was using the right terms and not what little idiom remain, so it should be accurate.

[fr_fr.zip](https://github.com/blay09/CookingForBlockheads/files/3855826/fr_fr.zip)

**Comment by Skydragonsz** [comment]
It's better to make a pull request (and easier for the developer).

**Comment by Ichirou-Tomoe** [comment]
Oh, I see, thank you. This is my first actual contribution aside from raising issues, so now I've looked up the documentation to do this properly.
It'is now in pull request 411.

**Comment by BlayTheNinth** [comment]
Thanks.
