### ISSUE TITLE
[Suggestion] Recursive crafting

### ISSUE THREAD

**Issue by Krougal** [blay09/CookingForBlockheads#412]
For the more complex recipes (Pams) it would be really useful to show not just what can be made from what we have on-hand, but also if we processed some of those into sub-comps (flour, condiments, etc). I was honestly ready to ditch Pams before this mod came along.

I can see that is could potentially be a severe performance hit in which case, forget I mentioned it.

**Comment by Skydragonsz** [comment]
Duplicate of #112

**Comment by Krougal** [comment]
> Duplicate of #112

Oh, cool. Thanks.
