### ISSUE TITLE
Allow Blocks to be Waterlogged

### ISSUE THREAD

**Issue by WenXin20** [blay09/CookingForBlockheads#413]
`Minecraft v1.14.4`

Currently, kitchen blocks cannot be waterlogged, which could be a nice enhancement.

**Comment by Zero9o1o** [comment]
To me it would feel odd for the counters, fridges, and appliances to be waterlogged. If CfB added stairs, walls, and/or fences then I would say it might fit.

**Comment by WenXin20** [comment]
To me, I think any non-full block should be waterloggable, it just would seem odd that if a glass jar was placed underwater that water would just magically flow around it.

**Comment by Zero9o1o** [comment]
Currently in vanilla there are non-full blocks like the anvils and the enchantment table can't be waterlogged. So like it doesn't seem that odd from a vanilla stand point

**Comment by WenXin20** [comment]
Although there's also the chest, scaffolding, and even the campfire that can be waterlogged.

**Comment by BedrockLegends** [comment]
I think this would be great in 1.14 and above as having Waterlogged blocks would help with say people dropping things in water by mistake

**Comment by JonesiBlitz** [comment]
Would be an interesting choice, with conduits making underwater breathing a thing, could have a fully submerged base. The more you can waterlog the cooler the base design could be. Although its an edge case, not sure how many build underwater.
