### ISSUE TITLE
[1.14] Crash on Startup (NullPointerException in BlockColors)

### ISSUE THREAD

**Issue by SDUBZ** [blay09/CookingForBlockheads#419]
FORGE : [28.1.106]
CFBH: [1.14.4-7.4.0]

crash report:
[crash-2019-12-15_03.00.27-client.txt](https://github.com/blay09/CookingForBlockheads/files/3964016/crash-2019-12-15_03.00.27-client.txt)
Logs:
[latest.log](https://github.com/blay09/CookingForBlockheads/files/3964017/latest.log)

**Comment by BlayTheNinth** [comment]
There is two silent rftoolsutility and rftoolsbuilder crashes in the latest.log that are causing the event bus to shutdown, which results in the followup crash in CFB.

**Comment by bigdudeandy** [comment]
i was getting the same crash figured out it was dank storage causing it for me hope this helps you guys
