### ISSUE TITLE
[Suggestion] Applied Energistics 2 Mod integration and support

### ISSUE THREAD

**Issue by yakumoringo** [blay09/CookingForBlockheads#423]
It would be nice if ME storage bus(AE2) could connect with cooking table(CFB).Than I can access my kitchen through the ME channel much more easier.（My English is not good XD）

**Comment by Skydragonsz** [comment]
There will be never support for AE.
See https://github.com/blay09/CookingForBlockheads/issues/109#issuecomment-217606522

**Comment by BlayTheNinth** [comment]
Correct. Someone has tried to add support, but the caching (similar to the Storage Drawer Controller) makes it difficult to use it the way Cooking for Blockheads would need to. Also I would much rather like to improve the existing storage capabilities in Cooking for Blockheads to make hooking up the kitchen to a magical digital storage thing unnecessary.
