### ISSUE TITLE
Recipe books don't show not-edible food ingredient recipes

### ISSUE THREAD

**Issue by InspectorCaracal** [blay09/CookingForBlockheads#426]
~~The cooking table doesn't show any of the not-edible ingredient recipes from the simplefarming mod, despite the compat json file including those items. Is there something else that needs to be done besides the json file that got added?

I tried changing the json file's contents and nothing changed, so I don't think it's affecting anything.~~

edit: I forgot to mention, I'm using mod version 7.4.4 for MC 1.14.4

edit2: This doesn't seem to be a simplefarming compatability issue, actually, as it doesn't show the recipe to make sugar anymore either and that's entirely vanilla minecraft. The recipe books and cooking table don't show the recipes to make any food ingredients that aren't themselves edible.

**Comment by BlayTheNinth** [comment]
This has been fixed in 1.15+.
