### ISSUE TITLE
[1.14.4-7.4.4] Network Bug (No Crash)

### ISSUE THREAD

**Issue by KittenKoder** [blay09/CookingForBlockheads#428]
I found this in the log, working on a modpack so that's something I watch closely:

[Client thread/WARN] [net.minecraft.client.network.play.ClientPlayNetHandler/]: Unknown custom packet identifier: cookingforblockheads:network

It was repeated a lot, hundreds of lines for less than one minute. I think it may also be linked to a performance issue I saw in the bug list. This was on single player, I have not tested it on a multiplayer server yet.

Due to this issue I cannot use the mod, even if it only occurs on single player because of needing to watch the log results every time I change the mods.

**Comment by BlayTheNinth** [comment]
The log spam has been fixed in 1.15.2+, but hundreds of lines of them does sound suspicious. I'll have to check if something is causing packets to be spammed. But unless any gamebreaking crashes show up or the problem turns out to be severe, this might not get backported to 1.14.

**Comment by BlayTheNinth** [comment]
Couldn't find anything suspicious with the amount of packets being sent. The related log spam is fixed in 1.15+.
