### ISSUE TITLE
1.12.2 - Cooking Table with NoFilter Book

### ISSUE THREAD

**Issue by TheCutter** [blay09/CookingForBlockheads#437]
Some ingredients (in my case salt) are shown es red (not available) when you click through the ingredients in the left matrix even though they are in the connected storage.
If you select a recipe from the right list which needs the item (in my case salt) it is shown as available in the left matrix.

**Comment by BlayTheNinth** [comment]
Are you on 6.5.0 or higher? This was fixed a while back and also can't be reproduced in 1.15+. However, 1.12.2 is also no longer supported.
