### ISSUE TITLE
1.12.2 - Crash when connecting sink with Buildcraft's heat exchanger

### ISSUE THREAD

**Issue by rickthetank** [blay09/CookingForBlockheads#438]
https://paste.dimdev.org/ocofopehiq.mccrash

The sink's water was piped out with Fluiducts and connected with the heat exhanger item, causing my game to crash.

**Comment by BlayTheNinth** [comment]
The site the crash log is posted on is unavailable.

**Comment by BlayTheNinth** [comment]
Closing since 1.12 is no longer supported and the crashlog no longer accessible, if this still happens in 1.15+ please open a new issue.
