### ISSUE TITLE
[Compatibility] Crash on start with Optiforge 1.15.2

### ISSUE THREAD

**Issue by ET1996** [blay09/CookingForBlockheads#439]
At first I tought it was Optiforge causing a crash, but they told me it was your mod causing a crash with it. Could you investigate the issue?
[crash-2020-04-17_15.59.00-client.txt](https://github.com/blay09/CookingForBlockheads/files/4496555/crash-2020-04-17_15.59.00-client.txt)

**Comment by BlayTheNinth** [comment]
Some other mod is crashing silently (earlier in the log) before the Cooking for Blockheads crash happened, causing initialization to fail. See #419

**Comment by ET1996** [comment]
Funny that when disabling only your mod and keeping everything else, everything works fine ¯\_(ツ)_/¯
All the mods including yours are compatible together if I do not include Optiforge. And Optiforge's owner points toward your mod causing the crash

**Comment by BlayTheNinth** [comment]
post your latest.log
