### ISSUE TITLE
Crash with latest version of Forge

### ISSUE THREAD

**Issue by RodrigoTaipe93** [blay09/CookingForBlockheads#440]
This happened with the latest version of Forge and the mod:

- https://paste.ee/p/Tsz1c

**Comment by BlayTheNinth** [comment]
See #419, there is a crash higher up in your latest.log, this is just a followup due to it not crashing correctly in an earlier loading stage.

**Comment by CarlosCS28** [comment]
Help me please
![2020-05-06_10 42 03](https://user-images.githubusercontent.com/64914242/81199074-cfed1700-8f87-11ea-9a34-0db9ebc70db7.png)
