### ISSUE TITLE
Remove weird sink activation success check

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/CookingForBlockheads#442]
No idea what it was added for since it's from a few million Minecraft versions ago, but apparently it's causing problems with fluid handlers that are also blocks

https://github.com/blay09/CookingForBlockheads/blob/1.15.x/src/main/java/net/blay09/mods/cookingforblockheads/block/SinkBlock.java#L102

**Comment by MuteTiefling** [comment]
Seems to be causing a dupe bug with pneumaticcraft.

https://github.com/TeamPneumatic/pnc-repressurized/issues/476
