### ISSUE TITLE
[1.15.2] Crash on Startup (NullPointerException in BlockColors) 

### ISSUE THREAD

**Issue by ghost** [blay09/CookingForBlockheads#443]
Love the mod! But ...

[crash-2020-05-08_21.19.09-client.txt](https://github.com/blay09/CookingForBlockheads/files/4602780/crash-2020-05-08_21.19.09-client.txt)

Found this ...

[https://github.com/blay09/CookingForBlockheads/issues/419](url)

... so I tried starting the game with just CookingForBlockheads & McJty's stuff = no crash. Same with only CookingForBlockheads & Mekanism present (no crash). Also no crashes with all the other mods loaded (if I remove CookingForBlockheads, that is).

If it's another mod causing the issue, could you please tell me which one it is? Any ideas?

**Comment by BlayTheNinth** [comment]
It could be any mod, you will have to look in your latest.log or post it here. There will be an exception that results in the EventBus being shutdown.

**Comment by ghost** [comment]
I was hoping to find the bad boy that's causing the trouble so I removed all mods except CookingForBlockheads and then tried it one on one with every single mod from my pack. No crashes at all. Then I added all mods again and now the crashes are gone. Weird but ... well, works - for now. Thanks for your assistance and keep up the good work!
