### ISSUE TITLE
[MC 1.15.2](CfB 8.0.2) Cow in a Jar not working

### ISSUE THREAD

**Issue by eplossl** [blay09/CookingForBlockheads#447]
My family has set up a server and we are trying to play with the Cow in a Jar.  While we have successfully gotten CfB to work and the Cow in a Jar created, we are finding that, when placed on a counter, (or anywhere else, for that matter) it doesn't seem to be picked up and usable.  If I have a bucket of milk in my inventory, I can create the CfB milk container(via the book in my hand or as part of a kitchen setup), but if I try to do the same thing with just the Cow in a Jar on a counter somewhere in the kitchen, it does not work.  The presence of the Cow in a Jar seems to be not detected.

On Twitch, the latest version I can find is 8.0.1.  Please let me know if there's anything I can do to be of assistance in getting additional debug data for this.

**Comment by BlayTheNinth** [comment]
This was probably caused by the cow in a jar not having collected enough milk, or due to Pam's Harvestcraft support not being fully in yet. I can't reproduce the issue in my version with proper Pam's support. Feel free to re-open if it still happens after updating.

**Comment by eplossl** [comment]
![image](https://user-images.githubusercontent.com/11776328/83093811-c70ed300-a065-11ea-9b33-1c932a68cd33.png)
Here's a picture of our setup.  When I go into the cooking table, there's no milk available.  We have just updated our server to the latest cooking for blockheads (8.0.2) available on Twitch.  
![image](https://user-images.githubusercontent.com/11776328/83093941-135a1300-a066-11ea-9063-b91afd66d071.png)
As you can see in the screenshot, the milk jar is full of milk.  For that matter, there's even 8 fresh milk in the refrigerator, but there's no Butter available to make, either.
![image](https://user-images.githubusercontent.com/11776328/83094094-7cda2180-a066-11ea-8c39-0e043fc7ec2c.png)

**Comment by eplossl** [comment]
Incidentally, I would reopen this if I could, but since you closed it, I cannot.

**Comment by BlayTheNinth** [comment]
Still unable to reproduce. Could you try placing a separate kitchen somewhere with just a milk (or cow) jar and a cooking table and see if butter is available then? Is your Harvestcraft updated to the latest version as well?

**Comment by EmberAnimus** [comment]
![image](https://user-images.githubusercontent.com/22672144/85917129-40dcdc80-b81d-11ea-8c4b-d6652cb65445.png)
![image](https://user-images.githubusercontent.com/22672144/85917138-4d613500-b81d-11ea-98e7-366db535581a.png)

I am using the MC 1.14 version of CfB alongside Pams food core (I have tested both 1.03 and 1.04) and am experiencing this issue. It seems that any pam's recipe that doesn't produce a food value (such as salt, butter, etc) is not detected by CfB and doesn't show in the cooking table or the recipe books as well. This occurs regardless of if the resource is present in a cabinet or provided by a block in the kitchen. (See below)
![image](https://user-images.githubusercontent.com/22672144/85917207-d24c4e80-b81d-11ea-8d52-52690f549f30.png)
![image](https://user-images.githubusercontent.com/22672144/85917211-d7a99900-b81d-11ea-9100-e319006d7739.png)
Even by manually adding a milk bucket or water bucket, butter and salt do not appear for example. 

Hope this helps!

**Comment by BlayTheNinth** [comment]
Does this issue still occur on 1.16.x?
