### ISSUE TITLE
Seems to be ignoring Pam's tools for some recipes

### ISSUE THREAD

**Issue by HalJordan** [blay09/CookingForBlockheads#449]
I've got the following relevant(afaik) mods installed:

CookingForBlockheads_1.15.2-8.0.1.jar
pamhc2crops-1.15.2-1.0.5.jar
pamhc2foodcore-1.15.2-1.0.3.jar
pamhc2trees-1.15.2-1.0.5.jar

It's picking up the recipes to make some food. It will use the pot for making stew(pot, meat, flour, 2 x veg) but I can't make salt or fresh water when there's a sink **_directly_** attached to the cooking table. I've tried with a water bucket in my inventory and fresh water still doesn't show up. The same goes for having the pot and fresh water either in an attached fridge, cabinet, and with the pot in the oven and water in the various possible locations. Salt from pam's never shows up in the list, but I can make it in the normal crafting table.

It's not seeing fresh milk with a cow in a jar available or with a milk bucket in the attached fridge, but it's there for ice cream and yogurt.

I also notice that making flour isn't an option in the table.

Am I doing something wrong? Am I missing something?

**Comment by BlayTheNinth** [comment]
You are on an outdated version, CFB 8.0.2 added full support for Pam's Harvestcraft 2.
