### ISSUE TITLE
[1.15.2] Cooking Table only crafts some recipes when Create is installed

### ISSUE THREAD

**Issue by Zekrom64** [blay09/CookingForBlockheads#451]
I am using CfB with all of Pam's Harvestcraft 2 and noticed that when [Create](https://www.curseforge.com/minecraft/mc-mods/create) is installed, only some recipes will craft successfully in the Cooking Table. This is a particular problem with recipes from Pam's (for example, crafting Fresh Water even with a Sink installed will not work). When the recipe fails to craft, [this exception](https://gist.github.com/Zekrom64/6ef8670ddc8779908f58af6ea262278a) is output to the log.

Forge: 31.2.9
Cooking for Blockheads: 8.0.2
pamhc2foodcore: 1.0.3
pamhc2crops: 1.0.5
pamhc2trees: 1.0.5

**Comment by giltwist** [comment]
Confirming that removing Create does resolve the crafting issue.
