### ISSUE TITLE
Unable to use Search Bar

### ISSUE THREAD

**Issue by VieLassiel** [blay09/CookingForBlockheads#454]
With the newest version installed, along with JEI, and Journey map, I can type using those two mods, or when I type anywhere else, but everytime I try to use the cooking for blockheads search bar, it REFUSES to let me type in the search bar.

MC Version: 1.14.4

**Comment by BlayTheNinth** [comment]
Seems to already have been fixed in later versions, but 1.14 is no longer supported.
