### ISSUE TITLE
Crash on 1.16.1

### ISSUE THREAD

**Issue by MiguelWaffles** [blay09/CookingForBlockheads#456]
Using forge forge-1.16.1-32.0.66

https://pastebin.com/05n8bMVt

**Comment by BlayTheNinth** [comment]
> java.lang.RuntimeException: Something crashed the event bus earlier in the loading stage. This is NOT a Cooking for Blockheads issue! Scroll up in your latest.log to find the real crash log.

> rats-6.0.3-1.16.1.jar Rats {rats@6.0.3 ERROR}
