### ISSUE TITLE
[1.16] Crash with Sink. Circular model dependency

### ISSUE THREAD

**Issue by Darkere** [blay09/CookingForBlockheads#457]
https://gist.github.com/Darkere/288ac435e0b8c2442b7373656dae76dd

Player says she was "just flying around". 

CookingForBlockheads_1.16.1-9.0.0

Forge 32.0.71

**Comment by BlayTheNinth** [comment]
Are they using a texture pack or OptiFine? Did it happen only that one time or does it happen persistently?

**Comment by Darkere** [comment]
No optifine. The pack comes with a texture pack but I don't think that touches the sink in any way. 

Haven't had anyone else report this since. So potentially a one off.
