### ISSUE TITLE
Mouse Tweaks Crafting

### ISSUE THREAD

**Issue by Shukaro** [blay09/CookingForBlockheads#46]
Not sure how much of this is on the other end, but if you have mouse tweaks installed (with the scroll-to-move feature on), you'll craft a full stack of stuff if you hover over an icon and scroll (which is annoying when you're just looking through recipes.)

**Comment by blay09** [comment]
I'll have a look at MouseTweaks and find out if I can prevent MouseTweaks mousewheel to work on those slots.
