### ISSUE TITLE
[1.15.2] Tools not showing in JEI

### ISSUE THREAD

**Issue by atoldiago** [blay09/CookingForBlockheads#461]
Tried searching for something similar but wasnt able to find anything. JEI does not have the tools one requires for cooking, listed in its menu. On top of that, I have no idea how to make any of the tools, to see if its just a JEI issue, or if CFBs tools simply dont exist for my server.

Pertinent information: I am running a server with 62 mods on it, JEI and CFB among them. 
Version: 1.15.2
Forge:  31.2.33

If you need the modlist I can provide it. I appreciate any input on this, if its even an issue (also where in the world are the recipes for the tools?)

**Comment by atoldiago** [comment]
I may be stupid here, and be expecting something to show that doesnt unless Pam's is installed (friend of mine explained to me what that was). Completely possible Im just an idiot.

**Comment by BlayTheNinth** [comment]
Cooking for Blockheads only adds the cooking books and kitchen blocks. All food and cooking utensils are by third party mods like Pam's.

**Comment by atoldiago** [comment]
Thank you for answering!
