### ISSUE TITLE
[1.16.2] Compatibility issue with JEI

### ISSUE THREAD

**Issue by Udofalcon** [blay09/CookingForBlockheads#465]
**Issue**
Game client crashes when I try to open any of the CFB books.

[Crash Report](https://gist.githubusercontent.com/Udofalcon/040d9dfdfb849c8aa398b010145a448c/raw/776e0ef54f4aa822d393313e400feb854c4fd743/gistfile1.txt)

**Versions**
Forge: 1.16.2 - 33.0.20
Cooking For Blockheads: 1.16.2 - 9.1.0
Just Enough Items: 1.16.2 - 7.1.3.19

**Comment by AileyJames** [comment]
I have a similar issue with JEI, but also had issues with cooking table (it would  crash or wouldn't show the UI and just darken the screen but not show UI)
