### ISSUE TITLE
Butcher axe is missing from VFP tools list

### ISSUE THREAD

**Issue by djmattyg007** [blay09/CookingForBlockheads#467]
I noticed that VFP's butcher axe wasn't included in the list of tools in the mod's compat file:

https://github.com/blay09/CookingForBlockheads/blob/1.15.x/src/main/resources/data/cookingforblockheads/cookingforblockheads/compat/vanillafoodpantry.json#L48

Is there a reason for this, or would you accept a PR that adds it?

**Comment by BlayTheNinth** [comment]
No reason, it was just missed / didn't exist yet when the compat file was created.
