### ISSUE TITLE
[Suggestion] Add Crafttweaker integration for anvil recipe

### ISSUE THREAD

**Issue by winterSteve25** [blay09/CookingForBlockheads#468]
Hello, I'm a pack dev. Don't know much about modding. But it will be great if it is possible to add custom anvil recipes like the cow in a jar with crafttweaker :)

**Comment by BlayTheNinth** [comment]
That's out of scope for this mod, if anything someone could make a CraftTweaker addon to support those kinds of recipes.

**Comment by winterSteve25** [comment]
ok, thanks :)
