### ISSUE TITLE
Support of Artisan Worktables

### ISSUE THREAD

**Issue by Lgmrszd** [blay09/CookingForBlockheads#472]
The [Artisan Worktables](https://www.curseforge.com/minecraft/mc-mods/artisan-worktables) mod provides enhanced worktables. It would be cool if cooking table could catch up recipes from chef's worktable (maybe with possibility to change supported worktable types?)

Possible ways to implement, as I see it:
 - Similar to how vanilla recipes are handled, use main ingredients, as well as secondary ingredients and tools from connected kitchen blocks.
 - Similar to Cooking Oven, having said worktable connected to kitchen, with tool in it allows using supported recipes.

**Comment by BlayTheNinth** [comment]
Same as with Farmer's Delight support, I'm not a big fan of having Cooking for Blockheads act as a magic solution for mods that add their own mechanics for cooking/crafting. It also looks like Artisan Worktables has not updated past 1.16, so I'm closing this for now.
