### ISSUE TITLE
[MC 1.16.3] - Loading error with mod version 9.2.0 

### ISSUE THREAD

**Issue by Nijoma69** [blay09/CookingForBlockheads#474]
Hi Blay,

I've just downloaded the latest version of your Cooking for Blockheads mod and at load MC throws an error (I've attached a screenshot and the crashlog).

I think this could be because the "optional" mods are not yet in the mod pack I'm using.

Keep up the great work, your mods are great!!

Nick
[crash-2020-09-26_10.46.56-fml.txt](https://github.com/blay09/CookingForBlockheads/files/5286487/crash-2020-09-26_10.46.56-fml.txt)
![Capture](https://user-images.githubusercontent.com/16520157/94338075-76918d00-ffe7-11ea-8177-7bb57d53b840.PNG)

**Comment by BlayTheNinth** [comment]
Looks like the file was corrupt, missing a bunch of stuff. New update is out.
