### ISSUE TITLE
[1.16.3] Client crash on opening cooking table - ullPointerException: Rendering screen at net.blay09.mods.cookingforblockheads.registry.CookingRegistry.isNonFoodRecipe

### ISSUE THREAD

**Issue by ProsperCraft** [blay09/CookingForBlockheads#477]
This doesn't happen with every client, only one player on our dedicated server.

He could not find the crash log, here is a paste of his console with the crash log at the end.

https://gist.githubusercontent.com/digghair/c5b13132386157feb38f059015d8d1df/raw/61bd873b2bf0c918faacb932d06dd3ddc1e5a38d/gistfile1.txt

Modpack- TownCraft TWO test
CFB- CookingForBlockheads_1.16.3-9.2.1
Forge -34.1.9

**Comment by ProsperCraft** [comment]
Reproduced here with a different player-

Crash log- https://gist.github.com/ProsperCraft/0f1caf93d67c51148870702d12033f97
Client log- https://gist.github.com/ProsperCraft/f95628ce4f3265f4e804779e55652533

Forge .16

**Comment by egguchan** [comment]
One of my server members is having the same problem, but we are unaffected with exactly the same mods:

Crash log - https://gist.github.com/egguchan/efbc62c880c057e1cb3305e2a90731a1

**Comment by ProsperCraft** [comment]
yes, this is the issue we have, some people crash, some don't.
