### ISSUE TITLE
Suggestion.

### ISSUE THREAD

**Issue by Taknax** [blay09/CookingForBlockheads#484]
A cook (like the mechant in FFB) would be amazing with the falling sound :)

**Comment by BlayTheNinth** [comment]
That'd be like telling the same joke twice :P I don't really see any purpose of a cook NPC right now (nor any point at which they should spawn in that way). Maybe there'll be a just-normally-spawning cook villager in the future, but I don't see much incentive for it at the moment.

**Comment by Taknax** [comment]
Maybe the cook can cook 3 different thinks at same time and can sell something. But true is that the mod is awesome enough without!
