### ISSUE TITLE
Pam's Harvestcraft 2 Food Extended & Trees issues

### ISSUE THREAD

**Issue by unmoving-javi** [blay09/CookingForBlockheads#485]
Currently using version 9.2.2 of Cooking for Blockheads and 1.0.0 of both Pam's mods.

Most recipes work, but the intermediate ingredients are not supported, mostly things without a food value. For instance hot sauce, other condiments, and so forth, even if the tools are available, cannot be crafted in the kitchen. HC2 Food Core works for recipes without food values too though, so maybe this is a simple fix, if the compatibility can just be extended to the newer HC2 mods.

**Comment by VaelophisNyx** [comment]
Aha, so it wasn't just me baffled by the missing recipes
