### ISSUE TITLE
PMMO Compatibility for Cooking exp with the Oven and Multiblock Kitchen

### ISSUE THREAD

**Issue by andresmarver1** [blay09/CookingForBlockheads#486]
Project MMO adds a variety of skills, one of them Cooking, which serve as a central 'hub' for interconnecting a myriad of mods into a cohesive progression line. Currently, there exists no compatibility between ProjectMMO and Cooking For Blockhead's Oven, as it is not read as a regular furnace. The 'crafting table' from the kitchen, though, works, as I assume it uses the same handler for crafting that PMMO picks up when awarding EXP.

Would be lovely to be able to have these two mods compatible. 

PMMO GitHub: https://github.com/Harmonised7/project_mmo

**Comment by BlayTheNinth** [comment]
The next version adds an `OvenCookedEvent` (which is fired where the pmmo compat mod mixins into right now) and an `OvenItemSmeltedEvent` (which extends and is fired the same way as the native ItemSmeltedEvent). Those can be used by third party mods to react to oven cooking.

https://github.com/blay09/CookingForBlockheads/commit/1c9229942cce8f84e9e72c31848366592a7aa500

**Comment by cheshyrp** [comment]
You say this was fixed in the "next version", yet I experience exactly the same crash on Cooking for Blockheads 1.16.5-9.3.3, dated June 28. Was the patch not applied?
