### ISSUE TITLE
Cooking Table gets pretty laggy on big kitchens due to Multiblock Scanner

### ISSUE THREAD

**Issue by jrr8128** [blay09/CookingForBlockheads#489]
Initially set up a small kitchen with 48 storage drawers (1x1) with various crops, nothing too complicated. When opening the kitchen block there is a few seconds delay (recipe look up) and then recipe list generation. Friends on the server immediately complain of rubber-banding each time I open/select a recipe and craft it. There is also a slight delay before the craft occurs. 

Troubleshooting - removed the storage drawer connection and tested it - there was less lag (less recipes) but still rubber-banding occurring. Removal of utensils (suggested in another thread) and no dice.

[https://i.imgur.com/4TRcpJL.jpeg](url)
https://spark.lucko.me/#Inr6JiYnvN

Modlist (All up to date for 1.15.2):

    Waystones (by BlayTheNinth)
    Charmonium (by svenhjol)
    MysticalLib (by EpicSquid315)
    Performant (by someaddon)
    mGui (by mickelus)
    Extra Boats (by TeamAbnormals)
    TelePass (by Mrbysco)
    U Team Core (by HyCraftHD)
    Polymorph (Forge) (by TheIllusiveC4)
    Miner's Helmet (by ModdingLegacy)
    Apotheosis (by Shadows_of_Fire)
    Valhelsia Structures (by ValhelsiaTeam)
    Bountiful (by ejektaflex)
    FTB Quests (by FTB)
    Wither Skeleton Tweaks (by Shadows_of_Fire)
    FTB GUI Library (by FTB)
    Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)
    FTB Teams (by FTB)
    Libnonymous (by davenonymous)
    Structure Gel API (by ModdingLegacy)
    AutoRegLib (by Vazkii)
    Strange (by svenhjol)
    Infinite Music (by frinn38)
    FastFurnace (by Shadows_of_Fire)
    Macaw's Roofs (by sketch_macaw)
    Rotten Creatures (by RPorotos)
    Controlling (by Jaredlll08)
    Abnormals Core (by TeamAbnormals)
    Leaves Decay on other Leaves (by tfarecnim)
    Dungeons Plus (by ModdingLegacy)
    Server Tab Info (by black_dog20)
    Buzzier Bees (by TeamAbnormals)
    Item Filters (by LatvianModder)
    Cooking for Blockheads (by BlayTheNinth)
    Simple Farming (by enemeez1)
    End: Reborn (by elecatron)
    Just Enough Items (JEI) (by mezz)
    Spawn in Village (by jihuayu)
    Productive Bees (by LobsterJonn)
    Nature's Compass (by Chaosyr)
    Tetra (by mickelus)
    Atum 2: Return to the Sands (by Shadowclaimer)
    More Overlays Updated (by RiDGo8)
    In Control! (by McJty)
    Neat (by Vazkii)
    Storage Drawers (by Texelsaur)
    Better Burning (by DarkhaxDev)
    Just Enough Resources (JER) (by way2muchnoise)
    Atmospheric (by TeamAbnormals)
    Better Ping Display (by Quintinity)
    Cosmetic Armor Reworked (by LainMI)
    Structurize (by H3lay)
    Curios API (Forge) (by TheIllusiveC4)
    Waystones2Waypoints (by Noobanidus)
    Campfire Torches (by enemeez1)
    Charm (by svenhjol)
    Macaw's Windows (by sketch_macaw)
    Farming for Blockheads (by BlayTheNinth)
    Dude! Where's my Horse? (by Noobanidus)
    Xaero's World Map (by xaero96)
    World Pre Generator (by GeheimagentNr1)
    Global XP (by bl4ckscor3)
    Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
    Quark Oddities (by Vazkii)
    The One Probe (by McJty)
    Enhanced Mushrooms (by Ep1c312)
    Pam's HarvestCraft 2 - Crops (by pamharvestcraft)
    Spice of Life: Carrot Edition (by lordcazsius)
    Decorative Blocks (by stohun)
    GraveStone Mod (by henkelmax)
    Bookshelf (by DarkhaxDev)
    Useful Backpacks (by HyCraftHD)
    JEI Enchantment Info (by Phylogeny)
    Enchanted Book Redesign (by tfarecnim)
    XL Packets (by tfarecnim)
    Kottle (by Alex_wells)
    MrCrayfish's Furniture Mod (by MrCrayfish)
    Quiver Redux (by tfarecnim)
    Drawers Tooltip (by Snownee_)
    Paintings ++ (by AbsolemJackdaw)
    AmbientSounds 3 (by CreativeMD)
    Upgrade Aquatic (by TeamAbnormals)
    Quark (by Vazkii)
    Immersive Engineering (by BluSunrize)
    Extended Nether Backport (by blackgear27)
    Crafting Tweaks (by BlayTheNinth)
    Doggy Talents (by percivalalb)
    Areas (by Serilum)
    Immersive Posts (by TwistedGate)
    Collective (by Serilum)
    TerraForged (by dags_)
    Create (by simibubi)
    Traverse Reforged (by Noobanidus)
    AppleSkin (by squeek502)
    Aquaculture 2 (by Shadowclaimer)
    Bamboo Blocks (by TeamAbnormals)
    Swamp Expansion (by TeamAbnormals)
    Savage & Ravage (by TeamAbnormals)
    Pickle Tweaks (by BlakeBr0)
    Better Animals Plus (by cybercat5555)
    MixinBootstrap (by LX_Gaming)
    Login Protection (by someaddon)
    Fast Leaf Decay (by olafskiii)
    MineColonies (by H3lay)
    Cull Particles (by tfarecnim)
    Starter Kit (by Serilum)
    Iron Chests (by ProgWML6)
    ReAuth (by TechnicianLP)
    Riddle Chests (by davenonymous)
    Absent by Design (by Lothrazar)
    Autumnity (by TeamAbnormals)
    Cucumber Library (by BlakeBr0)
    Uppers (by vadis365)
    Clumps (by Jaredlll08)
    Xaero's Minimap (by xaero96)
    Incubation (by martianarchitecture)
    Project: Vibrant Journeys (by solis_nova123)
    YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
    Morpheus (by Quetzi)
    Macaw's Furniture (by sketch_macaw)
    EmbellishCraft (by Mapper)
    Macaw's Bridges (by sketch_macaw)
    NetherPortalFix (by BlayTheNinth)
    Fairy Lights (by pau101)
    TrashSlot (by BlayTheNinth)
    YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
    Global Data- & Resourcepacks (by JTK222)
    Phosphor (Forge) (by jellysquid_)
    FTB Backups (by FTB)
    FTB Chunks (by FTB)
    Unity: Dark Edition (by theCyanideX)
    Dungeon Crawl (by XIROC1337)
    Placebo (by Shadows_of_Fire)
    FPS Reducer (by bre2el)
    Macaw's Trapdoors (by sketch_macaw)
    Comforts (by TheIllusiveC4)
    Inventory Tweaks Renewed (by David1544)
    The Midnight (by cipher_zero_x)
    Mapper Base (by Mapper)
    Extended Lights (by Polyvalord)
    Better Advancements (by way2muchnoise)
    The Endergetic Expansion (by TeamAbnormals)
    Whisperwoods (by itsmeowdev)
    Macaw's Doors (by sketch_macaw)
    Engineer's Decor (by wilechaote)

**Comment by BlayTheNinth** [comment]
Only way this can be improved is by only computing the Multiblock Kitchen once and caching it / reacting to world changes. It's a somewhat bigger change.

**Comment by Diversion98** [comment]
any info on this?
because on our server, this is a big pain :p

edit: i'm on mc 1.16

**Comment by Nihilhalla** [comment]
I can inform that this issue persists in 1.18.2 I have a spark profile that I have linked below in the hopes that it helps,
as much as I hate "+1" as a comment on a chain for an issue, that's all I have right now.
[awcsparkprofile.zip](https://github.com/ModdingForBlockheads/CookingForBlockheads/files/9792746/awcsparkprofile.zip)

**Comment by BlayTheNinth** [comment]
Closing in favor of #675 and #676 which proposes a solution for improving performance with larger setups.
