### ISSUE TITLE
[1.12.2] Oven not accepting RF energy

### ISSUE THREAD

**Issue by RavenholmZombie** [blay09/CookingForBlockheads#491]
Mod Version: 6.5.0

The oven is not accepting RF input from Immersive Engineering wire connectors or XNet connectors. I also tried this with a fully built multiblock kitchen and got the same results.

![2021-01-08_23 54 29](https://user-images.githubusercontent.com/1634865/104083493-1bd61700-520d-11eb-9357-64fb29ce2fea.png)

**Comment by BlayTheNinth** [comment]
Working fine with Immersive Engineering on 1.16+. Did you apply the Heating Unit to the oven?
