### ISSUE TITLE
[1.16.4] Recipes that cost tool durability consume the tool

### ISSUE THREAD

**Issue by NielsPilgaard** [blay09/CookingForBlockheads#495]
Recipes from Farmer's Delight that require a tool in the recipe consumes the tool when the recipe is used in a Cooking for Blockheads kitchen. Normally the tool would lose 1 durability per craft.

### Versions
- CookingForBlockheads_1.16.3-9.2.2
- FarmersDelight-1.16.3-0.2.4b
- Forge-1.16.4.35.1.36

Original report: https://github.com/NillerMedDild/Enigmatica6/issues/920#issuecomment-761684767

**Comment by BlayTheNinth** [comment]
I tried reproducing this with AE's cutting knife to craft anchor cables in the cooking table and the durability was reduced correctly, item was only used up once it was empty. 

The affected recipes seem to be custom recipes that aren't available in just Farmer's Delight, so my guess is that either the knife item(s) or the custom recipes are doing something different from (at least) AE2. 

Not sure what other mods there are with durability-based ingredients that this could be tested with.

**Comment by NielsPilgaard** [comment]
The tool/durability recipes from Farmer's Delight have been removed since I reported this, so I guess this isn't applicable anymore :P
Edit: Thanks for testing it out anywho.

**Comment by NielsPilgaard** [comment]
I figured out the issue here, it's actually the `tool_shapeless` recipetype from the Enigmatica Companion Mod that causes this ^^'
