### ISSUE TITLE
gradle build error

### ISSUE THREAD

**Issue by brocepticon** [blay09/CookingForBlockheads#499]
when building the gradle the cmd im getting this error from download.

A problem occurred evaluating root project 'CookingForBlockheads-1.16.x'.
> C:\Users\*******\Downloads\CookingForBlockheads-1.16.x\CookingForBlockheads-1.16.x\run\obfmods

can anyone help me with this?

**Comment by BlayTheNinth** [comment]
You have to create that "obfmods" folder, or add an `if(obfModsDir.exists())` around the code in the build.gradle as done here: https://github.com/blay09/Waystones/pull/322/files

**Comment by brocepticon** [comment]
so simple lol !!!! thank you sooo much it worked i would have never found that lol,
wicked code as well !
