### ISSUE TITLE
[1.16.5] Unable to remove cookbook from the cooking table

### ISSUE THREAD

**Issue by MarioSMB** [blay09/CookingForBlockheads#500]
The #NoFilter cookbook is very useful when placed on the cooking table, though it is also nice sometimes to only see what foods can actually be made. However, there is no way to remove the book (besides breaking the table of course, which is an annoyance).  
It would be nice to be able to remove the cookbook by shift-right-clicking the cooking table.

As a side note, perhaps a sorting option to hide meals which can't be crafted would also help.

**Comment by BlayTheNinth** [comment]
Right-clicking the cooking table should return the no filter edition to your hand.

**Comment by MarioSMB** [comment]
Strangely, upon trying again now, crouch-right-clicking appears to be correctly removing the book from the table, not sure why this wasn't the case before... I suppose it's safe to consider this solved.
