### ISSUE TITLE
My server crash after i cook from the oven

### ISSUE THREAD

**Issue by Lorkid** [blay09/CookingForBlockheads#507]
Everything is fine until i try to cook some breads from the oven and then my game is force close. When i try to login again, it's just wont load the save game.

**Comment by BlayTheNinth** [comment]
Need the crashlog / latest.log from when the crash happens.

**Comment by Lorkid** [comment]
[latest.log](https://github.com/blay09/CookingForBlockheads/files/6084690/latest.log)

**Comment by BlayTheNinth** [comment]
```
Caused by: java.lang.NullPointerException
	at com.minttea.cfbpmmocompat.OvenHandler.handleCooking(OvenHandler.java:29) ~[?:1.0.2]
	at net.blay09.mods.cookingforblockheads.tile.OvenTileEntity.handler$zzd000$handleCooking(OvenTileEntity.java:546) ~[?:9.2.2]
```

This is an error in the `Project MMO and Cooking for Blockheads Compat` mod (https://www.curseforge.com/minecraft/mc-mods/project-mmo-and-cooking-for-blockheads-compat)

**Comment by Lorkid** [comment]
Thank you
