### ISSUE TITLE
1.0.54 - Index of mouse click in cooking table is off

### ISSUE THREAD

**Issue by tivec** [blay09/CookingForBlockheads#51]
I crafted the new cooking table and ran into the following issue:

I scroll down once and hover the kiwi juice:
![](http://i.imgur.com/NvApRCP.png)

I click it, and it properly shows the recipe:
![](http://i.imgur.com/CuYnq4H.png)

Finally, to craft it I have to click on the cell + 1 (in this case, one to the right):
![](http://i.imgur.com/T2fDZSi.png)

If I scroll one more down, the offset has to be +2 for it to craft the correct recipe. I suspect that it will be +3 for another tick of the scroll wheel.

While I am not familiar with your code, I think the issue comes out of this function https://github.com/blay09/CookingForBlockheads/blob/master/src/main/java/net/blay09/mods/cookingbook/client/GuiRecipeBook.java#L256

**Comment by bakaxyf** [comment]
You can use `![](URI)` to embed imgur images :)

e.g.
 `![](http://i.imgur.com/NvApRCP.png)`
![](http://i.imgur.com/NvApRCP.png)

**Comment by tivec** [comment]
Gotcha @bakaxyf, updated the post with embedded images :)
