### ISSUE TITLE
Newest Version crash on startup

### ISSUE THREAD

**Issue by JuicyCosmos** [blay09/CookingForBlockheads#515]
**Versions**
- Forge Version (exact version number): forge version is 35.1.36, game version is 1.16.4
- Mod Version (exact version number): mod version 9.3.0

**Describe the bug**
The mod will not load up and instead crashes during startup, it seems like the enableMilk method does not exist (at least in forge 35)

**To Reproduce**
1. Open MC Launcher
2. Hit Play
3. The game crashes while loading

**Screenshots**
![image](https://user-images.githubusercontent.com/79921098/111060132-af5de980-84d5-11eb-9580-9596c9c2ab6d.png)

**Additional context**
I don't think this is a compatibility issue and I wonder if the issue can be solved by updating forge. My current game version and forge version are not the latest since updating them will lead to a lot of hassle updating all the mods I'm currently playing with.

**Comment by BlayTheNinth** [comment]
The file was incorrectly marked as compatible with 1.16.3/1.16.4. It is correctly marked as 1.16.5 only now. 

You'll have to downgrade back to the previous version if you can't update to 1.16.5, though nearly all mods should run just fine on 1.16.5 even with 1.16.4 file versions.
