### ISSUE TITLE
Shadow issue

### ISSUE THREAD

**Issue by Sebulba46** [blay09/CookingForBlockheads#519]
**Versions**
- Minecraft Version (exact version number): 1.16.5
- Forge Version (exact version number): forge-1.16.5-36.0.46
- Mod Version (exact version number): CookingForBlockheads_1.16.5-9.3.1.jar
- Do you use Sponge, OptiFine or Vivecraft (and which?): 

**Describe the bug**
The doors of the table and selves are wierd dark

**To Reproduce**
1. Place a table
2. place cubblestone behind
3. Doors appears to be dark

**Expected behavior**
A clear and decent looking door
**Screenshots**
![2021-03-24_00 55 16](https://user-images.githubusercontent.com/69625532/112225818-6973f480-8c3e-11eb-8177-88be0f1f84fd.png)

**Additional context (e.g. Crash Log if it crashed)**

**Comment by BlayTheNinth** [comment]
Do you use any mods that alter rendering (e.g. shaders) or improve performance?

**Comment by andOrlando** [comment]
I have the same issue running the enigmatica 6 expert modpack which doesn't seem to have neither shaders nor optifine. It seems to only happen when the block is facing south and smooth lighting is either minimum or maximum--it works correctly when smooth lighting is turned off. I'm on version 9.3.4 minecraft 1.16.5

**Comment by Microsoft6477** [comment]
I have the same issus when sodium installed, but if ture off smooth lighting can solve this issus.

Minecraft Version: 1.21.1
Neoforge Version: 21.1.222
Mod Version: 21.1.18
Sodium Version: 0.6.13
