### ISSUE TITLE
Server Crash 1.16.4

### ISSUE THREAD

**Issue by Holo795** [blay09/CookingForBlockheads#521]
Hello, I launch my server with 37 mods, at start it crash
Failed to create mod instance...

I send the crash report
[crash-2021-04-06_16.40.18-fml.txt](https://github.com/blay09/CookingForBlockheads/files/6265510/crash-2021-04-06_16.40.18-fml.txt)

**Comment by BlayTheNinth** [comment]
The 1.16.5 version is not compatible with 1.16.4.

**Comment by Holo795** [comment]
hum ok thx
