### ISSUE TITLE
Cooking for Blockheads (cookingforblockheads) has failed to load correctly

### ISSUE THREAD

**Issue by blueadamantine** [blay09/CookingForBlockheads#524]
**Versions**
- Minecraft Version (exact version number): 
- Forge Version (exact version number): 1.16.4-forge-35.1.37
- Mod Version (exact version number): 1.16.5-9.3.1
- Do you use Sponge, OptiFine or Vivecraft (and which?): OptiFine_1.16.4_HD_U_G6

**Describe the bug**
The mod fails to load, causing the error described in the title.

**To Reproduce**
1. Launch the launcher.
2. Press Play.
3. Wait for mods to load.

**Expected behavior**
Mod loads without issues and can be used in the game.

**Screenshots**
https://ibb.co/T0BgppZ

**Additional context (e.g. Crash Log if it crashed)**
https://traff.co/5iuEn1Nd

**Comment by BlayTheNinth** [comment]
1.16.5 version requires Minecraft 1.16.5 to run
