### ISSUE TITLE
Cooking tools with durability are being consumed instead of reduced

### ISSUE THREAD

**Issue by moklmaru** [blay09/CookingForBlockheads#525]
- Minecraft Version: 1.16.5
- Forge Version: 36.1.0
- Mod Version: 9.3.1
- Do you use Sponge, OptiFine or Vivecraft: None were used. I created an instance of only CFB, Croptopia (version 1.3.1), and JEI to test this issue. 

**Describe the bug**
When using the cooking station to create a Croptopia recipe that involves a tool (such as the cooking pot or frying pan), the tool will be entirely consumed instead of losing 1 durability as intended. The recipe works as normal in an ordinary crafting table, but not in a CFB kitchen.

**To Reproduce**
1. Construct a CFB multiblock kitchen
2. Load it with ingredients for a recipe that involves a cooking tool, as well as the tool itself (an easy example I used is grape jam which requires grapes, sugar, and a cooking pot)
3. Use the cooking table to craft the recipe and witness as your trusty cooking pot vanishes into thin air.

**Expected behavior**
Ideally, the recipe should be completed and leave the cooking pot with 1 less durability for further use.

**Comment by BlayTheNinth** [comment]
Seems to be fixed on Croptopia 1.4.0
