### ISSUE TITLE
Oven Crash Looping on Load 1.16.5 MV:9.3.1

### ISSUE THREAD

**Issue by litjohn50** [blay09/CookingForBlockheads#526]
**Versions**
- Minecraft Version (exact version number): 1.16.5
- Forge Version (exact version number):  36.1.4
- Mod Version (exact version number):  9.3.1
- Do you use Sponge, OptiFine or Vivecraft (and which?):  No

**Describe the bug**
I opened the cooking table selected that I wanted to cook a carrot from the mod "mystic world", once it finishes cooking the carrot it just crashes. Tried restarting the server and it just crash loops.

**To Reproduce**
1. Go to the cooking table and select Cooked carrot 
2. Put a Carrot in the Oven
3. Put fuel into oven and wait for it to cook
4.  Crash

**Expected behavior**
It is supposed to Cook the carrot.

**Additional context (e.g. Crash Log if it crashed)**
https://gist.github.com/litjohn50/9bf8324ba47a6edb9ecf8698e34bd5b2

**Comment by BlayTheNinth** [comment]
see https://github.com/blay09/CookingForBlockheads/issues/507#issuecomment-790698617
