### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by Heromaex** [blay09/CookingForBlockheads#528]
**Versions**
- Minecraft Version: 1.16.4
- Forge Version: 1.16.4-forge-35.1.37
- Mod Version: 1.16.5-7.0.15
- Do you use Sponge, OptiFine or Vivecraft: No, I am not.

**Describe the bug**
As soon as I start the game, it's giving me the error that is shown in the attached image.
I've been reading through the comments and they said it's compatible with it.
![image](https://user-images.githubusercontent.com/71891972/116099955-c2ef9900-a6ac-11eb-8d6a-b87a7d19013b.png)

**To Reproduce**
1. Open the game

**Expected behavior**
I can just open Minecraft and use it.

**Additional context (e.g. Crash Log if it crashed)**
[latest.log](https://github.com/blay09/CookingForBlockheads/files/6377882/latest.log)
[crash-2021-04-26_16.28.13-fml.txt](https://github.com/blay09/CookingForBlockheads/files/6377904/crash-2021-04-26_16.28.13-fml.txt)

**Comment by BlayTheNinth** [comment]
1.16.5 version requires Minecraft 1.16.5 to run
