### ISSUE TITLE
incompatible with dynamic trees

### ISSUE THREAD

**Issue by lyzio** [blay09/CookingForBlockheads#529]
**Versions**
- Minecraft Version (exact version number): 1.16.5
- Forge Version (exact version number): 36.1.15
- Mod Version (exact version number): 9.3.1
- Do you use Sponge, OptiFine or Vivecraft (and which?): no

**Describe the bug**
CookingForBlockheads Generates errors when trying to start server together with Dynamic Trees.
Neither mod describes incompatability with each other.

**To Reproduce**
Start server with Dynamic Trees.

**Expected behavior**
Server do not start

**Screenshots**

**Additional context (e.g. Crash Log if it crashed)**
Log file
https://pastebin.com/SDt98hiZ

**Comment by BlayTheNinth** [comment]
Unable to reproduce on latest versions of both mods.
