### ISSUE TITLE
Glitching textures [1.12.2]

### ISSUE THREAD

**Issue by Catacide** [blay09/CookingForBlockheads#530]
**Versions**
1.12.2
14.23.5.2847
6.5.0
Optifine enabled

**Describe the bug**
Texture glitches when using counters, kitchen corners and cabinets, see pictures for better visualition. Only happens when theres 2 of these next to each other, alone this doesnt happen

**To Reproduce**
1. Place cabinets, corner to counter or two counters next to each other
2. Textures glitch immediately

**Expected behavior**
No texture glitches :D

**Screenshots**
![2021-05-18_12 32 54](https://user-images.githubusercontent.com/49702864/118628966-cec70a80-b7d5-11eb-9e54-9a3ccfe05cf2.png)
![2021-05-18_12 33 01](https://user-images.githubusercontent.com/49702864/118628971-cf5fa100-b7d5-11eb-8b0c-6a4868a281bb.png)
![2021-05-18_12 33 07](https://user-images.githubusercontent.com/49702864/118628972-cff83780-b7d5-11eb-99c2-eee880e3a697.png)
![2021-05-18_12 33 33](https://user-images.githubusercontent.com/49702864/118628975-cff83780-b7d5-11eb-8cf0-7cf22f703a47.png)

**Comment by BlayTheNinth** [comment]
Does this happen without Optifine / on 1.16.5 too?

**Comment by Catacide** [comment]
> Does this happen without Optifine / on 1.16.5 too?

Removing Optifine fixed this, didnt even think about it to cause issues like this :/ Now to find another mod with optifine like zoom function, really liked it and only reason I love that mod :/ Thanks for help though and fast reply!

**Comment by BlayTheNinth** [comment]
OptiFine has a reputation of causing rendering issues with mods. It's odd it's happening on those models since they're just normal Minecraft block models, but yeah this isn't something that can or should be fixed here.
