### ISSUE TITLE
Suggestion: Double wide refrigerator or alternating door handles

### ISSUE THREAD

**Issue by garrettleach** [blay09/CookingForBlockheads#531]
I was playing in a modpack with many ingredients and placed 2 double tall refrigerators next to each other. Having the door handles both on the same side seemed odd. It seems like having a 4x4 model could look good or have the model alternate handle sides _somehow_.

**Comment by BlayTheNinth** [comment]
The handle faces towards where you're standing when you're placing the fridge.

**Comment by garrettleach** [comment]
Oooohh, awesome. Thank you!
