### ISSUE TITLE
compatibility with create´s milk

### ISSUE THREAD

**Issue by Gitcrafter** [blay09/CookingForBlockheads#533]
can you please make your milk jar accept Create´s milk, as your´s and Create´s milks seem to be two different liquids

**Comment by vemerion** [comment]
This can be closed now, since Create has switched over to using the standard Forge milk since this commit: https://github.com/Creators-of-Create/Create/commit/6bb6727fc8dd92d5a797845cb135cdce0d489219

**Comment by Gitcrafter** [comment]
no with v.0.3.2b, the Item Drain still produces create´s own milk, so you have to use another mods tank, in my case from mekanism, to insert the milk into the system, as seen in the below screenshot, you can tell the difference, because create´s milk is slightly more yellowish, than the forge milk

![2021-07-27_20 04 19](https://user-images.githubusercontent.com/81863925/127205180-2cc6a7db-a656-4d4d-a4c0-0a9242efc302.png)

**Comment by vemerion** [comment]
Well, yes, the fix has not been released to CurseForge yet, but it is coming in the next update, since the fix has been accepted and merged.

**Comment by Gitcrafter** [comment]
Thats good to know, then I just have to wait

**Comment by Gitcrafter** [comment]
it works now
