### ISSUE TITLE
Fridge/Block duping glitch

### ISSUE THREAD

**Issue by Ki-Tan2934** [blay09/CookingForBlockheads#536]
**Versions**
All

**Describe the bug**
Item dupe due to moving inventory

**To Reproduce**
https://cdn.discordapp.com/attachments/690026962420367579/849692462499102800/Mb7e0I70iL.mp4 Watch the vid

**Solution**
Please make all your block not moveable by pistons

CookingForBlockheads will not be added to the next ATM pack if not fixed and may be removed from current active packs

**Comment by BlayTheNinth** [comment]
Don't try to use mod removal from packs as leverage or a subtle threat because it will get you blocked.

**Comment by StupidRepo** [comment]
> CookingForBlockheads will not be added to the next ATM pack if not fixed and may be removed from current active packs

@Ki-Tan2934 lol. beginners mistake.
