### ISSUE TITLE
crash when play with Pet Revival mod,

### ISSUE THREAD

**Issue by ColaLiao** [blay09/CookingForBlockheads#541]
crash when play with Pet Revival mod,
put horse skulls on the ground, then the game crash.

 
[crash-2021-07-25_06.34.37-client.txt](https://github.com/blay09/CookingForBlockheads/files/6873152/crash-2021-07-25_06.34.37-client.txt)

**Comment by BlayTheNinth** [comment]
Issue most likely lies in Pet Revival having a broken block entity
