### ISSUE TITLE
Compat with a few mods [datapack included]

### ISSUE THREAD

**Issue by Sixdd6** [blay09/CookingForBlockheads#542]
I made a datapack for compat with Farmers Delight, Builders Crafts and Additions, and Crayfish's More Furniture mod.

Here is the pack: 
[Cooking for Blockheads compat v2.zip](https://github.com/ModdingForBlockheads/CookingForBlockheads/files/7021733/Cooking.for.Blockheads.compat.v2.zip)

Edit: tweaked the pack, didn't realize there were two cookingforblockheads folders.

**Comment by BlayTheNinth** [comment]
Thanks, will be added in next 1.18 release
