### ISSUE TITLE
heating unit power

### ISSUE THREAD

**Issue by Error0x99** [blay09/CookingForBlockheads#545]
1.12 
hi so me and my friends are playing a progression mod pack that uses power with that said I went ahead to make a heating unit and no matter what kind of power supply I try to hook up to it doesn't seem to work so far I've tried immersive engineering and cyclic

**Comment by BlayTheNinth** [comment]
1.12 is no longer supported

**Comment by Error0x99** [comment]
so that all you cant say anything else that might help? and then close it youre awful
