### ISSUE TITLE
milk caused Exception in server tick loop

### ISSUE THREAD

**Issue by OcrSu** [blay09/CookingForBlockheads#546]
Server Crash Log:
https://paste.loliidc.cn/?a0b2e243b7a8829b#4KNm5rTYkp8VL5Q2AFSM9nwfySase1QPUYbJd14jyJLG

mod:Refined Storage
https://www.curseforge.com/minecraft/mc-mods/refined-storage

**Comment by BlayTheNinth** [comment]
paste site is down

**Comment by OcrSu** [comment]
Crash Log lost
