### ISSUE TITLE
Crash with because of smth between Cooking for blockheads and FTB Power Pots

### ISSUE THREAD

**Issue by Julcraft14** [blay09/CookingForBlockheads#549]
### Minecraft Version

1.16

### Mod Loader

Forge

### Mod Loader Version

36.2.8

### Mod Version

9.3.3

### Describe the Issue

I am Playing the FTB Oceanblock modpack and i added Your mod for the Kitchen sink.
In the newes version they added FTB Power Pots.
I tested the pots and as soon as i placed the pot it crashed because of your mod

### Logs

https://pastebin.com/CuLdwa7t

**Comment by BlayTheNinth** [comment]
`at dev.ftb.powerpots.pot.PowerPotTile.func_200662_C(PowerPotTile.java:132) ~[?:1605.1.0-build.7] {re:classloading}`

**Comment by Julcraft14** [comment]
> `at dev.ftb.powerpots.pot.PowerPotTile.func_200662_C(PowerPotTile.java:132) ~[?:1605.1.0-build.7] {re:classloading}`

at net.blay09.mods.cookingforblockheads.compat.CompatCapabilityLoader.attachTileEntityCapabilities(CompatCapabilityLoader.java:47)

**Comment by Julcraft14** [comment]
Ist there a conflict ? How can i fix that

**Comment by BlayTheNinth** [comment]
Report to FTB Power Pots, it's an issue on their end

**Comment by Julcraft14** [comment]
Ok

**Comment by Julcraft14** [comment]
Why ist there an Error can you say me just that
pls. Id like to play

**Comment by BlayTheNinth** [comment]
> Report to FTB Power Pots, it's an issue on their end

**Comment by Julcraft14** [comment]
Cool Thanks
