### ISSUE TITLE
Most of items in inventory disappears upon interacting with the kitchen counter.

### ISSUE THREAD

**Issue by GoliathX211** [blay09/CookingForBlockheads#564]
### Minecraft Version

1.17.x

### Mod Loader

Forge

### Mod Loader Version

forge-1.17.1-37.1.1

### Mod Version

cookingforblockheads-10.0.0+0

### Describe the Issue

Expected: To open the counter inventory and still be able to put my items in it or see my items.

Note: Also running on a server through Aternos

Reproduce: 
Step 1: Place Kitchen Counter block
Step 2: Have items in your inventory
Step 3: Some/most items are not there.
Optional - To get the items to come back, you can interact with an item slot that should have an item or has a different item due to the bug. Interacting with another inventory also fixes it.

Included: Video going through steps.
https://user-images.githubusercontent.com/30582936/146547629-7c05c1b5-98e3-4899-b7ed-b125f8c1e6c5.mp4

Note: The other counter blocks also do the glitch when I open their inventories

Mod List: 
appleskin-forge-mc1.17.1-2.2.0
balm-1.8.2+0
BiomesOPlenty-1.17.1-14.0.0.36-universal
buildinggadgets-1.17.1-14.0.0.36
chiselsandbits-1.1.39-ALPHA
chunkloaders-1.1.7a-mc1.17
Clumps-forge-1.17.1-7.0.10
cookingforblockheads-10.0.0+0
create-mc1.17.1_v0.4
elevatorid-1.17.1-1.8.1
farmingforblockheads-8.0.0+0
flywheel-forge-1.17-0.30
ironchest-1.17.1-12.0.2
jei-1.17.1-8.3.0.45
mavm-1.0.5b (More Axolotl Variants)
modnametooltip-1.17.1-1.17.0
netherportalfix-8.0.0+0
OptiFine_1.17.1_HD_U_H1 (tested without, not the issue)
SimpleStorageNetwork-1.17.1-1.5.0
sophisticatedbackpacks-1.17.1-3.12.1.418
supermartijn642configlib-1.0.9-mc1.17
swingthroughgrass-1.17.1-1.6.0
theoneprobe-1.17-4.0.2
torchmaster-3.0.1-beta
trashslot-10.0.0+0
waystones-8.2.0+0
Xaeros_Minimap_21.22.3_Forge_1.17.1
XaerosWorldMap_1.18.6_Forge_1.17.1

### Logs

"You have exceeded the maximum paste size of 512 kilobytes per paste. PRO users don't have this limit!" 

### Do you use any performance-enhancing mods (e.g. OptiFine)?

I was using OptiFine as I reproduced it in the video, and I am testing without OptiFine as I type this. Without OptiFine, the issue still occurs.

**Comment by GoliathX211** [comment]
So through testing it appears that what the bug is doing is taking the items in the top row of the inventory and setting them to the hotbar. Odd.

**Comment by GoliathX211** [comment]
If there is anything you would like me to do to help out in any way, let me know. If you want me to test removing certain mods to see if they are the issue, I am willing.

**Comment by BlayTheNinth** [comment]
Does this still happen on 1.18 / latest Balm?

**Comment by GoliathX211** [comment]
Sorry about the inactivity, I will try to check this after work

**Comment by GoliathX211** [comment]
Very busy lately and forgot. Working on it now.

**Comment by GoliathX211** [comment]
It does not seem to be happening for the 1.18 version with latest balm.
