### ISSUE TITLE
java.lang.NoSuchFieldError: GELLED

### ISSUE THREAD

**Issue by Hanawa02** [blay09/CookingForBlockheads#565]
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

net.minecraftforge:36.2.20

### Mod Version

9.3.4

### Describe the Issue

When I open the Book "Cooking for Blockheads #NoFilter Edition" and hover above or click over the first recipes, the error occurs and crash the application.

I'm playing the Valhesia 3 (1.16) mods.

### Logs

https://pastebin.com/mNrh3uV6

**Comment by BlayTheNinth** [comment]
`at com.cosmicgelatin.peculiars.core.registry.PeculiarsItems$Foods.lambda$static$8(PeculiarsItems.java:45) ~[?:1.16.5-2.0.0] {re:classloading}`

This seems to be an issue in Peculiars (possibly related to AppleSkin).
