### ISSUE TITLE
1.18.1 - Crash on Startup - Field Cannot be Null Oven Automation

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [blay09/CookingForBlockheads#566]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

1.18.1 - 39.0.10

### Mod Version

 cookingforblockheads-forge-1.18-11.0.0.jar

### Describe the Issue

Crash on Startup.

### Logs

https://gist.github.com/P3rf3ctXZer0/58fbeaf5fd32a46197458e00301d0820, https://gist.github.com/P3rf3ctXZer0/692bb9216542d75fcd6d1189d224c73c

### Do you use any performance-enhancing mods (e.g. OptiFine)?

adaptive_performance_tweaks_1.18.1-2.0.0, FastSuite-1.18.1-3.0.0, ferritecore-4.0.0-forge

**Comment by BlayTheNinth** [comment]
Fixed in latest Balm
