### ISSUE TITLE
Jade / WTHIT Incompatibility

### ISSUE THREAD

**Issue by nanonestor** [blay09/CookingForBlockheads#567]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

39.0.44

### Mod Version

11.1.0

### Describe the Issue

Throws an error in logs looking for-
[20:29:26] [Worker-Main-8/ERROR]: Error loading plugin at net.blay09.mods.cookingforblockheads.compat.WailaAddon

I do have Jade installed fyi -- Jade-1.18-4.1.1.jar.

Full log link, the link in the logs section is a snip of only the error thrown.
[Full log](https://paste.gg/p/anonymous/8e79734929c346d39c528c0321b8cea6)

### Logs

https://paste.gg/p/anonymous/8abac79b654749d6bf5b4c92a6eba5a3

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Not optifine.  Do have some such as lazydfu, ferrite core, entity culling - do not forsee them causing this type of issue.

**Comment by hacheraw** [comment]
Same here

**Comment by BlayTheNinth** [comment]
The Waila compat was implemented on the API of the WTHIT fork.

It seems both WTHIT and Jade have made diverging changes to the API while still keeping the original mod id and package names, so I don't think it's possible to support both at once, at least not without annoying magic or a separate mod.
