### ISSUE TITLE
Cooking gone wrong???

### ISSUE THREAD

**Issue by Klouver-github** [blay09/CookingForBlockheads#571]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

1.18.1-forge-39.0.85

### Mod Version

cookingforblockheads-forge-1.18.1-11.1.0.jar

### Describe the Issue

I have updated Balm while I have jade installed so when the issue came up, I took out jade and put in other requirement, didn't work either I even tried without Jade it never let me through requiring something for CookingForBlockHeads I am out of ideas what else could be the problem or solution to it

### Logs

https://paste.gg/p/anonymous/fd19906f6c464ee0b42b9aa4857cd2b6

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No Optifine

**Comment by BlayTheNinth** [comment]
Is it crashing or are you just getting an error logged?
