### ISSUE TITLE
Crash when upgrading building in Minecolonies

### ISSUE THREAD

**Issue by emanuele246gi** [blay09/CookingForBlockheads#572]
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

36.2.29

### Mod Version

9.3.4

### Describe the Issue

Because I've created a customized building with Minecolonies using the fridge from this mod, when I try to build it with the builders, it crashes without even showing me the interface.

### Logs

https://pastebin.com/720bbWfg

### Do you use any performance-enhancing mods (e.g. OptiFine)?
FerriteCore, Smooth Boot, FPS reducer, Dynamic FPS, Entity Culling

**Comment by BlayTheNinth** [comment]
I wouldn't really see this as an issue on Cooking for Blockheads' side. It looks like Minecolonies is trying to access tile capabilities without the tile being properly initialized (i.e. having a `world`). I believe this is something Minecolonies needs to safeguard against, as it would affect all mods with capabilities that are world-dependent.
