### ISSUE TITLE
Pam's HarvestCraft 2 Food Core incompatibility

### ISSUE THREAD

**Issue by iosgoodch** [blay09/CookingForBlockheads#574]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.0.18

### Mod Version

cookingforblockheads-forge-1.18.2-12.0.0

### Describe the Issue

I have determined through trial and error that cookingforblockheads-forge-1.18.2-12.0.0 is not compatible with the newly released Pam's HarvestCraft 2 Food Core mod (pamhc2foodcore-1.18.2-1.0.0). The issue is that PHC recipes cannot be crafted and JEI (jei-1.18.2-9.5.2.135) will not show the recipe ingredients. With cookingforblockheads-forge-1.18.2-12.0.0 removed, PHC crafting recipes work just find and JEI is able to display the recipes without an issue.

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No performance-enhancing mods are installed.

**Comment by BlayTheNinth** [comment]
Same cause as #576, but it looks to be an issue in Forge and I'm not sure what in Cooking for Blockheads is triggering it:
https://github.com/MinecraftForge/MinecraftForge/issues/8498

The current workaround is to run `/reload` after loading the world.
