### ISSUE TITLE
Incompatibility with croptopia

### ISSUE THREAD

**Issue by Vane79** [blay09/CookingForBlockheads#576]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

forge-1.18.2-40.0.17

### Mod Version

cookingforblockheads-forge-1.18.2-12.0.0

### Describe the Issue

Cooking for blockheads breaks croptopia recipes. 
This is what happens with both croptopia and cooking for blockheads enabled: 
![image](https://user-images.githubusercontent.com/36656584/159158318-c6849054-aca8-4554-92a0-533fa72d4a1d.png)
![image](https://user-images.githubusercontent.com/36656584/159158319-388532e9-5a50-4a99-a83e-f5456c98646e.png)

### Logs

https://pastebin.com/YBjJayXJ

### Do you use any performance-enhancing mods (e.g. OptiFine)?

None

**Comment by BlayTheNinth** [comment]
Same cause as #574, but it looks to be an issue in Forge and I'm not sure what in Cooking for Blockheads is triggering it:
https://github.com/MinecraftForge/MinecraftForge/issues/8498

The current workaround is to run `/reload` after loading the world.

**Comment by Vane79** [comment]
So, I've updated forge to forge-1.18.2-40.0.19, and tried running /reload, and it didn't fix the recipes.

**Comment by BlayTheNinth** [comment]
Reload takes a few seconds to finish, how long after running the command did you check?

**Comment by Vane79** [comment]
30 seconds-ish
