### ISSUE TITLE
infinite flour glitch

### ISSUE THREAD

**Issue by Sofiazed1** [blay09/CookingForBlockheads#577]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.0.19

### Mod Version

cookingforblockheads-forge-1.18.2-12.0.0.jar

### Describe the Issue

Whenever i use the cooking table to craft any recipe containing the flour item from pamhc2foodcore-1.18.2-1.0.0.jar, I also end up with a ton of extra flour. In this instance I crafted 12 batter, and then attempted to use up the random flour it gave me by crafting a stack of dough, and ended up with an additional 38 stacks of flour.
After posting this I opened the fridge and found 15 stacks of dough. I'm sure I didn't craft that many.

### Do you use any performance-enhancing mods (e.g. OptiFine)? 

Yes

**Comment by Sofiazed1** [comment]
never mind. it's being caused by jei. i'm accidentally cheat acquiring stacks of flour.

**Comment by Sofiazed1** [comment]
update: i changed the JEI (jei-1.18.2-9.5.4.171.jar) keybinds and the flour still appears. It may or may not be JEI related but i can't tell
using balm-3.0.1+0.jar as well, in case that is relevant.

**Comment by BlayTheNinth** [comment]
Does this happen on Minecraft 1.19?

**Comment by Sofiazed1** [comment]
Haven't tried, been too busy.
