### ISSUE TITLE
Fridge has missing textures / models when using OptiFine

### ISSUE THREAD

**Issue by ASlipperySlope** [blay09/CookingForBlockheads#578]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

Forge 39.1.2

### Mod Version

11.1.0

### Describe the Issue

The fridge has a missing texture either on the bottom, top or both upon restarting the game / world.

https://i.imgur.com/PL2m54k.png

### Do you use any performance-enhancing mods (e.g. OptiFine)?

OptiFine, doesn't happen without OptiFine.

**Comment by BlayTheNinth** [comment]
Closing since OptiFine isn't supported
