### ISSUE TITLE
Crash report shows: Circular reference while loading cookingforblockheads:block/sink_flipped

### ISSUE THREAD

**Issue by planeswalker2** [blay09/CookingForBlockheads#580]
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

forge-36.2.31

### Mod Version

CookingForBlockheads_1.16.5-9.3.4

### Describe the Issue

I can't even load into the game now I just immediately crash and so does everyone else who goes to my base.

Not sure what is causing it, tried removing the sinks but that didnt help.

Crash report linked. 

### Logs

https://paste-bin.xyz/47415

**Comment by BlayTheNinth** [comment]
Paste expired
