### ISSUE TITLE
Re-Add Functionality to connect to storage drawers

### ISSUE THREAD

**Issue by TronWoWGamer** [blay09/CookingForBlockheads#581]
This used to work in 1.16.5 where you could connect the cooking table to storage drawers either by being next to a drawer or any other part of the multi-block next to it.  Now in 1.18.2 it no longer seems to work which is a real pain for storing food from a large farm.

**Comment by HalcyonSeas73** [comment]
Agreed, would love to see this feature again.

**Comment by chocolatechipcats** [comment]
Query: Does this work in version 13.3.1 for 1.19.2? 

Placing some storage drawers on top of the kitchen flooring (and also connecting with cabinets) doesn't seem work and the kitchen block is not seeing anything inside the drawers.

Sorry for commenting on a closed issue and thanks in advance. 🙂
