### ISSUE TITLE
Blocks missing textures

### ISSUE THREAD

**Issue by kruelcamm** [blay09/CookingForBlockheads#582]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

Forge

### Mod Version

1.18.2

### Describe the Issue

The doors on the fridge, oven and cabinets are all missing on each item.

**Comment by BlayTheNinth** [comment]
Likely a mod conflict with something adding shaders or improving performance or changing model loading.

**Comment by tindin** [comment]
occulus causes this

**Comment by FlorSilvestre12** [comment]
I am now having this issue. Fridge and oven doors don't render. Minecraft Java 1.21.4, Fabric, mod version 21.4.2.

Other mods used are Additional Lanterns, Alternate Current, AppleSkin, Balm, Beautify: Refabricated, Biomes of Plenty, Cristel Lib, Entangled, Furnicraft, GlitchCore, Journeymap, Landmines, Legacy Bows, Mod Menu, OWO Lib, SuperMartijn642's Config Lib, SuperMartijn642's Core Lib, TerraBlender, Towns and Towers, and World Tools. The server was originally part of an Archipelago server so has some weirdness going on with death and advancement mechanics which I wouldn't think would cause a visual glitch like this.

(I also can't change the color of my counters or sinks. IDK if that's unrelated or might give a clue as to what's going on.)
