### ISSUE TITLE
Cow in a Jar Causes Registry Object not Present error

### ISSUE THREAD

**Issue by MystiaTech** [blay09/CookingForBlockheads#585]
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

36.2.33

### Mod Version

9.3.4

### Describe the Issue

We have had at least two server crashes now due to a registry not found: minecraft milk. When looking through the crash reports, both times it reported the issue appears to be caused by the cow-in-a-jar item. Our servers are set to reboot twice a day so I am not sure why the errors are happening so infrequently apart.

### Logs

https://gist.github.com/Advtech92/1b7943b14aa650c5b65e16bcd825a8be

### Do you use any performance-enhancing mods (e.g. OptiFine)?

no

**Comment by BlayTheNinth** [comment]
The milk fluid is registered by Forge so it should be present, my best guess is that the combination of Mekanism and Pipez causes pipe connection checks to run before Forge had the chance to register the fluid. Nothing I can fix here.

**Comment by BlayTheNinth** [comment]
Closing since this likely can't be fixed here and 1.16 is no longer supported.
