### ISSUE TITLE
Cow in A jar not creating milk

### ISSUE THREAD

**Issue by ninjalol5** [blay09/CookingForBlockheads#588]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.1.20

### Mod Version

12.0.1

### Describe the Issue

Cows in a jar just not making milk!

### Logs

https://docs.google.com/document/d/1BLNe90lm6CScCEqzTV0USKvZWoNxyOkg9Sp5jT11WV8/edit?usp=sharing

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Optifine

**Comment by BlayTheNinth** [comment]
logs should be put on gist or pastebin, I can't look at them if they require a login
