### ISSUE TITLE
Is CFB (cookingforblockheads) compatible with other mods?

### ISSUE THREAD

**Issue by Kingfluffypants** [blay09/CookingForBlockheads#589]
### Minecraft Version

1.12.x

### Mod Loader

Forge

### Mod Loader Version

1.12.2

### Mod Version

1.12.2

### Describe the Issue

I am making a modpack for my friends and halfway through the loading process it popped up with an error saying that a probable cause might be CFB. This is not unique to your mod because it has been happening a lot and I have 300+ mods in the pack but I want to know if you could tell me if any mods in my pack are not compatible with your mod.
[RANDOM ASSORTMENT OF MODS.zip](https://github.com/ModdingForBlockheads/CookingForBlockheads/files/8794242/RANDOM.ASSORTMENT.OF.MODS.zip)

**Comment by BlayTheNinth** [comment]
1.12 is no longer supported + I need logs, not a zip of 300+ mod files
