### ISSUE TITLE
The game crashed

### ISSUE THREAD

**Issue by Naxo175** [blay09/CookingForBlockheads#591]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

Forge 39.1.2

### Mod Version

11.1.0

### Describe the Issue

![image](https://user-images.githubusercontent.com/71966108/173108732-fd78fe76-73ec-44aa-911f-850d6662f079.png)

### Logs

https://pastebin.com/wGu37PHe

### Do you use any performance-enhancing mods (e.g. OptiFine)?

optifine

**Comment by BlayTheNinth** [comment]
Does it happen without OptiFine?

**Comment by Naxo175** [comment]
> Does it happen without OptiFine?

I don't know why but it suddenly worked with optifine, it's weird, i didn't touch the modpack, i didn't remove anything, i did nothing, i just restarted my pc and it worked.
Sorry for this useless issue
