### ISSUE TITLE
A list of small bugs

### ISSUE THREAD

**Issue by Chill907Gaming** [blay09/CookingForBlockheads#594]
### Minecraft Version

1.19.x

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### Mod Version

Cooking for blockheads v 13.1.1

### Describe the Issue

1. Using an empty bucket on the sink does not fill it

2. The toaster does not accept bread to cook croptopia toast.

3. The cow in a jar only supplies milk when right clicked with an empty bucket, not to any recipe's that require milk. even vanilla cake. You must fill the buckets manually to use milk.

4. When trying to craft "water bottles" from croptopia, the sink does not supply water. You should only need glass and a water bucket. related to problem 1 maybe?

5. After crafting an item using ingredients from a fruit bowl or spice rack, the used ingredients will appear to linger until you open the fruit bowl or spice rack. 
  E.g. Craft bread using wheat from a fruit bowl. After the bread is crafted look at the fruit bowl and visually there is still wheat.
  [Here is an example of the item's visual glitch](https://gyazo.com/e03cadd2a5be590572c36e2e338ff444)
  This is really not a big deal at ALL but just in case it's an easy fix I'll mention it
  
6. I'm not quite sure how to explain this one other than just showing you. I want to craft flour which requires two of the same item in the crafting grid. e.g. Corn, wheat, barley, etc. But the crafting station does not seem to see this recipe at all. 
[Here is an example](https://gyazo.com/25dda2eb389298924fe2e3b36d89f274). Sorry I don't really know how to explain it better. This must be because the flour is not considered a food right? If this is also a feature please let me know.
  
  

Some of these issues may be caused by croptopia and how they accept ingredients for crafting, but when I used applied energistics 2 with croptopia I was able to craft "croptopia water bottles" using only glass. It seems that water buckets and the water in my fluid cells are interchangeable. I know the sink might just be busted entirely right now but I would like to see this feature on cooking for blockheads if it's not already supposed to be that way. 
   E.g. crafting dough uses water bucket, wheat, and a cooking pot. Currently I have to fill a water bucket or water bottle from my own infinite source of water, then I can craft a couple dough.

### Logs

not necessary

### Do you use any performance-enhancing mods (e.g. OptiFine)?

not when testing

**Comment by BlayTheNinth** [comment]
Not sure if number 4 is fixed since I couldn't get Croptopia to run in my dev env. It could also be that it requires an empty bucket present in the kitchen.

Everything else should be fixed now.
