### ISSUE TITLE
Cow in a Jar Crash

### ISSUE THREAD

**Issue by grundrow** [blay09/CookingForBlockheads#597]
### Minecraft Version

1.19.x

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### Mod Version

13.1.1

### Describe the Issue

When trying to craft a Cow in a Jar it crashes after being made

### Logs

The game crashed whilst ticking block entity Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3611.method_15780(net.minecraft.class_3611)" because "fluid" is null Exit Code: -1

**Comment by BlayTheNinth** [comment]
need full logs

**Comment by romanempire12** [comment]
I had the same issue when trying to craft the cow in a jar
[crash-2022-07-10_19.55.52-server.txt](https://github.com/ModdingForBlockheads/CookingForBlockheads/files/9080650/crash-2022-07-10_19.55.52-server.txt)

**Comment by BlayTheNinth** [comment]
Update to the latest version.
