### ISSUE TITLE
Heating Unit Fabric energy compatibility

### ISSUE THREAD

**Issue by Geartwo** [blay09/CookingForBlockheads#598]
Please make the Oven upgraded with a Heating Unit compatible with:

- Modern Industrialization: EU
- Tech Reborn: E

**Comment by johnneijzen** [comment]
i was about make report about this because i taught it was bugged that none of energy cable are working
this all energy mod that i know off

Modern Industrialization: EU/t
Tech Reborn: E/t
Powah!: Fe/T
Industrial Revolution: LF/tick

**Comment by hideki2k02** [comment]
Unfortunately this is still not fixed... Is there an issue with the Fabric API? (I would sponsor if i had a job lmao)

**Comment by Raeffi** [comment]
Having the same Issue trying to input fe using Create Crafts and Additions wires (Fabric)

**Comment by BlayTheNinth** [comment]
Blocked by https://github.com/TwelveIterationMods/Balm/issues/67
