### ISSUE TITLE
Long loading time when installed with AE2

### ISSUE THREAD

**Issue by Vanroden141** [blay09/CookingForBlockheads#599]
### Minecraft Version

1.19.x

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### Mod Version

13.1.2

### Describe the Issue

When this mod is installed with AE2 12.0.1 the game locks up and takes a long time to load, and it seems to lock up longer with more mods. if either mod is removed the game loads perfectly but together it locks up

### Logs

https://pastebin.com/VpqSY9fB

### Do you use any performance-enhancing mods (e.g. OptiFine)?

n/a

**Comment by BlayTheNinth** [comment]
Closing since there's been no other reports of this and whatever it was probably resolved itself
