### ISSUE TITLE
Crashing due to StackOverflowError with AE2 

### ISSUE THREAD

**Issue by Geartwo** [blay09/CookingForBlockheads#602]
### Minecraft Version

1.19.x

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### Mod Version

13.1.2

### Describe the Issue

When placing an AE2 Inscriber or Press block the game crashes.
Description: Tessellating block in world - Indigo Renderer

This crash only happens when Cooking for Blockheads is installed.

Steps to recreate:
- Install Fabric, AE2, CFB, Balm & Cloth-Config
- Start a new creative world
- Place an Inscriber Block

### Logs

https://pastebin.com/4P5ADPnC

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No

**Comment by BlayTheNinth** [comment]
I suggest reporting this to AE2, they probably have a better idea on what could be causing their `AutoRotatingBakedModel` to freak out.

**Comment by Geartwo** [comment]
Crash was reported to AE2
#AppliedEnergistics/Applied-Energistics-2/issues/6459

**Comment by shartte** [comment]
This might actually be related to our way of customizing models in the model bakery. We do it in the getter, which is bad if any other mod calls it.
I've taken your model manager mixin as inspiration for a better injection point to customize the loaded baked models. That *might* fix this one as well (My guess is, our auto rotating model just got applied over and over and over again), but I have to re-test it.

**Comment by Geartwo** [comment]
This problem was solved with the new AE2 Update (12.0.2-alpha)
Thank you
