### ISSUE TITLE
Random Crash just happening out of nowhere (and only to specific players)

### ISSUE THREAD

**Issue by Asveste** [blay09/CookingForBlockheads#604]
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

36.2.35

### Mod Version

1.16.5-9.3.4

### Describe the Issue

While playing on our server a random crash out of nowhere happened. Thinking this could've happened all the time for no reason at all, we just started the server again. For a short amount of time everything was fine and working as it should, but then another player joined, and instantly after they joined, the server crashed again. After testing a bit more we now knew that this crash only happens from specific players joining. The interesting thing about this is, that someone from our group teleported themself to the player affected - in the short amount of time before the server would crash again - but this also caused a server crash. Now the player who teleported themself to the affected one was not able to join anymore, without causing a crash as well.
After removing the Cooking for Blockheads mod everything was working fine again and the affected players could also join the server without crashing it.

### Logs

Server Crash Log: https://gist.github.com/Asveste/4da5ea5b1fbb312a4818cdc06a777eda     Latest Server Log: https://gist.github.com/Asveste/2c6f94a00687091be2da1ee523b113db

### Do you use any performance-enhancing mods (e.g. OptiFine)?

We specifically removed every performance-enhancing mods on both the client and the server, which sadly did not fix the above issue.

**Comment by BlayTheNinth** [comment]
This has been fixed on Ice and Fire's side: https://github.com/Alex-the-666/Ice_and_Fire/issues/4547
