### ISSUE TITLE
Fridge not working

### ISSUE THREAD

**Issue by Shelmet67** [blay09/CookingForBlockheads#605]
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

Forge - 36.2.22

### Mod Version

1.16.5-9.3.4

### Describe the Issue

After cooking something in the furnace, the fridge stopped working, after a little testing it seems that when the fridge is 2 tall it no longer connects to the cooking table.

**Comment by Shelmet67** [comment]
Seems to be happening when the Preservation Chamber is installed

**Comment by BlayTheNinth** [comment]
Does this happen in 1.19+?
