### ISSUE TITLE
CookingForBlockheads crashes on Fabric during startup when in a pack with Create.

### ISSUE THREAD

**Issue by duress-to-kill** [blay09/CookingForBlockheads#610]
### Minecraft Version

1.18.x

### Mod Loader

Fabric

### Mod Loader Version

0.14.9

### Mod Version

12.1.0

### Describe the Issue

Game crashes during startup when installed with Create for Fabric (vers. `0.5.0c-708`).

Confirmed the interaction by creating a new modpack, pulling in only the latest (as of this submission) versions of Create and Cooking for Blockheads, which reproduced the issue.

### Logs

https://pastebin.com/iE1grxiq

**Comment by BlayTheNinth** [comment]
https://github.com/ModdingForBlockheads/Balm/issues/33
https://github.com/Fabricators-of-Create/Create/issues/508

Issue in Create with a pending fix
