### ISSUE TITLE
[Compatibility] Caupona is a relatively new cooking mod that would definitely benefit from compatibility.

### ISSUE THREAD

**Issue by Corvus20** [blay09/CookingForBlockheads#611]
[Caupona](https://www.curseforge.com/minecraft/mc-mods/caupona) some new cooking station blocks including stew pots, frying pans, braziers, and a few other components like doliums and its own stove blocks.

Its a beautiful mod and I'd love to see some compatibility for it.

**Comment by BlayTheNinth** [comment]
What kind of compatibility are you looking for specifically?
