### ISSUE TITLE
"Carpet" variant of "Kitchen Floor" blocks (forge)

### ISSUE THREAD

**Issue by xFirefalconx** [blay09/CookingForBlockheads#616]
Hi! 
I'm using a machine involving a bunch of hoppers right below my Minecraft kitchen. I'm currently using plain carpet pieces to prevent myself and others from tripping inside the hoppers. I would love to put a "Kitchen Block" of any color on top of them, but there is none that lets items pass through plus be as flat as a carpet, so I hope it's possible for you to add a carpet variant that lets you drop items to the hopper below just like vanilla carpets while keeping the "Kitchen Floor" block features. I believe that would make many people happy. 

P.S.: I'm playing on 1.16.5 and 1.18.2 and would love to have that available for either or both of them, if that's possible.

**Comment by BlayTheNinth** [comment]
This seems like quite a specific use case that I can't really follow. The idea of a "kitchen carpet" isn't immediately appealing to me either, I believe if anything, there should be some other alternative to the Kitchen Floor that allows linking kitchen blocks without requiring a specific block, but I'm not sure how that would look like yet. Moving this to Discussions for now.
