### ISSUE TITLE
[1.19.2] Crash while rendering Sink in world.

### ISSUE THREAD

**Issue by Gbergz** [blay09/CookingForBlockheads#617]
### Minecraft Version

1.19.x

### Mod Loader

Forge

### Mod Loader Version

43.1.39

### Mod Version

13.2.3

### Describe the Issue

Not much to explain other than me teleporting to an area with a Sink made my game crash.

### Logs

https://gist.github.com/Gbergz/2eeb5ce58a93845708528a4f250f4b7d

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No.

**Comment by BlayTheNinth** [comment]
Fixed in latest Balm version
