### ISSUE TITLE
Crashing when crafting food.

### ISSUE THREAD

**Issue by FishusChrist** [blay09/CookingForBlockheads#618]
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

36.2.34

### Mod Version

1.16.5-9.3.4

### Describe the Issue

When shift crafting stacks in the cooking table the game closes suddenly without an error message.

### Logs

https://drive.google.com/file/d/1sJRpzRFpMB11XJGgXNh7azG5R59SqlTJ/view?usp=sharing

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No performance enhancing mods.

**Comment by BlayTheNinth** [comment]
Please upload logs on gist or pastebin so they can be accessed without needing a login.

**Comment by FishusChrist** [comment]
> Please upload logs on gist or pastebin so they can be accessed without needing a login.

Here: https://gist.github.com/FishusChrist/0954966783b47f6d6d8ef31bafa5e23c  -- Sorry for the inconvenience.

**Comment by FishusChrist** [comment]
> Please upload logs on gist or pastebin so they can be accessed without needing a login.

Here, I think this is correct: https://gist.github.com/FishusChrist/019693d796f55f1b357776c2757a2ec6  -- sorry for the inconvenience.

**Comment by BlayTheNinth** [comment]
This is caused by Inventory Profiles Next:

```
Caused by: java.lang.NullPointerException: inventory must not be null
	at org.anti_ad.mc.ipnext.event.LockSlotsHandler.isMappedSlotLocked(Unknown Source) ~[?:?]
	at org.anti_ad.mc.ipnext.event.LockSlotsHandler.isQMoveActionAllowed(Unknown Source) ~[?:?]
```

**Comment by FishusChrist** [comment]
> This is caused by Inventory Profiles Next:
> 
> ```
> Caused by: java.lang.NullPointerException: inventory must not be null
> 	at org.anti_ad.mc.ipnext.event.LockSlotsHandler.isMappedSlotLocked(Unknown Source) ~[?:?]
> 	at org.anti_ad.mc.ipnext.event.LockSlotsHandler.isQMoveActionAllowed(Unknown Source) ~[?:?]
> ```

That helped, Thank you.
