### ISSUE TITLE
language zh_cn update for 1.19.2

### ISSUE THREAD

**Issue by YivanLiu** [blay09/CookingForBlockheads#632]
[zh_cn.zip](https://github.com/TwelveIterationMods/CookingForBlockheads/files/10779009/zh_cn.zip)

**Comment by BlayTheNinth** [comment]
Please submit translations as pull requests by using the "Add file" button in the [lang folder](https://github.com/TwelveIterationMods/CookingForBlockheads/tree/1.19.x/shared/src/main/resources/assets/cookingforblockheads/lang).
