### ISSUE TITLE
Cow in a jar not producing milk

### ISSUE THREAD

**Issue by ninjalol5** [blay09/CookingForBlockheads#635]
### Minecraft Version

1.19.2 (LTS)

### Mod Loader

Forge

### Mod Loader Version

1.43.52

### Mod Version

13.3.0

### Describe the Issue

Any time I put the cow in a jar down it never produces milk!

### Logs

https://gist.github.com/ninjalol5/0146e800c2f294179dc586fc06210249

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

yes

**Comment by BlayTheNinth** [comment]
Does it happen with only Cooking for Blockheads and Balm installed?

**Comment by ninjalol5** [comment]
> Does it happen with only Cooking for Blockheads and Balm installed?

yes!

**Comment by BlayTheNinth** [comment]
It works fine for me, what are your exact steps to reproduce the issue? How did you craft the Cow in a Jar and where do you place it? What happens if you leave it for 20 minutes and then use a bucket on it, and what happens when you try to fill it manually with a milk bucket?
