### ISSUE TITLE
Kitchen Blocks doors only face South for some reason

### ISSUE THREAD

**Issue by Gameriel** [blay09/CookingForBlockheads#637]
### Minecraft Version

Other (specify below)

### Mod Loader

Forge

### Mod Loader Version

14.23.5.2860

### Mod Version

6.5.0

### Balm Version

n/a

### Describe the Issue

MC version 1.12.2 
Cooking for Blockheads multiblock Kitchens that have doors, only render on the south face of the block. meaning that the doors on certain blocks render facing only south and appear to have no doors, but they are actually just inside the block facing the south.

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Attributefix, Better biome Blending, BetterFPS, Clumps, Fast Furnace, Fast workbench, Particle Culling, Surge, Texfix, Tiquality.

**Comment by BlayTheNinth** [comment]
Minecraft 1.12 is no longer supported and this is likely a mod conflict with one of the performance mods.
