### ISSUE TITLE
Better compatibility with Farmer's Delight

### ISSUE THREAD

**Issue by realslude** [blay09/CookingForBlockheads#638]
There isn't enough compatibility with Farmer's Delight 

1. I can't put my cutting board on a counter
~~2. The recipes only show and work for Croptopia and if they do show and work it will only give me the Croptopian stuff~~
2. Should add so if a Farmer's Delight crafting block is on a counter (or kitchen floor) all the recipes will show up in the cooking table

Great mod tho

**Comment by BlayTheNinth** [comment]
Farmer's Delight support is being discussed in https://github.com/TwelveIterationMods/CookingForBlockheads/discussions/562. If you want to open an issue for it, please describe in detail what blocks Cooking for Blockheads should support in what manner and why, as I am not familiar with Farmer's Delight. Generally I want to avoid having Cooking for Blockheads be a magic solution for mods that provide their own alternate crafting systems.

**Comment by SaphireLattice** [comment]
It seems that the discussion is gone? I was trying to figure out how much compatibility (if any) is there for Farmer's Delight cutting board recipes, and found this.
