### ISSUE TITLE
Euphoric Curiosity ~ Not working

### ISSUE THREAD

**Issue by Daemanis** [blay09/CookingForBlockheads#643]
### Minecraft Version

1.19.2 (LTS)

### Mod Loader

Forge

### Mod Loader Version

Fabric 0.14.12

### Mod Version

13.3.1

### Balm Version

4.5.2

### Describe the Issue

Adding this mod to the pack, the pack still works perfectly fine however though you can view the cooking for blockheads blocks, you cannot view their recipes, you cannot craft any of them, and if you try to place them using creative the block vanishes instantly

**Comment by BlayTheNinth** [comment]
This usually means that the mod isn't installed correctly on the server. Make sure you're using the correct version (depending on what mod loader your server uses, either Forge or Fabric) and check / post the server log for any issues related to `cookingforblockheads`.

**Comment by Daemanis** [comment]
> This usually means that the mod isn't installed correctly on the server. Make sure you're using the correct version (depending on what mod loader your server uses, either Forge or Fabric) and check / post the server log for any issues related to `cookingforblockheads`.

25.04 18:57:55 [Server] Server thread/[ERROR] [worlds_together] Error for jar:file:///mods/Cooking%20for%20Blockheads.jar: java.nio.file.NoSuchFileException: /fabric.mod.json

that is the only error on the server logs that have anything to do with Cooking for Blockheads

**Comment by BlayTheNinth** [comment]
That sounds like you downloaded the Forge version but are running a Fabric server. That filename also does not look like an official version (unless you renamed it yourself). Cooking for Blockheads is only available on [Modrinth](https://modrinth.com/mod/cooking-for-blockheads) and [CurseForge](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads-fabric).
