### ISSUE TITLE
Storage Drawers failure

### ISSUE THREAD

**Issue by chocolatechipcats** [blay09/CookingForBlockheads#644]
### Minecraft Version

1.19.2 (LTS)

### Mod Loader

Forge

### Mod Loader Version

Forge 43.2.8

### Mod Version

cookingforblockheads-forge-1.19.2-13.3.1.jar

### Balm Version

balm-forge-1.19.2-4.5.7.jar

### Describe the Issue

Trying to connect Storage Drawers (StorageDrawers-1.19-11.1.2) to my kitchen using the floor blocks and cabinets. It fails to detect any ingredients I put inside the storage drawer.

Issue #581 is about the same thing and is closed as 'completed' a few months before the release I use. (I asked there but I think it was missed.)

Thank you.

**Comment by BlayTheNinth** [comment]
Works without issues for me. Is it only Storage Drawers not working or do ~~chests~~ kitchen counters maybe have the same issue? I put wheat in a storage drawer connected to the cooking table and was able to craft bread just fine. Does it happen with only Storage Drawers and Cooking for Blockheads (+ Balm) installed?

**Comment by chocolatechipcats** [comment]
Chests (both default oak and additional ones added by mods) are failing as well. 🙁

**Comment by chocolatechipcats** [comment]
It works if I made a new Forge profile with only Balm, CFB, and Storage Drawers. I will test other mods and see if theres a conflict.

**Comment by chocolatechipcats** [comment]
It was bloody Optifine, of course.

**Comment by blahpers** [comment]
I'm having this issue with vanilla chests.  1.19.3, Forge, only mods are CfB, JEI, and Balm.  No Optifine.

Am I not connecting the chest with the cooking table properly?  I'm placing it right next to the cooking table.

**Comment by chocolatechipcats** [comment]
Are they both on kitchen floors?

**Comment by blahpers** [comment]
I believe so.

<img width="1087" alt="image" src="https://github.com/TwelveIterationMods/CookingForBlockheads/assets/609209/f2235e2d-71a2-44a2-babb-60b80ab7b04f">

**Comment by blahpers** [comment]
Silly question:  Do I need to make a custom compat .json for vanilla chests to work?

**Comment by chocolatechipcats** [comment]
I used a vanilla chest during my clean-install test. Is your Forge up-to-date? Sometimes I've seen slightly older versions cause funky issues.

**Comment by blahpers** [comment]
Running 44.1.23, which looks like the latest available for 1.19.3, at least through my launcher.  I'll try again with 1.20.1 and the corresponding Forge & CfB and see whether anything's different.

**Comment by BlayTheNinth** [comment]
Vanilla Chests are not supported by default; when I mentioned chests in my earlier comment I actually meant Kitchen Counters. So yes, chests would need a custom compat json.
