### ISSUE TITLE
Kitchen Blocks and possible others cause issues with FramedBlocks (was sent here from FB github)

### ISSUE THREAD

**Issue by xFirefalconx** [blay09/CookingForBlockheads#645]
### Minecraft Version

1.18.2

### Mod Loader

Forge

### Mod Loader Version

40.2.0

### Mod Version

12.2.0

### Balm Version

3.2.6

### Describe the Issue

In short, incompatibility that the FramedBlocks dev told me to refer to you as it's caused by the way the block color is derived - afaik.
What it looks like: Framed blocks that get covered with CookingForBlockheads kitchen tiles - go invisible and have no texture. 
I added this mod because there are no carpet like kitchen tiles and mend the issue that way - doesn't work without your help of fixing this incompatibility. 
The original discussion, if you want 100% to read into:

https://github.com/XFactHD/FramedBlocks/issues/265#issuecomment-1528005214
> I've looked into it and found that this needs to be fixed by Cooking for Blockheads. Their kitchen floor model does not specify the so-called cull-faces which tell the game that a certain surface of the block can be culled when it's covered by a neighboring block on the given side: https://github.com/TwelveIterationMods/CookingForBlockheads/blob/1.19.x/shared/src/main/resources/assets/cookingforblockheads/models/block/kitchen_floor.json#L12-L17. I rely on that information to get the model surfaces and transform then into the various shapes. Please report this to them with the above explanation.

A graphic to underline the issue visually, each invisible block should look like the floating full block above it. 
![grafik](https://user-images.githubusercontent.com/106652912/235316357-1d01a286-3c87-4e69-9242-1c109a50d8c5.png)

I don't think logs are necessary here, but I'll add one anyways. 

### Logs

https://gist.github.com/xFirefalconx/b05a104b5314a6ee1726200b0b846c3d

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Nope, just tested with all Vanilla.

**Comment by BlayTheNinth** [comment]
This is now fixed on 1.19+. For 1.18, you could use a resource pack to override the model to this: https://github.com/TwelveIterationMods/CookingForBlockheads/blob/e9949711585f48d36b8356bb754bb92f302890eb/shared/src/main/resources/assets/cookingforblockheads/models/block/kitchen_floor.json

**Comment by xFirefalconx** [comment]
> This is now fixed on 1.19+. For 1.18, you could use a resource pack to override the model to this: https://github.com/TwelveIterationMods/CookingForBlockheads/blob/e9949711585f48d36b8356bb754bb92f302890eb/shared/src/main/resources/assets/cookingforblockheads/models/block/kitchen_floor.json

Thank you, just because I am a bit confused, sorry, 
1. is the link a resource pack? idk what a resource pack is in essence.
2. what do I do? download this json in the link and put it in resource pack folder, done? 
3. does that work with each and every kitchen block, regardless of color?

**Comment by BlayTheNinth** [comment]
Here is a resource pack which you can put in the resource packs folder (without extracting it) and then enable in the Minecraft options ("Resource Packs").

[kitchenfloorfix.zip](https://github.com/TwelveIterationMods/CookingForBlockheads/files/11361958/kitchenfloorfix.zip)

**Comment by xFirefalconx** [comment]
Thank you! I did as you said and it works now! Thanks for being so kind and helping me out with the resource pack!
