### ISSUE TITLE
[Compatibility] Crash when using milk as texture for FramedBlocks

### ISSUE THREAD

**Issue by blahpers** [blay09/CookingForBlockheads#651]
### Minecraft Version

1.20.x

### Mod Loader

Forge

### Mod Loader Version

45.1.2

### Mod Version

15.0.2

### Balm Version

6.0.2

### Describe the Issue

FramedBlocks supports using a bucket of fluid on a framed block to give the block the texture of the fluid.  When I try this with the Milk fluid added/exposed by Cooking for Blockheads, the client crashes with an exception.

Steps to reproduce:
1. Place any framed block from the FramedBlocks mod (e.g., Framed Cube).
2. Equip a bucket of milk in the main hand.
3. Use (default to right-click) the bucket of milk on the placed framed block.

Expected result:
Framed block changes appearance from a hollow crate frame to the texture of the milk fluid.

Actual result:
Client crashes.

Mods used for test:
- Cooking for Blockheads 15.0.2
- FramedBlocks 8.0.2
- JEI 13.1.0.15
- Balm 6.0.2

Other notes:
This was originally discovered playing a larger modpack in Minecraft 1.19.3 (including CfB 14.0.2, Balm 5.0.4, FB 7.1.2)

### Logs

https://pastebin.com/VZfz7wcW

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Not required to reproduce bug

**Comment by BlayTheNinth** [comment]
The milk is added by Forge and only enabled by Cooking for Blockheads, it is up to FramedBlocks to handle the Forge milk edge case correctly.
