### ISSUE TITLE
[1.20.1] Anvil on cow over jar kills cow, no cow in a jar.

### ISSUE THREAD

**Issue by ProsperCraft** [blay09/CookingForBlockheads#652]
### Minecraft Version

1.20.x

### Mod Loader

Forge

### Mod Loader Version

forge-1.20.1-47.0.19

### Mod Version

cookingforblockheads-forge-1.20-16.0.0

### Balm Version

balm-forge-1.20-7.0.4

### Describe the Issue

When you place a jar, then push a cow over it, and drop an anvil on it, the cow dies instead of being put in the jar.  

I had this issue in 1.19 as well, and thought I had reported it, but I don't see the issue, may have been in Discord.

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

No

**Comment by BlayTheNinth** [comment]
Cannot reproduce. Are you using a vanilla cow?

![java_xFvWQZFwxr](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/1933180/73f7a478-b482-4e72-a547-0836fb8e5028)

**Comment by BlayTheNinth** [comment]
Is `cowJarEnabled` enabled in the config?
