### ISSUE TITLE
Make stove have capabilityu

### ISSUE THREAD

**Issue by Hirokoai** [blay09/CookingForBlockheads#654]
Mod compatibility for create mod specifically mechanical arm

**Comment by skyjay1** [comment]
To add more detail: The Forge version of the mod does not add Item Capabilities to blocks with inventories. This makes them incompatible with hoppers and mods that interact with inventories, such as Create or any generic Pipe mod.

Solution: Add item capabilities to CFB block entities from the CompatCapabilityLoader class

**Comment by BlayTheNinth** [comment]
Cooking for Blockheads already supports ItemHandler capabilities, including on the oven. Otherwise, hoppers would not work on them.
