### ISSUE TITLE
Worthy Food tools are incorrectly consumed during crafting

### ISSUE THREAD

**Issue by Morphyloon** [blay09/CookingForBlockheads#656]
### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Mod Loader Version

0.86.0+1.20.1

### Mod Version

16.0.0

### Balm Version

7.0.4

### Describe the Issue

When making any recipe from the mod "Worthy Food" (using version 1.2.0) that involves the tools from said mod (pot, pan, knife, etc) the tool is also consumed in the process when it should not. Worthy Food tools can be placed in the Cooking For Blockheads UI (tool rack, oven UI), but they are still consumed.

 The Worthy Food recipe properly works in any standard crafting table (shapeless 3x3 or 2x2 depending on the number of ingredients), returning the tool as it should.

**Comment by BlayTheNinth** [comment]
Fixed in Balm 8.0.2+
