### ISSUE TITLE
Add EnviroMine Compatibility

### ISSUE THREAD

**Issue by mrammy** [blay09/CookingForBlockheads#66]
compatibility for your refrigerators to keep EnviroMine from rotting foods. EnviroMine's freezer appears to slow to a complete halt, or its just so slow its impossible to tell. Maybe if you could add a "freezer" block that accomplishes the same thing or just add the EnviroMine freezer and esky to part of your multiblock structure detection so it can pull items from those inventories, or you could have your own blocks that use their API (if that's even possible), that are slightly slower rot speed (fridge) and completely frozen rot speed or super slow (freezer). I personally would prefer your models and renders on your own blocks, but 100% up to you =).

Thanks,
mrammy

**Comment by Forecaster** [comment]
Seconded!
+1
Etc.

**Comment by blay09** [comment]
It doesn't look like EnviroMine provides an API, so the most I can do is have the freezer act as a kitchen part.
