### ISSUE TITLE
[1.19.2] Bread in oven smelts into bread forever

### ISSUE THREAD

**Issue by SigmaFlame** [blay09/CookingForBlockheads#660]
### Minecraft Version

1.19.2 (LTS)

### Mod Loader

Forge

### Mod Loader Version

43.2.22

### Mod Version

13.3.2

### Balm Version

4.5.7

### Describe the Issue

Hello,

When you put bread into an oven or a toaster, the result is bread again.
So you can't waste coal or energy in the oven to make bread again and again.

### Logs

There is no log since there is no crash

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

No

**Comment by SigmaFlame** [comment]
Tested with and without Pam Harvestcraft and a toast item existing in the game, same result for the oven, but the toaster makes toast well.

**Comment by BlayTheNinth** [comment]
Being able to toast bread multiple times if no toast-adding mod is installed is intentional. You will find that the name of the bread is changing.

As for the furnace recipe, Cooking for Blockheads does not add a smelting recipe for bread, so that must be some other mod causing it.
