### ISSUE TITLE
Errore nell'avviare minecraft 1.19.2

### ISSUE THREAD

**Issue by ornitori** [blay09/CookingForBlockheads#663]
### Minecraft Version

1.19.2 (LTS)

### Mod Loader

Forge

### Mod Loader Version

Forge 1.19.2 43.2.23

### Mod Version

cookingforblockheads-forge-1.19.2-13.3.3

### Balm Version

balm-forge-1.19.2-4.6.0

### Describe the Issue

Avviando Minecraft Forge 1.19.2 43.2.23 provando con tutte le versioni della mod compatibili con la 1.19.2, mi da il seguente codice di errore:

Il gioco si è bloccato durante il rendering dell'overlay
Errore: net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: caricamento del file di configurazione cookingforblockheads-common.toml non riuscito di tipo COMMON per mod cookingforblockheads

Codice di uscita: -1

Inoltre prima funzionava e se metto la seguente versione di forge: 1.19.2-forge-43.2.0 funziona, ma altre mod richiedono la versione superiore di forge

Come posso risolvere?

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

utilizzo preview_OptiFine_1.19.2_HD_U_I1_pre4

**Comment by BlayTheNinth** [comment]
Try deleting your config file in `config/cookingforblockheads-common.toml` to reset it to defaults.

**Comment by ornitori** [comment]
Grezie mille
