### ISSUE TITLE
Shaped recipes with items below each other don't work

### ISSUE THREAD

**Issue by jinkhya** [blay09/CookingForBlockheads#665]
### Minecraft Version

1.20.x

### Mod Loader

Forge

### Mod Loader Version

Forge

### Mod Version

2.3.2

### Balm Version

7.1.4

### Describe the Issue

This what the recipe is : 
![image](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/10158963/ef163e89-5856-421e-9ef2-5f0ee155fe63)
This is what CFB is trying to do and doesn't work : 
![image](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/10158963/d709e928-60b5-4236-be89-56e6b005379d)

To reproduce install balm, croptopia (can probably be any mod that adds these kinds of recipes), CFB, EMI or JEI and try to craft ground pork or tea (the cup)

### Logs

https://gist.github.com/jinkhya/6f61375a5ca478c7eaf11d8f92d4045d

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

No

**Comment by NekoLeila** [comment]
It seems like a lot of croptopia recipes are broken in ATM9

**Comment by NekoLeila** [comment]
In the Cooking Table in ATM9*
