### ISSUE TITLE
Cooking for blockheads crashes on world load when i have these mods

### ISSUE THREAD

**Issue by eldritch-cookie** [blay09/CookingForBlockheads#672]
### Minecraft Version

1.20.2

### Mod Loader

Forge

### Mod Loader Version

fabric 0.14.24

### Mod Version

17.0.0

### Balm Version

8.0.1

### Describe the Issue

with this huge mod list i crash on world load, i am sorry for not providing a minimal reproduction but today i am just so exhausted so i really can't bisect the mods to know which one exactly introduces the incompatibility, i just thought it was better to write down somewhere that this crash happpens than to just do nothing and just uninstall the mod, i do know the issue doesn't happen with only cooking for blockheads installed
- [Conjuring](https://modrinth.com/mod/GriMtaoD) [1.0.29+1.20.2]
- [Shulker Box Tooltip](https://modrinth.com/mod/2M01OLQq) [4.0.7+1.20.2]
- [MCPitanLib](https://modrinth.com/mod/uNRoUnGT) [1.8.4-1.20.2-fabric]
- [MidnightLib](https://modrinth.com/mod/codAaoxh) [1.5.0]
- [Universal Shops](https://modrinth.com/mod/cnIatHrN) [1.4.0+1.20.2]
- [Immersive Ores](https://modrinth.com/mod/F9Vuwq3S) [1.20.2-0.3]
- [Beautify](https://modrinth.com/mod/DhSSvaxs) [1.0.0+1.20.2]
- [FastMove - Parkour Movement](https://modrinth.com/mod/XmqpPthc) [1.0.7]
- [Waystones](https://modrinth.com/mod/LOpKHB2A) [15.0.1]
- [Open Parties and Claims](https://modrinth.com/mod/gF3BGWvG) [0.20.0]
- [Language Reload](https://modrinth.com/mod/uLbm7CG6) [1.5.10+1.20.2]
- [Fabric Language Kotlin](https://modrinth.com/mod/Ha28R6CL) [1.10.15+kotlin.1.9.21]
- [Amecs](https://modrinth.com/mod/rcLriA4v) [1.3.11+mc.1.20.2]
- [Load My F***ing Tags](https://modrinth.com/mod/67kVxsaO) [1.0.2+1.20]
- [Resourceful Lib](https://modrinth.com/mod/G1hIVOrD) [2.2.4]
- [More Bows Restrung](https://modrinth.com/mod/CkMS2Yh3) [1.0.11+1.20.x]
- [Better Runtime Resource Pack (BRRP) v1](https://modrinth.com/mod/JnrDtPAE) [1.0.2]
- [NotEnoughAnimations](https://modrinth.com/mod/MPCX6s5C) [1.6.4]
- [Harvest with ease](https://modrinth.com/mod/W4Ajthd2) [8.0.0.0]
- [Architectury](https://modrinth.com/mod/lhGA9TYQ) [10.0.16]
- [FastBack](https://modrinth.com/mod/ZHKrK8Rp) [0.16.2+1.20.2-fabric]
- [Dynamic Fullbright](https://modrinth.com/mod/tF7P4IlX) [1.2.0]
- [Compressed Blocks](https://modrinth.com/mod/IQRVlbit) [1.4.2]
- [No More Useless Keys](https://modrinth.com/mod/YCcdA1Lp) [1.1.0+mc1.20.1]
- [Factions Mod](https://modrinth.com/mod/ZjwW8Q6n) [2.5.2]
- [Universal Graves](https://modrinth.com/mod/yn9u3ypm) [3.1.1+1.20.2]
- [More Stairs](https://modrinth.com/mod/TBkmYtP5) [1.20.2-1.0.5-[FABRIC]]
- [EnchantmentDescriptions](https://modrinth.com/mod/UVtY3ZAC) [18.0.3]
- [Armorful](https://modrinth.com/mod/LlOkR2e2) [2.0.3+1.20.2]
- [NetherPortalFix](https://modrinth.com/mod/nPZr02ET) [14.0.0]
- [Not Enough Crashes](https://modrinth.com/mod/yM94ont6) [4.4.6+1.20.2]
- [Better Furnaces Reforged](https://modrinth.com/mod/ZXOYCX2A) [1.0.2]
- [Better Statistics Screen](https://modrinth.com/mod/n6PXGAoM) [3.5.2+fabric-1.20.2]
- [Krypton](https://modrinth.com/mod/fQEb0iXm) [0.2.4]
- [Terra](https://modrinth.com/mod/FIlZB9L0) [6.4.1-BETA+3aef97738]
- [Dynamic FPS](https://modrinth.com/mod/LQ3K71Q1) [3.2.1]
- [Additional Lanterns](https://modrinth.com/mod/jXNvTKds) [1.1.1]
- [DirectionHUD](https://modrinth.com/mod/H8WCXRtb) [1.5.3+1.20-1.20.2]
- [Handcrafted](https://modrinth.com/mod/pJmCFF0p) [3.1.0]
- [More Fences](https://modrinth.com/mod/R6vtGMF3) [1.20.2-1.0.5-[FABRIC]]
- [AttributeFix](https://modrinth.com/mod/lOOpEntO) [22.0.2]
- [Noxesium](https://modrinth.com/mod/Kw7Sm3Xf) [1.0.5+f253e35]
- [Forge Config API Port](https://modrinth.com/mod/ohNO6lps) [9.0.0]
- [Elytra Trinket](https://modrinth.com/mod/wk57PrDM) [1.0.5]
- [Xaero's Minimap](https://modrinth.com/mod/1bokaNcj) [23.9.0]
- [Resourcefulconfig](https://modrinth.com/mod/M1953qlQ) [2.2.1]
- [Xaero's World Map](https://modrinth.com/mod/NcUtCpym) [1.37.0]
- [SimpleRepair](https://modrinth.com/mod/orypIQ4M) [1.0.0]
- [Better Combat](https://modrinth.com/mod/5sy6g3kz) [1.8.1+1.20.2]
- [Command Macros](https://modrinth.com/mod/h3r1moh7) [1.6.3-1.20.2]
- [Item Alchemy](https://modrinth.com/mod/cfQx2fbQ) [0.7.6]
- [Advanced Networking](https://modrinth.com/mod/IF0Y4xFw) [3.0.0+mc.1.20.2]
- [EntityCulling-Fabric](https://modrinth.com/mod/NNAgCjsB) [1.6.2-mc1.20.1]
- [Cloth Config v12](https://modrinth.com/mod/9s6osm5g) [12.0.111]
- [SuperMartijn642's Config Lib](https://modrinth.com/mod/LN9BxssP) [1.1.8+a]
- [Scannable](https://modrinth.com/mod/YqFnwJHf) [1.7.12+18ccb75]
- [oωo](https://modrinth.com/mod/ccKDOlHs) [0.11.3+1.20.2]
- [libIPN](https://modrinth.com/mod/onSQdWhM) [4.0.1]
- [AppleSkin](https://modrinth.com/mod/EsAfCjCV) [2.5.1+mc1.20.2]
- [Numismatic Overhaul](https://modrinth.com/mod/ZXm8hVxN) [0.2.10+1.20.2]
- [Interactic](https://modrinth.com/mod/ErpAAAaf) [0.2.1+1.20.2]
- [Jade](https://modrinth.com/mod/nvQzSEkH) [12.2.1]
- [Blackwolf Library](https://modrinth.com/mod/mskYGmCA) [1.20.2-1.0.5-[FABRIC]]
- [Mythic Upgrades](https://modrinth.com/mod/ERH7cFoy) [2.3.2+mc1.20.2]
- [Factory API](https://modrinth.com/mod/nkTZHOLD) [2.0]
- [The Bumblezone - Fabric](https://modrinth.com/mod/eA8SXqWL) [7.2.2+1.20.2-fabric]
- [Trinkets](https://modrinth.com/mod/5aaWibi9) [3.8.0]
- [Forgiving Void](https://modrinth.com/mod/1vkzEZjE) [11.0.0]
- [More Slabs](https://modrinth.com/mod/wcpPgNHy) [1.20.2-1.0.5-[FABRIC]]
- [Stendhal](https://modrinth.com/mod/BWloQ9jK) [1.4.0-1.20.2]
- [Inventory Profiles Next](https://modrinth.com/mod/O7RBXm3n) [1.10.9]
- [Building Wands](https://modrinth.com/mod/XkisZUfp) [2.6.8-release]
- [Things](https://modrinth.com/mod/VzAGdu9D) [0.3.2+1.20.2]
- [OpenLoader](https://modrinth.com/mod/KwWsINvD) [20.0.5]
- [Iron Chests](https://modrinth.com/mod/7mHyGgvW) [2.0.1]
- [Lighty](https://modrinth.com/mod/yjvKidNM) [2.1.2+1.20.2]
- [More Trapdoors](https://modrinth.com/mod/7kxOSaZm) [1.20.2-1.0.6-[FABRIC]]
- [Lithium](https://modrinth.com/mod/gvQqBUqZ) [0.12.0]
- [Infusion Table](https://modrinth.com/mod/W9CiRGYK) [1.2.0]
- [VaultPatcher](https://modrinth.com/mod/NLV0Mnpu) [1.3.5+6]
- [More Carpets](https://modrinth.com/mod/VWAugYdy) [1.20.2-1.0.5-[FABRIC]]
- [LambDynamicLights](https://modrinth.com/mod/yBW8D80W) [2.3.3+1.20.2]
- [REI Collapsible Entries QOL](https://modrinth.com/mod/lvuenewC) [1.0.1]
- [Bosses of Mass Destruction (Beta)](https://modrinth.com/mod/du3UfiLL) [1.7.3-1.20.2]
- [Indium](https://modrinth.com/mod/Orvt0mRa) [1.0.27+mc1.20.1]
- [Book of Experience](https://modrinth.com/mod/KfqvJMNp) [3.1.0]
- [Roughly Enough Items](https://modrinth.com/mod/nfn13YXA) [13.0.678]
- [Energized Power](https://modrinth.com/mod/6pku8gW1) [1.20.2-2.6.0-fabric]
- [Iron Bookshelves](https://modrinth.com/mod/QmCOBeSP) [1.20.2-1.2.3-fabric]
- [Mob Filter](https://modrinth.com/mod/gRn1FzwR) [0.6.0+1.20.2]
- [Yet Another Cobblestone Generator](https://modrinth.com/mod/xPsKRMUF) [2023.11.1]
- [Pufferfish's Skills](https://modrinth.com/mod/hqQqvaa4) [0.10.0]
- [More Walls](https://modrinth.com/mod/wdEiEKti) [1.20.2-1.0.6-[FABRIC]]
- [Ping Wheel](https://modrinth.com/mod/QQXAdCzh) [1.7.0]
- [Traveler's Backpack](https://modrinth.com/mod/rlloIFEV) [1.20.2-9.2.3]
- [Wireless Chargers](https://modrinth.com/mod/nCk7Sfz8) [1.0.9]
- [Dynamic Asset Generator](https://modrinth.com/mod/83pFEQVb) [5.0.0]
- [More Player Badges](https://modrinth.com/mod/R3CET9PN) [1.0+fabric-1.20.2]
- [Cardinal Components API](https://modrinth.com/mod/K01OU20C) [5.3.0]
- [Industrial Quarry Mod](https://modrinth.com/mod/Hg6ZLVmu) [1.2.0]
- [More Doors](https://modrinth.com/mod/OWP2vqo0) [1.20.2-1.0.6-[FABRIC]]
- [Magic Mirror](https://modrinth.com/mod/1d2CrxHN) [1.0.0]
- [ImmediatelyFast](https://modrinth.com/mod/5ZwdcRci) [1.2.7+1.20.2]
- [Collective](https://modrinth.com/mod/e0M1UDsY) [7.8]
- [Extra Alchemy](https://modrinth.com/mod/n0S5OkPo) [1.11.1]
- [Fabric API](https://modrinth.com/mod/P7dR8mSH) [0.91.1+1.20.2]
- [Balm](https://modrinth.com/mod/MBAkmtvl) [8.0.1]
- [Alternate Current](https://modrinth.com/mod/r0v8vy1s) [1.7.0]
- [Tesseract](https://modrinth.com/mod/OUhp5O2m) [1.0.35]
- [Bookshelf](https://modrinth.com/mod/uy4Cnpcm) [21.0.11]
- [Comforts](https://modrinth.com/mod/SaCpeal4) [7.0.1+1.20.2]
- [Forgero](https://modrinth.com/mod/wxKGvopS) [0.11.5+1.20.2]
- [Better Mount HUD](https://modrinth.com/mod/kqJFAPU9) [1.2.2]
- [Tech Reborn](https://www.curseforge.com/projects/233564) [5.9.1]
- [GeckoLib 4](https://modrinth.com/mod/8BmcQJ2H) [4.2.4]
- [Better Totem of Undying [FABRIC]](https://modrinth.com/mod/qRwFcI3W) [1.1.1]
- [Red Bits](https://modrinth.com/mod/u6AMJBvu) [1.16.2]
- [Labelling Containers](https://modrinth.com/mod/b2T42hfY) [1.3.0-mc1.20.2]
- [Additional Structures](https://modrinth.com/mod/TWsbC6jW) [4.2.1]
- [Roughly Enough Professions](https://modrinth.com/mod/V8XJ8f5f) [2.1.0]
- [Easy Authentication Mod](https://modrinth.com/mod/aZj58GfX) [3.0.19]
- [Nature's Compass](https://modrinth.com/mod/fPetb5Kh) [1.20.2-2.2.3-fabric]
- [Tree Harvester](https://modrinth.com/mod/abooMhox) [8.3]
- [More Pressure Plates](https://modrinth.com/mod/1O2Oukf5) [1.20.2-1.0.6-[FABRIC]]
- [FerriteCore](https://modrinth.com/mod/uXXizFIs) [6.0.1]
- [Crystals Overhauled](https://modrinth.com/mod/F5ao3BYo) [1.6.0]
- [Mod Menu](https://modrinth.com/mod/mOgUt4GM) [8.0.0]
- [spark](https://modrinth.com/mod/l6YH9Als) [1.10.54]
- [BetterF3](https://modrinth.com/mod/8shC1gFX) [8.0.2]
- [Cooking for Blockheads](https://modrinth.com/mod/vJnhuDde) [17.0.0]
- [Iris](https://modrinth.com/mod/YL57xq9U) [1.6.10]
- [Item Collectors](https://modrinth.com/mod/y9vDr4Th) [1.1.8]
- [SuperMartijn642's Core Lib](https://modrinth.com/mod/rOUBggPv) [1.1.15]
- [Packed Up](https://modrinth.com/mod/ZbFzEauY) [1.0.30]
- [Extended Drawers](https://modrinth.com/mod/AhtxbnpG) [2.0.8+mc.1.20.2]
- [Excavated Variants](https://modrinth.com/mod/IZaMGxb0) [4.0.0]
- [Notes](https://modrinth.com/mod/ko8Qabo1) [1.20.2-2.1.0-fabric]
- [Debugify](https://modrinth.com/mod/QwxR6Gcd) [1.20.2+1.0]
- [Explorer's Compass](https://modrinth.com/mod/RV1qfVQ8) [1.20.2-2.2.3-fabric]
- [More Buttons](https://modrinth.com/mod/yZlTasvQ) [1.20.2-1.0.5-[FABRIC]]
- [Polymer](https://modrinth.com/mod/xGdtZczs) [0.6.3+1.20.2]
- [Trash Cans](https://modrinth.com/mod/4QrnfueM) [1.0.18]
- [Additional Additions](https://modrinth.com/mod/R4TvILfj) [6.0.2]
- [Tom's Simple Storage Mod](https://modrinth.com/mod/XZNI4Cpy) [1.6.8]
- [Wormhole (Portals)](https://modrinth.com/mod/6nHZTTjQ) [1.1.15]
- [Chalk](https://modrinth.com/mod/OrtjXTCH) [2.3.0]
- [Sodium](https://modrinth.com/mod/AANobbMI) [0.5.3]
- [Advanced Netherite](https://modrinth.com/mod/CFX9ftUJ) [2.0.2-1.20.2]
- [Light Emitting Diode](https://modrinth.com/mod/nrekn9hP) [1.7.0]
- [ModernFix](https://modrinth.com/mod/nmDcB62a) [5.9.3+mc1.20.2]

### Logs

https://gist.github.com/eldritch-cookie/4bb48323182373130c300de32ec3868f

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

sodium, indium, krypton, modern fix and immediately fast

**Comment by BlayTheNinth** [comment]
It's caused by one of the mods that haven't been updated to 1.20.2, specifically one adding a shapeless recipe.

Minecraft 1.20.1 is not compatible with 1.20.2 and you will likely run into similar crashes in other places even without Cooking for Blockheads when running 1.20.1 mods on 1.20.2.

**Comment by eldritch-cookie** [comment]
i've got my game to run and when i add cooking for blockheads it does load a world, but i've gave up for now running on 1.20.2
