### ISSUE TITLE
Some Kitchen Cabinets have black handles

### ISSUE THREAD

**Issue by EPSIL0N** [blay09/CookingForBlockheads#684]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Forge

### Mod Loader Version

47.2.19

### Mod Version

16.0.1

### Balm Version

7.2.1

### Describe the Issue

![image](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/5761561/a2d03883-6223-4a96-8003-decedfa5e1fd)

Certain locations seem to have cabinets with black handles but then a block or two away the handles are white, I couldn't seem to figure out what I might be doing to cause it.

**Comment by BlayTheNinth** [comment]
Fixed in Minecraft 1.20.4+
