### ISSUE TITLE
Fridge placing crash

### ISSUE THREAD

**Issue by leopalladium** [blay09/CookingForBlockheads#685]
### Minecraft Version

1.20.4

### Mod Loader

Forge

### Mod Loader Version

49.0.19

### Mod Version

1.20.2-17.0.1

### Balm Version

9.0.5

### Describe the Issue

Crash when trying to place Fridge. Aternos server. Automatically kicks everyone from the server and it's unable to connect. Game crashes. 
`The game crashed whilst unexpected error Error: java.lang.NoSuchMethodError: 'void net.minecraft.world.phys.AABB.<init>(net.minecraft.core.BlockPos, net.minecraft.core.BlockPos)'`

- cloth-config-13.0.121-forge.jar
- pamhc2foodcore-1.20.4-1.0.5.jar

### Logs

https://pastebin.com/jTVn1hyT

**Comment by BlayTheNinth** [comment]
Minecraft 1.20.2 is not compatible with 1.20.4. 

Cooking for Blockheads is not yet available for 1.20.4.
