### ISSUE TITLE
With Croptopia, when you create a food that requires a tool, the tool disappears after creation.

### ISSUE THREAD

**Issue by NekopasCraft** [blay09/CookingForBlockheads#691]
### Minecraft Version

1.20.4

### Mod Loader

Forge

### Mod Loader Version

49.0.27

### Mod Version

18.0.4

### Balm Version

9.0.6

### Describe the Issue

When using Croptopia, if you create a food that requires tools, the tool placed in the tool rack or oven will disappear after creation.
If created directly using the workbench, the tool will not disappear.

Using "Croptopia 3.0.4"

**Comment by StriderTR** [comment]
Sorry about the duplicate post. That's what I get for doing this at almost 3AM. 

I see it's been addressed already and moved up the to-do list. So, thank you very much! Keep up the amazing work!
