### ISSUE TITLE
Cooking for blockheads dont work on fabric with Paladin's Furniture Mod

### ISSUE THREAD

**Issue by DiogoSota03** [blay09/CookingForBlockheads#697]
### Minecraft Version

1.20.4

### Mod Loader

Forge

### Mod Loader Version

1.20.4 (Most recent)

### Mod Version

1.20.4 (Most recent)

### Balm Version

Most recent

### Describe the Issue

Cooking for blockheads dont work on fabric with Paladin's Furniture Mod, the game always crash when i try to launch it, everything is updated, i can run them with other mods, but not connected, sorry for my bad english, i love cooking for blackheads, can you guys fix it? <3

**Comment by BlayTheNinth** [comment]
Please provide the full logs. You can find the logs in the `logs` directory of the client or server. Most of the time `latest.log` is the correct file (unless the crash or issue happened during an earlier run).

Logs can be uploaded here by dragging the file into the comment field, or you can post them on a site like https://gist.github.com/ or https://pastebin.com/. Make sure they are set to be `public` (or unlisted) and to `never expire`.

**Comment by DiogoSota03** [comment]
Im sorry for my late response, im kinda new to all this, (i use fabric, sodium)
im glad you guys answered, i think this is you guys want...idk, i hope is this, thank you guys <33 love your mod
[latest.log](https://github.com/TwelveIterationMods/CookingForBlockheads/files/14808823/latest.log)

**Comment by BlayTheNinth** [comment]
It needs to be a crash report (which are stored separately as well) or the latest.log from when the crash happened. The latest.log you posted does not contain any crashes.
