### ISSUE TITLE
Cooking For Blockhead doesn't work with ProminenceII Rpg

### ISSUE THREAD

**Issue by Louidgee** [blay09/CookingForBlockheads#701]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Fabric

### Mod Loader Version

Fabric0.14.25

### Mod Version

16.0.4

### Balm Version

1.20.1 7.1.4

### Describe the Issue

All the ''cooking for blockhead'' blocks cannot be placed in my ProminenceII(RPG) world without despawning. They cannot be crafted either. 

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

no

**Comment by BlayTheNinth** [comment]
Blocks disappearing or being uncraftable usually means the mod is not correctly installed on the server.
