### ISSUE TITLE
Kitchen sink doesnt supply any water to create pipes/ae2

### ISSUE THREAD

**Issue by MrStickyPiston** [blay09/CookingForBlockheads#703]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Fabric

### Mod Loader Version

0.15.10

### Mod Version

16.0.4

### Balm Version

7.2.2

### Describe the Issue

![2024-05-08_15 55 57](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/97804691/2a454db3-3989-40d2-a7cd-5b8d84578d77)
It says unattached, while the sink is in front of it

in config, sinkRequiresWater = false

### Logs

https://mclo.gs/53ni1kF

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

sodium lithium ferritecore memoryleakfix starlight enhanced block entitys clumps

**Comment by MrStickyPiston** [comment]
![2024-05-08_16 10 14](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/97804691/2ba4cceb-5fbc-4a54-a17c-cd29e622aeea)
also a create screenshot

**Comment by MrStickyPiston** [comment]
![2024-05-08_16 16 52](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/97804691/234ad842-2f7a-4cbb-9f9e-5976a6bbf3ac)
minimal reproducible with 

  [✔] appliedenergistics2-fabric-15.1.0
  [✔] balm-fabric-1.20.1-7.2.2
  [✔] cookingforblockheads-fabric-1.20.1-16.0.4
  [✔] create-fabric-0.5.1-f-build.1417+mc1.20.1
  [✔] fabric-api-0.92.1+1.20.1

**Comment by MrStickyPiston** [comment]
This happens when on neoforge: (expected behaviour)
![2024-05-08_14 22 43](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/97804691/98cae970-6847-4a4d-b0cf-eb173c279a3c)
![2024-05-08_14 22 48](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/97804691/c7645648-4f08-4ea0-a00b-a4278d56e86f)

  [✔] appliedenergistics2-forge-15.1.1
  [✔] balm-forge-1.20.1-7.2.2
  [✔] cookingforblockheads-forge-1.20.1-16.0.4
  [✔] create-1.20.1-0.5.1.f

**Comment by BlayTheNinth** [comment]
Fixed in latest Balm
