### ISSUE TITLE
Crashing when launching the game with Paladin's Furniture Mod

### ISSUE THREAD

**Issue by Rema0000000** [blay09/CookingForBlockheads#707]
### Minecraft Version

1.20.4

### Mod Loader

Fabric

### Mod Loader Version

0.15.11

### Mod Version

18.0.5

### Balm Version

9.0.9

### Describe the Issue

Just after launching the game, it crashes, same occurs when starting a server with Cooking for Blockheads and Paladin's Furniture Mod in it.

Here's the log: 
[crash-2024-06-08_04.06.41-client.txt](https://github.com/user-attachments/files/15746309/crash-2024-06-08_04.06.41-client.txt)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Sodium/Indium (not sure if they count as that)

**Comment by Rema0000000** [comment]
Also tried to give the server's crash report but it doesnt give any so I just copied what appeared in the console (I think it's similar to the client one). Thanks ^^
[Server_crash.txt](https://github.com/user-attachments/files/15746323/Server_crash.txt)

**Comment by BlayTheNinth** [comment]
Paladin's Furniture Mod is referencing API classes that no longer exist. Cooking for Blockheads' API was changed in 1.20.4+. This must be fixed on their side.

**Comment by Rema0000000** [comment]
Oh okay, thank you so much, I’ll try to tell it to their support ^^
