### ISSUE TITLE
Duping with a kitchen cabinet

### ISSUE THREAD

**Issue by funnycubeguy** [blay09/CookingForBlockheads#708]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Forge

### Mod Loader Version

1.20.1

### Mod Version

cookingforblockheads-forge-1.20.1-16.0.4.jar

### Balm Version

balm-forge-1.20.1-7.2.2.jar

### Describe the Issue

Dupe with create + kitchen cabinet. Doesn't let you open with other blocks.

https://streamable.com/wup7qe

**Comment by BlayTheNinth** [comment]
This is already fixed in 16.0.6.
