### ISSUE TITLE
[1.21] Crash during game load: Duplicate cauldron registration

### ISSUE THREAD

**Issue by FreeFull** [blay09/CookingForBlockheads#710]
### Minecraft Version

Other (specify below)

### Mod Loader

NeoForge

### Mod Loader Version

21.0.6-beta

### Mod Version

21.0.1

### Balm Version

21.0.4

### Describe the Issue

When loading Minecraft 1.21 with Cooking for Blockheads, the game runs into an error. All that's needed are the latest version of NeoForge, Balm and Cooking for Blockheads.

### Logs

https://gist.github.com/FreeFull/18073cdc62ca29f37de91ebb3960842d

**Comment by BlayTheNinth** [comment]
Fixed in Balm 21.0.5
