### ISSUE TITLE
Outer corner connectors

### ISSUE THREAD

**Issue by elektronemulo** [blay09/CookingForBlockheads#713]
The connectors that go in an inside corner need a outside corner variant.

The outside corner would be used to wrap a countertop or cabinets around a column. The column could hide pipes/conduits to provide power/fluid/items.

![image](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/20167300/bfea1b27-8efe-46b5-ae27-9669723c1463)

Thanks for an awesome mod!

**Comment by BlayTheNinth** [comment]
They act the same way as stairs, so they already have an outside corner variant.
