### ISSUE TITLE
Jade integration is a bit broken with Cow in a Jar and Milk Jar.

### ISSUE THREAD

**Issue by StupidRepo** [blay09/CookingForBlockheads#714]
### Minecraft Version

1.21

### Mod Loader

Fabric

### Mod Loader Version

0.15.11

### Mod Version

21.0.1

### Balm Version

21.0.8

### Describe the Issue

When the Milk Jar is empty, Jade will show "Empty" at the top with the little background 'progress bar'.
When the Milk Jar/Cow in a Jar is not empty, nothing shows at the top. This is a bit sad as I can't see how full the jars are.

Keep in mind it works fine with sinks, showing "Water 26.51 kB".

![image](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/69256931/0ac3f79e-ddbf-4f6e-8c7c-015a6a43253d)

When full ^

![image](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/69256931/1dec4b29-9392-4a29-a59f-e6edd005a99e)

When empty ^

(Ignore the different names, it still happens with both jar types)

**Comment by BlayTheNinth** [comment]
Should be fixed in the latest version of Balm.

**Comment by StupidRepo** [comment]
Awesome! Thank you!
