### ISSUE TITLE
Crash with Tech Reborn fluid containers.

### ISSUE THREAD

**Issue by GoldenFurredFox** [blay09/CookingForBlockheads#724]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Fabric

### Mod Loader Version

0.15.11

### Mod Version

16.0.6

### Balm Version

7.3.7

### Describe the Issue

When you view anything Tech Reborn related in REI, REI crashes with fluid handler errors.

Open your inventory
Search "flui"
REI crashes with an error related to balm_fabric:milk

REI should not be crashing here.

### REI version

12.1.750

### Tech Reborn version

5.8.7

### Logs

https://gist.github.com/SamHammie/2574fe9bc497bcd952317026e1b1ef31

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Yes, performance enhancing mods.

**Comment by BlayTheNinth** [comment]
This is already fixed in Balm 7.3.9.
