### ISSUE TITLE
Translation broken & missing on some dyeable Kitchen Block

### ISSUE THREAD

**Issue by hibiyasleep** [blay09/CookingForBlockheads#727]
### Security Notice

- [X] Users might post VIRUS LINKS in comment responses to issue reports. **DO NOT DOWNLOAD ANY FILES FROM HERE.**

### Minecraft Version

1.21.1

### Mod Loader

Fabric

### Mod Loader Version

n/a

### Mod Version

21.1.2

### Balm Version

21.0.19

### Describe the Issue

due to uncolored Oven replaced by White Oven (and more), these translation are missing.

- ko_kr.json have `block.cookingforblockheads.oven` but no `block.cookingforblockheads.white_oven`
  ![image](https://github.com/user-attachments/assets/362b2c9f-1568-41c0-b4e1-94c6e6018cc6)

I could PR this, however my language isn't only affecting language, so opening bug for tracking them.

### Logs

n/a

**Comment by BlayTheNinth** [comment]
Translations are provided by community members, including any updates to them.

I generally do not track outdated translations as issues as it would clutter up the issue tracker with things that I personally can't do anything about other than wait for someone to submit updated translations.
