### ISSUE TITLE
Preservation Chamber upgrade only applies 

### ISSUE THREAD

**Issue by Gaz492** [blay09/CookingForBlockheads#731]
### Minecraft Version

Other (specify below)

### Mod Loader

NeoForge

### Mod Version

cookingforblockheads-neoforge-1.20.4-18.0.8.jar

### Describe the Issue

Double fridge multiblock with the preservation chamber upgrade still allows you to deplete an item

Steps to reproduce:
1. Place 2 fridges down on top of each other
2. Apply a preservation chamber to the top fridge
3. If you have jade installed, notice that the upgrade only shows up on the bottom block of the fridge
4. Using a cooking table placed adjacent to the fridge, use the items in the fridge until it consumes every item

Linking this for tracking purposes https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6001

### Logs

N/A

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge or Arclight)?

embeddium

**Comment by GoodSoup03** [comment]
Can this fix be backported to 1.21.1 for all the mods 10?
