### ISSUE TITLE
Other buckets (miner delight and wooden/ceramic bucket)

### ISSUE THREAD

**Issue by SigmaFlame** [blay09/CookingForBlockheads#732]
### Minecraft Version

Other (specify below)

### Mod Loader

Forge

### Mod Version

1.19.2-1.3.3.4

### Describe the Issue

When clicking on a sink with a bucket from another mod (miner's delight and wooden/ceramic bucket) the bucket full of liquid become an empty iron bucket, allowing transforming a copper/wooden/clay bucket to an iron one.
It is possible to fix that bug for 1.19.2 please? Thank you in advance.

### Logs

There's no crash so there's no log.

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge or Arclight)?

No

**Comment by BlayTheNinth** [comment]
Cannot reproduce in 1.20.1 or 1.21.1 so this was likely fixed at some point.

Minecraft 1.19.2 is no longer supported.
