### ISSUE TITLE
Fabric Backport for 1.20.1

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [blay09/CookingForBlockheads#739]
It'd be amazing if this mod could be backported for Fabric into mc 1.20.1

**Comment by BlayTheNinth** [comment]
Cooking for Blockheads has been available for Fabric since 1.18.2.

https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads-fabric/files/all?page=1&pageSize=20&version=1.20.1
