### ISSUE TITLE
Hoppers not inputting into CfB containers

### ISSUE THREAD

**Issue by Frost-System** [blay09/CookingForBlockheads#741]
### Minecraft Version

1.21.3

### Mod Loader

NeoForge

### Mod Version

21.1.3

### Describe the Issue

Hoppers in any orientation/relation to the block [I tested with top, front, side, and back of both the kitchen counter and the fridge] will not input items into the container, as if there is no inventory present.
Issue is present even when no other mods are present in a pack / new install.

### Logs

[latest.log](https://github.com/user-attachments/files/18001580/latest.log)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge or Arclight)?

no

**Comment by kotx** [comment]
Possibly related to #654?

**Comment by NekoLeila** [comment]
Just updated to the latest version and am still having this problem
