### ISSUE TITLE
Exit code -1

### ISSUE THREAD

**Issue by Scorpions95** [blay09/CookingForBlockheads#742]
### Minecraft Version

1.21.3

### Mod Loader

NeoForge

### Mod Version

1.21.4

### Describe the Issue

The game crashed whilst rendering block entity
Error: java.lang.IllegalStateException: Tried to access deferred object before it was resolved.
![Screenshot 2024-12-10 010104](https://github.com/user-attachments/assets/e6803d4b-e1f6-4e0e-af01-3aa5e7c900ed)

### Logs

[crash-2024-12-10_01.02.36-client.txt](https://github.com/user-attachments/files/18069071/crash-2024-12-10_01.02.36-client.txt)

**Comment by westcard** [comment]
I am having the same issue when trying to place any kitchen block other then the Cooking table and floors.  It immediately crashes.  Minecraft 1.21.4 with Neoforge 21.4.27.  I have to remove the mod and have the server remove all entities then re-add the mod.  I do not have any performance mods on the server yet.
