### ISSUE TITLE
How about AppleMilkTea support ?

### ISSUE THREAD

**Issue by bakaxyf** [blay09/CookingForBlockheads#78]

**Comment by blay09** [comment]
What of it needs special support?

**Comment by bakaxyf** [comment]
* Show all its food recipes
* Make its cooking machines can be used in Multiblock Kitchens
* Don't some recipe compressed foods like [VegiBag] (https://github.com/defeatedcrow/AppleMilkTea2_1.7.10/blob/master/resources/assets/dcsapplemilk/lang/en_US.lang#L81-L90)

**Comment by BlayTheNinth** [comment]
Feel free to re-open once it reaches Minecraft 1.9.4.
