### ISSUE TITLE
The Item Unloader in Railcraft can not test that a big firdge is the same  container

### ISSUE THREAD

**Issue by IamAchang** [blay09/CookingForBlockheads#87]
I think this picture can show what I mean =3

![qq 20150929122906](https://cloud.githubusercontent.com/assets/12226796/10155825/4ad7663c-66ac-11e5-9eee-6731afdc9cc3.png)
![qq 20150929122840](https://cloud.githubusercontent.com/assets/12226796/10155827/4f069066-66ac-11e5-8994-26e1ddd385cd.png)
![qq 20150929122847](https://cloud.githubusercontent.com/assets/12226796/10155828/5102169c-66ac-11e5-9e81-8d9b3f0b2a58.png)

**Comment by UUUii** [comment]
In this scenario, the Item Unloader can only detection the lower part of the large refrigerator.
