### ISSUE TITLE
Cooking Oven Crash 

### ISSUE THREAD

**Issue by KurtBuscus** [blay09/CookingForBlockheads#89]
This was in the "Blightfall" modpack

Log time

---- Minecraft Crash Report ----
// My bad.

Time: 9/29/15 7:44 PM
Description: Ticking memory connection

java.lang.ClassCastException: net.blay09.mods.cookingbook.block.TileEntityCookingTable cannot be cast to net.blay09.mods.cookingbook.block.TileEntityCookingOven
at net.blay09.mods.cookingbook.block.BlockCookingOven.func_149749_a(BlockCookingOven.java:161)
at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
at net.minecraft.world.World.func_147465_d(World.java:451)
at net.minecraft.world.World.func_147468_f(World.java:573)
at net.minecraft.block.Block.removedByPlayer(Block.java:1341)
at net.minecraft.block.Block.removedByPlayer(Block.java:1335)
at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:247)
at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:296)
at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:217)
at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:498)
at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at net.blay09.mods.cookingbook.block.BlockCookingOven.func_149749_a(BlockCookingOven.java:161)
at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
at net.minecraft.world.World.func_147465_d(World.java:451)
at net.minecraft.world.World.func_147468_f(World.java:573)
at net.minecraft.block.Block.removedByPlayer(Block.java:1341)
at net.minecraft.block.Block.removedByPlayer(Block.java:1335)
at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:247)
at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:296)
at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:217)
at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:498)
at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
Connection: net.minecraft.network.NetworkManager@4748661
Stacktrace:
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 8.1 (amd64) version 6.3
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 3181565760 bytes (3034 MB) / 3946840064 bytes (3764 MB) up to 4294967296 bytes (4096 MB)
Mod Pack: Unknown / None
LiteLoader Mods: 2 loaded mod(s)
- VoxelMap version 1.5.13
- Mouse Tweaks version 2.4.4
LaunchWrapper: 44 active transformer(s)
- Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
- Transformer: squeek.applecore.asm.TransformerModuleHandler
- Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
- Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
- Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
- Transformer: appeng.transformer.asm.ASMIntegration
- Transformer: com.wirsbo.main.ClassTransformer
- Transformer: net.technicpack.blightcore.coremod.BlightCoreClassTransformer
- Transformer: codechicken.lib.asm.ClassHeirachyManager
- Transformer: codechicken.core.asm.InterfaceDependancyTransformer
- Transformer: codechicken.core.asm.TweakTransformer
- Transformer: codechicken.core.asm.DelegatedTransformer
- Transformer: codechicken.core.asm.DefaultImplementationTransformer
- Transformer: invtweaks.forge.asm.ContainerTransformer
- Transformer: mcp.mobius.mobiuscore.asm.CoreTransformer
- Transformer: net.technicpack.newradicalbotany.coremod.NewRadicalBotanyClassTransformer
- Transformer: codechicken.nei.asm.NEITransformer
- Transformer: net.technicpack.notimefix.coremod.NoTimeFixClassTransformer
- Transformer: api.player.forge.PlayerAPITransformer
- Transformer: thaumic.tinkerer.preloader.AccessTransformer
- Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
- Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
- Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
- Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
- Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
- Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
- Transformer: appeng.transformer.asm.ASMTweaker
- Transformer: net.technicpack.blightcore.coremod.BlightCoreAccessTransformer
- Transformer: codechicken.core.asm.CodeChickenAccessTransformer
- Transformer: cofh.asm.CoFHAccessTransformer
- Transformer: invtweaks.forge.asm.ITAccessTransformer
- Transformer: net.technicpack.newradicalbotany.coremod.NewRadicalBotanyAccessTransformer
- Transformer: net.technicpack.notimefix.coremod.NoTimeFixAccessTransformer
- Transformer: thaumic.tinkerer.preloader.AccessTransformer
- Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
- Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
- Transformer: cofh.asm.CoFHClassTransformer
- Transformer: lumien.perfectspawn.Transformer.PSClassTransformer
- Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
- Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
- Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
- Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
- Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
- Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 116 mods loaded, 116 mods active
mcp{9.05} Minecraft Coder Pack Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
FML{7.10.85.1291} Forge Mod Loader Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Forge{10.13.2.1291} Minecraft Forge Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
appliedenergistics2-core{rv2-stable-1} AppliedEnergistics2 Core Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
blightcore{1.2.0} Blight Core Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
CodeChickenCore{1.0.4.29} CodeChicken Core Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MobiusCore{1.2.3} MobiusCore Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
newradicalbotany{1.1.2} New Radical Botany Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
NotEnoughItems{1.0.4.83} Not Enough Items Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
notimefix{2.1.0} No Time Fix Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
PlayerAPI{1.4} Player API Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ThaumicTinkerer-preloader{0.1} Thaumic Tinkerer Core Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
{000} CoFH ASM Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
bspkrsCore{6.16} bspkrsCore Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
StatusEffectHUD{1.27} StatusEffectHUD Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
AppleCore{1.1.0} AppleCore Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
appliedenergistics2{rv2-stable-1} Applied Energistics 2 Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ArchimedesShips{1.7.10 v1.7.1} Archimedes' Ships Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ArmorStatusHUD{1.28} ArmorStatusHUD Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
CoFHCore{1.7.10R3.0.2} CoFH Core Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded{1.7.10R2.8.0} MineFactory Reloaded Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Baubles{1.0.1.10} Baubles Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Thaumcraft{4.2.3.5} Thaumcraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} MFR Compat: Thaumcraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Waila{1.5.8} Waila Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Automagy{0.24.1} Automagy Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
betterrain{0.15} Better Rain Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
betterstorage{0.13.1.126} BetterStorage Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
BiblioCraft{1.10.3} BiblioCraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Mantle{1.7.10-0.3.2.jenkins186} Mantle Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Natura{2.2.0} Natura Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
BiblioWoodsNatura{1.4} BiblioWoods Natura Edition Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ThermalFoundation{1.7.10R1.0.0} Thermal Foundation Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ThermalExpansion{1.7.10R4.0.1} Thermal Expansion Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
BigReactors{0.4.1A2} Big Reactors Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
AWWayofTime{v1.3.0a} Blood Magic: Alchemical Wizardry Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Botania{r1.6-191} Botania Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ChickenChunks{1.3.4.16} ChickenChunks Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
chisel{1.5.7} Chisel Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
cookingbook{1.0.92} Cooking for Blockheads Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
customnpcs{1.7.10c} CustomNpcs Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
EnderStorage{1.4.5.24} EnderStorage Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ForgeMultipart{1.1.1.321} Forge Multipart Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ExtraUtilities{1.2.5} Extra Utilities Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MetallurgyCore{4.0.4} Metallurgy Core Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
TConstruct{1.7.10-1.8.3-RFNerf.DEV.1911337} Tinkers' Construct Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Metallurgy{4.0.5} Metallurgy 4 Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
harvestcraft{1.7.10g} Pam's HarvestCraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ExtraTiC{1.4.5} ExtraTiC Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ThaumicTinkerer{unspecified} Thaumic Tinkerer Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ForbiddenMagic{1.7.10-0.562} Forbidden Magic Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
HelpFixer{1.0.7} HelpFixer Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
HardcoreQuesting{The Journey (4.2.3)} Hardcore Questing Mode Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ImLookingAtBlood{1.1} I'm Looking At Blood Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
inpure|core{1.7.10R1.0.0B9} INpureCore Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
inventorytweaks{1.58-147-645ca10} Inventory Tweaks Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
JABBA{1.1.4} JABBA Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Lockdown{2.0.0} Lockdown Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
LunatriusCore{1.1.2.21} LunatriusCore Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} MFR Compat: Applied Energistics Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} MFR Compat: Atum Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} MFR Compat: BackTools Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} MFR Compat: BuildCraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} MFR Compat: Chococraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} MFR Compat: ExtraBiomes Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} MFR Compat: Forestry Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} MFR Compat: ForgeMicroblock Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} MFR Compat: IC2 Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} MFR Compat: Mystcraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} MFR Compat ProjectRed Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} MFR Compat: Railcraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} MFR Compat: Sufficient Biomes Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} MFR Compat: Thermal Expansion Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} MFR Compat: Tinkers' Construct Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} MFR Compat: TwilightForest Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} MFR Compat: Vanilla Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineTweaker3{3.0.9B} MineTweaker 3 Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
modelcitizens{1.0.1} Model Citizens Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
modtweaker2{0.7} Mod Tweaker 2 Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MouseTweaks{2.4.4} Mouse Tweaks Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
NEIAddons{1.12.2.9} NEI Addons Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
NEIAddons|Botany{1.12.2.9} NEI Addons: Botany Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
NEIAddons|Forestry{1.12.2.9} NEI Addons: Forestry Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
NEIAddons|CraftingTables{1.12.2.9} NEI Addons: Crafting Tables Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
NEIAddons|ExNihilo{1.12.2.9} NEI Addons: Ex Nihilo Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
NEIPlugins{1.1.0.10-unofficial} NEI Plugins Unofficial Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Netherless{0.9.0} Netherless Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
NetherOres{1.7.10R2.3.0RC4} Nether Ores Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
PerfectSpawn{1.1} Perfect Spawn Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
purplepanic{1.0.6} Purple Panic Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
RedstoneArsenal{1.7.10R1.1.0} Redstone Arsenal Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
biomescanner{0.1.0} Biome Scanner Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
blightbuster{0.1.0} BlightBuster Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
cavestokingdoms{0.0.1} Caves to Kingdoms Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
RPGAdvMod{1.0.0} RPGAdvMod Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Schematica{1.7.5.git} Schematica Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
SpiceOfLife{1.2.4} The Spice of Life Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
StorageDrawers{1.7.10-1.5.3} Storage Drawers Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
TabulaRasa{1.7.10R1.0.1} Tabula Rasa Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
playerzombiemod{v1} Tainted Players Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
tcnodetracker{1.1.0} TC Node Tracker Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
TerrainControl{2.7.0-SNAPSHOT} Terrain Control Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
thaumcraftneiplugin{1.7.10-1.7} Thaumcraft NEI Plugin Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
thaumicenergistics{0.8.10.10} Thaumic Energistics Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ThermalDynamics{1.7.10R1.0.0RC7} Thermal Dynamics Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
TiCTooltips{1.2.4} TiC Tooltips Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
TMechworks{1.7.10-67.34d1d9b} Tinkers' Mechworks Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
TML{3.0.1} TooMuchLoot Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Translocator{1.1.1.12} Translocator Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
UndergroundBiomes{0.7} Underground Biomes Constructs Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ubcores{1.7.10-0.1.2.0} UBC Ore Registrar Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
WailaHarvestability{1.1.0} Waila Harvestability Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
McMultipart{1.1.1.321} Minecraft Multipart Plugin Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
HungerOverhaul{1.7.10-1.0.0.DEV.c9b8cee} Hunger Overhaul Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
IguanaTweaksTConstruct{1.7.10-2.1.4.DEV.0edeedd} Iguana Tinker Tweaks Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ForgeMicroblock{1.1.1.321} Forge Microblocks Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
AE2 Version: stable rv2-stable-1 for Forge 10.13.2.1291
CoFHCore: -[1.7.10]3.0.2-268
MineFactoryReloaded: -[1.7.10]2.8.0-104
Mantle Environment: Environment healthy.
ThermalFoundation: -[1.7.10]1.0.0-81
ThermalExpansion: -[1.7.10]4.0.1-182
TConstruct Environment: Environment healthy.
NetherOres: Lacking version information.
RedstoneArsenal: -[1.7.10]1.1.0-80
ThermalDynamics: -[1.7.10]1.0.0RC7-98
AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:ON
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Player Count: 1 / 8; [EntityPlayerMP['kurtegg8'/88, l='MewBlight', x=972.31, y=72.00, z=434.86]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by blay09** [comment]
Weird, I don't see how this is possible. For some reason, the game believed acooking table was a cooking oven. Something super strange must have happened, but I won't be able to do anything about it unless there's more information on how it ended up like this.

**Comment by KurtBuscus** [comment]
Alright, my world corrupted and when I salvaged the world ( I copy pasted random parts of the world file in until it started crashing and got most of my stuff back) and this started happening. When I broke the cooking oven the game crashed and I had to delete it with McEdit.

**Comment by blay09** [comment]
I can only assume that the corruption somehow corrupted things which broke things.

It wasn't Cooking for Blockheads that corrupted the world though, right?

**Comment by KurtBuscus** [comment]
No, I removed all the cooking for blockheads stuff that I had and a few days later it corrupted again (Which made me really mad :P).

**Comment by blay09** [comment]
Okay; anyways it looks like a crash that can only result from corrupted worlds doing weird things, so there's nothing I can do other than adding failchecks (which isn't worth it).
