### ISSUE TITLE
Milk Storage

### ISSUE THREAD

**Issue by blay09** [blay09/CookingForBlockheads#91]

**Comment by blay09** [comment]
Hey @Zero9o1o, think you can make a model for this? I'm thinking something like 

![Milk](http://ecx.images-amazon.com/images/I/31VEgpdhUmL._SY300_.jpg)
or
![Milk](http://1v550a3jlx4d2lc773o373z5qn.wpengine.netdna-cdn.com/wp-content/uploads/2009/05/recycle-plastic-milk-bottle-tops.jpg)

but empty (liquid will be done in code).

It shouldn't be too big (but not too small either, you need to right click it still!), as it'll likely be placed on some table instead of standing on the ground.

**Comment by Zero9o1o** [comment]
How tall you want it like half block tall, quarter ?

**Comment by blay09** [comment]
Half to three quarter I'd say

**Comment by blay09** [comment]
Closed in favor of #117
