### ISSUE TITLE
Unlimited Water when sink is empty of water (1.0.128)

### ISSUE THREAD

**Issue by parcel31u** [blay09/CookingForBlockheads#93]
Allows for infinite water and salt when not even supplied with water at all.

**Comment by blay09** [comment]
It's working fine for me here. Did you enable "sinkRequiresWater" in the config?

Also it could be that you have a water bucket or Fresh Water in your inventory. The recipes will be available then and use that instead.

**Comment by parcel31u** [comment]
Sorry, didn't see the config, thank you.
